// Frozen pre-progression values, used only by the one-time saved-world migration.
export const LEGACY_BALANCE = {
  units: {
    RADIUM_GRENADIER: 24,
    COBALT_SENTINEL: 38,
    ISOTOPE_SNIPER: 19,
    ATOMIC_SAPPER: 25,
    PALE_EXECUTIONER: 45,
    GAMMA_TEMPLAR: 34,
    RADIUM_HUSSAR: 28,
    ISOTOPE_LANCER: 32,
    COBALT_CUIRASSIER: 46,
    ASH_DRAGOON: 27,
    PALE_OUTRIDER: 24,
    GAMMA_PALADIN: 44,
    RADIUM_COURIER: 23,
    ISOTOPE_BIKE: 29,
    COBALT_SIDECAR: 38,
    PALE_HUNTER_BIKE: 25,
    GAMMA_TRIKE: 30,
    APOCALYPSE_BIKE: 36,
    RADIUM_SCOUT_CAR: 35,
    COBALT_HALFTRACK: 48,
    ISOTOPE_TANK_HUNTER: 43,
    MAUSOLEUM_TANK: 76,
    GAMMA_FLAK_CRAWLER: 44,
    APOCALYPSE_CRAWLER: 52,
    RADIUM_RECON: 23,
    ISOTOPE_INTERCEPTOR: 31,
    COBALT_ATTACK_PLANE: 45,
    PALE_NIGHT_FIGHTER: 29,
    GAMMA_BOMBER: 48,
    APOCALYPSE_WING: 62,
    RADIUM_GYRO: 26,
    ISOTOPE_HELICOPTER: 32,
    COBALT_GUNSHIP: 49,
    PALE_HUNTER_HELI: 30,
    GAMMA_HELICOPTER: 36,
    APOCALYPSE_HELICOPTER: 57,
    TERRAFORMER: 10,
    RECON_PLANE: 10,
    FIGHTER: 18,
    BOMBER: 24,
    ZEPPELIN: 38,
    OCCULT_DRAGON: 44,
    FLAK_CANNON: 18,
    TESLA_TROOPER: 14,
    HEX_HUNTER: 11,
    PLAGUE_MEDIC: 9,
    GHOUL_INFANTRY: 16,
    SPECTRAL_RIDER: 15,
    SIEGE_WALKER: 24,
    HEX_TANK: 34,
    MORTAR: 9,
    RIFLEMAN: 10,
    STORMTROOPER: 13,
    MACHINE_GUNNER: 12,
    SNIPER: 7,
    BAZOOKA: 9,
    OFFICER: 12,
    MOTORCYCLE: 11,
    ARMORED_CAR: 19,
    TANK: 32,
    FIELD_GUN: 13,
    ROCKET_LAUNCHER: 16,
    IRON_REVENANT: 23,
    PEASANT: 5,
    MILITIA: 7,
    SPEARMAN: 11,
    CROSSBOW: 8,
    RANGER: 8,
    LIGHT_CAVALRY: 9,
    PALADIN: 18,
    RAM: 20,
    HEALER: 7,
    ENGINEER: 9,
    BERSERKER: 13,
    VOID_ACOLYTE: 7,
    SCOUT: 5,
    INFANTRY: 10,
    GUARD: 15,
    ARCHER: 7,
    KNIGHT: 10,
    SIEGE: 8,
  },
  buildings: {
    ISOTOPE_LAB: {
      hp: 85,
      cost: {
        GOLD: 220,
        WOOD: 80,
        STONE: 100,
        IRON: 150,
        FOOD: 0,
      },
    },
    NUCLEAR_REACTOR: {
      hp: 140,
      cost: {
        GOLD: 400,
        WOOD: 100,
        STONE: 200,
        IRON: 280,
        FOOD: 0,
      },
    },
    HELIPAD: {
      hp: 95,
      cost: {
        GOLD: 280,
        WOOD: 90,
        STONE: 120,
        IRON: 180,
        FOOD: 0,
      },
    },
    ATOMIC_FOUNDRY: {
      hp: 125,
      cost: {
        GOLD: 520,
        WOOD: 140,
        STONE: 180,
        IRON: 360,
        FOOD: 0,
      },
    },
    AERODROME: {
      hp: 75,
      cost: {
        STONE: 70,
        GOLD: 160,
        WOOD: 100,
        IRON: 100,
        FOOD: 0,
      },
    },
    AIRSHIP_YARD: {
      hp: 95,
      cost: {
        STONE: 90,
        GOLD: 210,
        WOOD: 130,
        IRON: 150,
        FOOD: 0,
      },
    },
    DRAGON_ROOST: {
      hp: 110,
      cost: {
        STONE: 160,
        GOLD: 260,
        WOOD: 100,
        IRON: 140,
        FOOD: 0,
      },
    },
    FLAK_BATTERY: {
      hp: 80,
      cost: {
        STONE: 65,
        GOLD: 100,
        WOOD: 50,
        IRON: 85,
        FOOD: 0,
      },
    },
    WOOD_WALL: {
      hp: 30,
      cost: {
        STONE: 0,
        GOLD: 0,
        WOOD: 30,
        IRON: 0,
        FOOD: 0,
      },
    },
    STONE_WALL: {
      hp: 65,
      cost: {
        STONE: 45,
        GOLD: 0,
        WOOD: 0,
        IRON: 0,
        FOOD: 0,
      },
    },
    STEEL_WALL: {
      hp: 100,
      cost: {
        STONE: 0,
        GOLD: 0,
        WOOD: 0,
        IRON: 45,
        FOOD: 0,
      },
    },
    TESLA_COIL: {
      hp: 95,
      cost: {
        STONE: 70,
        GOLD: 90,
        WOOD: 45,
        IRON: 90,
        FOOD: 0,
      },
    },
    CRYPT_BARRACKS: {
      hp: 75,
      cost: {
        STONE: 65,
        GOLD: 100,
        WOOD: 60,
        IRON: 50,
        FOOD: 0,
      },
    },
    ALCHEMY_FOUNDRY: {
      hp: 65,
      cost: {
        STONE: 50,
        GOLD: 130,
        WOOD: 70,
        IRON: 80,
        FOOD: 0,
      },
    },
    BLACK_OBSERVATORY: {
      hp: 55,
      cost: {
        STONE: 60,
        GOLD: 140,
        WOOD: 80,
        IRON: 65,
        FOOD: 0,
      },
    },
    QUARRY: {
      hp: 30,
      cost: {
        GOLD: 25,
        WOOD: 30,
        STONE: 0,
        IRON: 5,
        FOOD: 0,
      },
    },
    ARSENAL: {
      hp: 50,
      cost: {
        STONE: 35,
        GOLD: 70,
        WOOD: 65,
        IRON: 35,
        FOOD: 0,
      },
    },
    BUNKER: {
      hp: 100,
      cost: {
        STONE: 80,
        GOLD: 70,
        WOOD: 35,
        IRON: 100,
        FOOD: 0,
      },
    },
    GARAGE: {
      hp: 50,
      cost: {
        STONE: 0,
        GOLD: 80,
        WOOD: 65,
        IRON: 55,
        FOOD: 0,
      },
    },
    TANK_FACTORY: {
      hp: 75,
      cost: {
        STONE: 65,
        GOLD: 160,
        WOOD: 100,
        IRON: 130,
        FOOD: 0,
      },
    },
    REFINERY: {
      hp: 45,
      cost: {
        STONE: 35,
        GOLD: 100,
        WOOD: 70,
        IRON: 70,
        FOOD: 0,
      },
    },
    MUNITIONS: {
      hp: 45,
      cost: {
        STONE: 25,
        GOLD: 85,
        WOOD: 65,
        IRON: 60,
        FOOD: 0,
      },
    },
    RADIO: {
      hp: 35,
      cost: {
        STONE: 15,
        GOLD: 75,
        WOOD: 40,
        IRON: 65,
        FOOD: 0,
      },
    },
    FIELD_HOSPITAL: {
      hp: 50,
      cost: {
        STONE: 20,
        GOLD: 65,
        WOOD: 65,
        IRON: 25,
        FOOD: 30,
      },
    },
    GUN_BATTERY: {
      hp: 85,
      cost: {
        STONE: 50,
        GOLD: 110,
        WOOD: 60,
        IRON: 100,
        FOOD: 0,
      },
    },
    OCCULT_LAB: {
      hp: 60,
      cost: {
        STONE: 60,
        GOLD: 150,
        WOOD: 80,
        IRON: 100,
        FOOD: 0,
      },
    },
    ROCKET_SILO: {
      hp: 65,
      cost: {
        STONE: 60,
        GOLD: 170,
        WOOD: 80,
        IRON: 140,
        FOOD: 0,
      },
    },
    RAIL_DEPOT: {
      hp: 55,
      cost: {
        STONE: 30,
        GOLD: 90,
        WOOD: 90,
        IRON: 75,
        FOOD: 0,
      },
    },
    CAMP: {
      hp: 30,
      cost: {
        STONE: 0,
        GOLD: 0,
        WOOD: 25,
        IRON: 0,
        FOOD: 0,
      },
    },
    HOUSE: {
      hp: 20,
      cost: {
        STONE: 0,
        GOLD: 0,
        WOOD: 20,
        IRON: 0,
        FOOD: 0,
      },
    },
    GRANARY: {
      hp: 25,
      cost: {
        STONE: 0,
        GOLD: 15,
        WOOD: 40,
        IRON: 0,
        FOOD: 0,
      },
    },
    HUNTER: {
      hp: 20,
      cost: {
        STONE: 0,
        GOLD: 0,
        WOOD: 20,
        IRON: 0,
        FOOD: 0,
      },
    },
    FISHERY: {
      hp: 20,
      cost: {
        STONE: 0,
        GOLD: 10,
        WOOD: 30,
        IRON: 0,
        FOOD: 0,
      },
    },
    STABLE: {
      hp: 35,
      cost: {
        STONE: 0,
        GOLD: 55,
        WOOD: 60,
        IRON: 15,
        FOOD: 25,
      },
    },
    ARCHERY: {
      hp: 30,
      cost: {
        STONE: 0,
        GOLD: 40,
        WOOD: 55,
        IRON: 10,
        FOOD: 10,
      },
    },
    MONASTERY: {
      hp: 45,
      cost: {
        STONE: 40,
        GOLD: 80,
        WOOD: 60,
        IRON: 30,
        FOOD: 20,
      },
    },
    FORGE: {
      hp: 40,
      cost: {
        STONE: 20,
        GOLD: 65,
        WOOD: 45,
        IRON: 35,
        FOOD: 0,
      },
    },
    LIBRARY: {
      hp: 35,
      cost: {
        STONE: 30,
        GOLD: 100,
        WOOD: 70,
        IRON: 30,
        FOOD: 20,
      },
    },
    BAKERY: {
      hp: 25,
      cost: {
        STONE: 10,
        GOLD: 25,
        WOOD: 35,
        IRON: 5,
        FOOD: 10,
      },
    },
    WELL: {
      hp: 30,
      cost: {
        STONE: 10,
        GOLD: 5,
        WOOD: 20,
        IRON: 0,
        FOOD: 0,
      },
    },
    OUTPOST: {
      hp: 35,
      cost: {
        STONE: 0,
        GOLD: 35,
        WOOD: 35,
        IRON: 5,
        FOOD: 0,
      },
    },
    VILLAGE: {
      hp: 35,
      cost: {
        STONE: 20,
        GOLD: 60,
        WOOD: 50,
        IRON: 10,
        FOOD: 25,
      },
    },
    FARM: {
      hp: 15,
      cost: {
        STONE: 0,
        GOLD: 20,
        WOOD: 25,
        IRON: 0,
        FOOD: 0,
      },
    },
    LUMBER: {
      hp: 20,
      cost: {
        STONE: 0,
        GOLD: 25,
        WOOD: 20,
        IRON: 5,
        FOOD: 0,
      },
    },
    MINE: {
      hp: 25,
      cost: {
        STONE: 0,
        GOLD: 35,
        WOOD: 35,
        IRON: 5,
        FOOD: 0,
      },
    },
    MARKET: {
      hp: 25,
      cost: {
        STONE: 0,
        GOLD: 50,
        WOOD: 35,
        IRON: 10,
        FOOD: 10,
      },
    },
    WAREHOUSE: {
      hp: 30,
      cost: {
        STONE: 15,
        GOLD: 35,
        WOOD: 45,
        IRON: 10,
        FOOD: 0,
      },
    },
    WORKSHOP: {
      hp: 30,
      cost: {
        STONE: 15,
        GOLD: 65,
        WOOD: 45,
        IRON: 25,
        FOOD: 0,
      },
    },
    BARRACKS: {
      hp: 40,
      cost: {
        STONE: 20,
        GOLD: 60,
        WOOD: 45,
        IRON: 25,
        FOOD: 10,
      },
    },
    FORT: {
      hp: 65,
      cost: {
        STONE: 65,
        GOLD: 90,
        WOOD: 45,
        IRON: 65,
        FOOD: 0,
      },
    },
    TOWER: {
      hp: 40,
      cost: {
        STONE: 25,
        GOLD: 45,
        WOOD: 25,
        IRON: 30,
        FOOD: 0,
      },
    },
  },
} as const;
