import {
  Crown,
  Sword,
  Eye,
  Castle,
  Bird,
  Star,
  KeyRound,
  Bell,
  Shield,
  Swords,
  Moon,
  Flame,
  Skull,
  Axe,
  Anchor,
  Snowflake,
  Sun,
  Eclipse,
  Atom,
  Radiation,
  Zap,
  Cog,
  Orbit,
  Gem,
  Feather,
  TreePine,
  Mountain,
  Compass,
  type LucideIcon,
} from 'lucide-react';
import type { EmblemId } from '@voidmarch/config';

export const symbols: Record<EmblemId, LucideIcon> = {
  crown: Crown,
  sword: Sword,
  eye: Eye,
  tower: Castle,
  bird: Bird,
  star: Star,
  key: KeyRound,
  bell: Bell,
  shield: Shield,
  swords: Swords,
  moon: Moon,
  flame: Flame,
  skull: Skull,
  axe: Axe,
  anchor: Anchor,
  snowflake: Snowflake,
  sun: Sun,
  eclipse: Eclipse,
  atom: Atom,
  radiation: Radiation,
  zap: Zap,
  cog: Cog,
  orbit: Orbit,
  gem: Gem,
  feather: Feather,
  'tree-pine': TreePine,
  mountain: Mountain,
  compass: Compass,
};
export function emblemIcon(id: string): LucideIcon {
  return Object.prototype.hasOwnProperty.call(symbols, id) ? symbols[id as EmblemId] : Crown;
}
