import type { UnitProfile, UnitTab } from './index';

export const CAMPAIGN_FAMILIES = {
  blood: 'Principautés du Sang',
  abyss: 'Corsaires des Abysses',
  briar: 'Pacte des Ronces',
  frost: 'Légions du Givre',
} as const;
export const CAMPAIGN_COLORS = {
  blood: 14184835,
  abyss: 7522756,
  briar: 10930299,
  frost: 11000308,
} as const;
export const CAMPAIGN_SHEETS = [
  'blood-empire-troops',
  'blood-empire-engines',
  'blood-industrial-troops',
  'blood-industrial-engines',
  'abyss-empire-troops',
  'abyss-empire-engines',
  'abyss-industrial-troops',
  'abyss-industrial-engines',
  'briar-empire-troops',
  'briar-empire-engines',
  'briar-industrial-troops',
  'briar-industrial-engines',
  'frost-empire-troops',
  'frost-empire-engines',
  'frost-industrial-troops',
  'frost-industrial-engines',
] as const;
/** Mid-game prices are base costs, repriced once at tier 2 or 3. */
export const CAMPAIGN_ROSTER = {
  SANG_MUSKET: {
    name: 'Mousquetaire carmin',
    hp: 43,
    attack: 18,
    defense: 4,
    move: 3,
    vision: 5,
    range: 3,
    buildingAttack: 18,
    capture: 2,
    cost: {
      GOLD: 85,
      WOOD: 34,
      STONE: 0,
      IRON: 36,
      FOOD: 27,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 3,
      role: 'Mousquet à poudre : tir direct, soutien de ligne.',
    },
    family: 'blood',
    group: 'MUSKET',
    category: 'Armes à feu',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-troops',
      cell: 0,
      frame: 1080,
    },
  },
  SANG_GRENADIER: {
    name: 'Grenadier du calice',
    hp: 51,
    attack: 20,
    defense: 5,
    move: 3,
    vision: 4,
    range: 2,
    buildingAttack: 29,
    capture: 2,
    cost: {
      GOLD: 110,
      WOOD: 44,
      STONE: 0,
      IRON: 46,
      FOOD: 35,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Grenades lancées en cloche ; utile contre les positions fortifiées, une cible par attaque.',
    },
    family: 'blood',
    group: 'GRENADIER',
    category: 'Armes à feu',
    tier: 2,
    era: 2,
    weapon: 'bomb',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-troops',
      cell: 1,
      frame: 1081,
    },
  },
  SANG_PIKE: {
    name: 'Piquier de la Cour sanglante',
    hp: 65,
    attack: 18,
    defense: 8,
    move: 3,
    vision: 4,
    range: 1,
    buildingAttack: 16,
    capture: 2,
    cost: {
      GOLD: 100,
      WOOD: 40,
      STONE: 0,
      IRON: 42,
      FOOD: 32,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Piques de défense : bonus contre la cavalerie, combat au contact.',
      antiCavalry: 24,
    },
    family: 'blood',
    group: 'PIKE',
    category: 'Infanterie médiévale',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-troops',
      cell: 2,
      frame: 1082,
    },
  },
  SANG_SCOUT: {
    name: 'Éclaireur nocturne',
    hp: 46,
    attack: 13,
    defense: 3,
    move: 8,
    vision: 9,
    range: 1,
    buildingAttack: 13,
    capture: 2,
    cost: {
      GOLD: 100,
      WOOD: 40,
      STONE: 0,
      IRON: 42,
      FOOD: 32,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Reconnaissance montée : grande vision et mobilité, résistance limitée.',
      mounted: true,
    },
    family: 'blood',
    group: 'SCOUT',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: true,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-troops',
      cell: 3,
      frame: 1083,
    },
  },
  SANG_LANCER: {
    name: 'Hussard écarlate',
    hp: 68,
    attack: 25,
    defense: 6,
    move: 7,
    vision: 5,
    range: 1,
    buildingAttack: 23,
    capture: 2,
    cost: {
      GOLD: 145,
      WOOD: 58,
      STONE: 0,
      IRON: 61,
      FOOD: 46,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 5,
      role: 'Charge au contact ; efficace contre les cavaliers.',
      mounted: true,
      antiCavalry: 8,
    },
    family: 'blood',
    group: 'LANCER',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-troops',
      cell: 4,
      frame: 1084,
    },
  },
  SANG_CUIRASSIER: {
    name: 'Cuirassier du tombeau',
    hp: 85,
    attack: 27,
    defense: 10,
    move: 5,
    vision: 4,
    range: 1,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 185,
      WOOD: 74,
      STONE: 0,
      IRON: 78,
      FOOD: 59,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 6,
      role: 'Cavalerie cuirassée pour tenir le contact, vulnérable aux armes antichars.',
      mounted: true,
      armored: true,
    },
    family: 'blood',
    group: 'CUIRASSIER',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-troops',
      cell: 5,
      frame: 1085,
    },
  },
  SANG_CANNON: {
    name: 'Canon reliquaire',
    hp: 67,
    attack: 21,
    defense: 5,
    move: 2,
    vision: 5,
    range: 4,
    buildingAttack: 45,
    capture: 2,
    cost: {
      GOLD: 190,
      WOOD: 76,
      STONE: 0,
      IRON: 80,
      FOOD: 25,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Canon à poudre : tir direct de siège intercepté par les remparts, 2 PA par tir.',
      mechanical: true,
      siege: true,
    },
    family: 'blood',
    group: 'CANNON',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-engines',
      cell: 0,
      frame: 1104,
    },
  },
  SANG_MORTAR: {
    name: 'Mortier des lamentations',
    hp: 60,
    attack: 18,
    defense: 4,
    move: 2,
    vision: 5,
    range: 5,
    buildingAttack: 40,
    capture: 2,
    cost: {
      GOLD: 210,
      WOOD: 84,
      STONE: 0,
      IRON: 88,
      FOOD: 27,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Mortier de siège : tir en cloche au-dessus des remparts, 2 PA, une cible.',
      mechanical: true,
      siege: true,
    },
    family: 'blood',
    group: 'MORTAR',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'shell',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-engines',
      cell: 1,
      frame: 1105,
    },
  },
  SANG_VOLLEY: {
    name: 'Orgue de la Cour rouge',
    hp: 63,
    attack: 27,
    defense: 4,
    move: 2,
    vision: 4,
    range: 3,
    buildingAttack: 29,
    capture: 2,
    cost: {
      GOLD: 230,
      WOOD: 92,
      STONE: 0,
      IRON: 97,
      FOOD: 30,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Orgue à poudre : rafale directe contre une cible, défense fragile.',
      mechanical: true,
    },
    family: 'blood',
    group: 'VOLLEY',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'blood-empire-engines',
      cell: 2,
      frame: 1106,
    },
  },
  SANG_WAGON: {
    name: 'Carrosse de chasse',
    hp: 68,
    attack: 18,
    defense: 5,
    move: 5,
    vision: 5,
    range: 3,
    buildingAttack: 18,
    capture: 2,
    cost: {
      GOLD: 160,
      WOOD: 64,
      STONE: 0,
      IRON: 67,
      FOOD: 21,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 6,
      role: 'Attelage de tir mobile ; circule au sol, ne transporte pas de troupes.',
      mechanical: true,
    },
    family: 'blood',
    group: 'WAGON',
    category: 'Véhicules',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-engines',
      cell: 3,
      frame: 1107,
    },
  },
  SANG_FORT_WAGON: {
    name: 'Fourgon funéraire',
    hp: 95,
    attack: 20,
    defense: 11,
    move: 3,
    vision: 4,
    range: 2,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 230,
      WOOD: 92,
      STONE: 0,
      IRON: 97,
      FOOD: 30,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 8,
      role: 'Fourgon blindé à arbalète : lent et résistant, tir direct.',
      mechanical: true,
      armored: true,
    },
    family: 'blood',
    group: 'FORT_WAGON',
    category: 'Véhicules',
    tier: 2,
    era: 2,
    weapon: 'bolt',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-engines',
      cell: 4,
      frame: 1108,
    },
  },
  SANG_BALLOON: {
    name: 'Ballon du crépuscule',
    hp: 61,
    attack: 16,
    defense: 3,
    move: 3,
    vision: 10,
    range: 3,
    buildingAttack: 36,
    capture: 0,
    cost: {
      GOLD: 240,
      WOOD: 96,
      STONE: 0,
      IRON: 101,
      FOOD: 31,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE', 'LIBRARY'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Ballon de reconnaissance et de siège : vol lent, aucune capture, 2 PA par attaque.',
      mechanical: true,
      flying: true,
      siege: true,
    },
    family: 'blood',
    group: 'BALLOON',
    category: 'Aviation',
    tier: 2,
    era: 2,
    weapon: 'bomb',
    indirect: false,
    recon: true,
    automatic: false,
    sprite: {
      sheet: 'blood-empire-engines',
      cell: 5,
      frame: 1109,
    },
  },
  SANG_RIFLE: {
    name: 'Fusilier des veines noires',
    hp: 77,
    attack: 30,
    defense: 8,
    move: 4,
    vision: 6,
    range: 4,
    buildingAttack: 28,
    capture: 2,
    cost: {
      GOLD: 230,
      WOOD: 34,
      STONE: 0,
      IRON: 138,
      FOOD: 74,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 5,
      role: 'Infanterie de ligne industrielle ; tir direct polyvalent.',
    },
    family: 'blood',
    group: 'RIFLE',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-industrial-troops',
      cell: 0,
      frame: 1128,
    },
  },
  SANG_MG: {
    name: 'Mitrailleur du caveau',
    hp: 91,
    attack: 31,
    defense: 10,
    move: 3,
    vision: 5,
    range: 4,
    buildingAttack: 31,
    capture: 2,
    cost: {
      GOLD: 300,
      WOOD: 45,
      STONE: 0,
      IRON: 180,
      FOOD: 96,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Mitrailleuse de soutien : rafale directe contre une cible.',
    },
    family: 'blood',
    group: 'MG',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'blood-industrial-troops',
      cell: 1,
      frame: 1129,
    },
  },
  SANG_ANTITANK: {
    name: 'Briseur de cercueils',
    hp: 66,
    attack: 24,
    defense: 6,
    move: 3,
    vision: 5,
    range: 4,
    buildingAttack: 35,
    capture: 2,
    cost: {
      GOLD: 310,
      WOOD: 46,
      STONE: 0,
      IRON: 186,
      FOOD: 99,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Lance-roquettes antichar : bonus contre les blindés, tir intercepté par les murs.',
      antiArmor: 28,
    },
    family: 'blood',
    group: 'ANTITANK',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'rocket',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-industrial-troops',
      cell: 2,
      frame: 1130,
    },
  },
  SANG_BIKE: {
    name: 'Moto funéraire',
    hp: 73,
    attack: 23,
    defense: 5,
    move: 8,
    vision: 8,
    range: 3,
    buildingAttack: 23,
    capture: 2,
    cost: {
      GOLD: 250,
      WOOD: 38,
      STONE: 0,
      IRON: 150,
      FOOD: 32,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Moto de reconnaissance : rapide, bonne vision et faible blindage.',
      mechanical: true,
    },
    family: 'blood',
    group: 'BIKE',
    category: 'Motos',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    automatic: true,
    sprite: {
      sheet: 'blood-industrial-troops',
      cell: 3,
      frame: 1131,
    },
  },
  SANG_SIDECAR: {
    name: 'Side-car des héritiers',
    hp: 103,
    attack: 28,
    defense: 8,
    move: 6,
    vision: 6,
    range: 4,
    buildingAttack: 28,
    capture: 2,
    cost: {
      GOLD: 330,
      WOOD: 50,
      STONE: 0,
      IRON: 198,
      FOOD: 43,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 7,
      role: 'Side-car de soutien armé : tir direct, sans transport de troupes.',
      mechanical: true,
    },
    family: 'blood',
    group: 'SIDECAR',
    category: 'Motos',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'blood-industrial-troops',
      cell: 4,
      frame: 1132,
    },
  },
  SANG_DRAGOON: {
    name: 'Dragon sanguinaire',
    hp: 103,
    attack: 32,
    defense: 9,
    move: 6,
    vision: 6,
    range: 3,
    buildingAttack: 30,
    capture: 2,
    cost: {
      GOLD: 320,
      WOOD: 48,
      STONE: 0,
      IRON: 192,
      FOOD: 102,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Cavalerie au fusil : déplacement rapide et tir direct.',
      mounted: true,
    },
    family: 'blood',
    group: 'DRAGOON',
    category: 'Cavalerie',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-industrial-troops',
      cell: 5,
      frame: 1133,
    },
  },
  SANG_LIGHT_TANK: {
    name: 'Char Nosferatu',
    hp: 138,
    attack: 32,
    defense: 13,
    move: 5,
    vision: 5,
    range: 4,
    buildingAttack: 43,
    capture: 2,
    cost: {
      GOLD: 440,
      WOOD: 66,
      STONE: 0,
      IRON: 264,
      FOOD: 57,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 9,
      role: 'Char mobile de soutien : blindage léger, tir direct.',
      mechanical: true,
      armored: true,
    },
    family: 'blood',
    group: 'LIGHT_TANK',
    category: 'Blindés',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-industrial-engines',
      cell: 0,
      frame: 1152,
    },
  },
  SANG_HEAVY_TANK: {
    name: 'Char du sépulcre',
    hp: 183,
    attack: 36,
    defense: 17,
    move: 3,
    vision: 4,
    range: 4,
    buildingAttack: 54,
    capture: 2,
    cost: {
      GOLD: 650,
      WOOD: 98,
      STONE: 0,
      IRON: 390,
      FOOD: 84,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 12,
      role: 'Char lourd : blindage élevé, lent et vulnérable aux antichars.',
      mechanical: true,
      armored: true,
    },
    family: 'blood',
    group: 'HEAVY_TANK',
    category: 'Blindés',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-industrial-engines',
      cell: 1,
      frame: 1153,
    },
  },
  SANG_HOWITZER: {
    name: 'Obusier des martyrs',
    hp: 97,
    attack: 29,
    defense: 8,
    move: 2,
    vision: 5,
    range: 6,
    buildingAttack: 64,
    capture: 2,
    cost: {
      GOLD: 480,
      WOOD: 72,
      STONE: 0,
      IRON: 288,
      FOOD: 62,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 9,
      role: 'Obusier de siège : tir en cloche, 2 PA, une cible par obus.',
      mechanical: true,
      siege: true,
    },
    family: 'blood',
    group: 'HOWITZER',
    category: 'Artillerie',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-industrial-engines',
      cell: 2,
      frame: 1154,
    },
  },
  SANG_FLAK: {
    name: 'DCA des gargouilles',
    hp: 93,
    attack: 25,
    defense: 8,
    move: 3,
    vision: 6,
    range: 5,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 460,
      WOOD: 69,
      STONE: 0,
      IRON: 276,
      FOOD: 60,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 8,
      role: 'Défense antiaérienne : bonus contre les aéronefs, tir direct.',
      mechanical: true,
      antiAir: 32,
    },
    family: 'blood',
    group: 'FLAK',
    category: 'Artillerie',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-industrial-engines',
      cell: 3,
      frame: 1155,
    },
  },
  SANG_FIGHTER: {
    name: 'Chasseur chauve-souris',
    hp: 91,
    attack: 27,
    defense: 7,
    move: 9,
    vision: 8,
    range: 4,
    buildingAttack: 27,
    capture: 0,
    cost: {
      GOLD: 480,
      WOOD: 72,
      STONE: 0,
      IRON: 288,
      FOOD: 62,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['MUNITIONS', 'REFINERY', 'RADIO'],
      minRecruitLevel: 3,
      population: 8,
      role: 'Intercepteur à hélice : bonus antiaérien, aucune capture.',
      mechanical: true,
      flying: true,
      antiAir: 30,
    },
    family: 'blood',
    group: 'FIGHTER',
    category: 'Aviation',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    automatic: true,
    sprite: {
      sheet: 'blood-industrial-engines',
      cell: 4,
      frame: 1156,
    },
  },
  SANG_BOMBER: {
    name: 'Bombardier du dernier bal',
    hp: 133,
    attack: 29,
    defense: 9,
    move: 6,
    vision: 6,
    range: 4,
    buildingAttack: 60,
    capture: 0,
    cost: {
      GOLD: 680,
      WOOD: 102,
      STONE: 0,
      IRON: 408,
      FOOD: 88,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['MUNITIONS', 'REFINERY', 'RADIO'],
      minRecruitLevel: 3,
      population: 11,
      role: 'Bombardier industriel : dégâts de siège, 2 PA, aucune capture ni dégâts de zone.',
      mechanical: true,
      flying: true,
      siege: true,
    },
    family: 'blood',
    group: 'BOMBER',
    category: 'Aviation',
    tier: 3,
    era: 3,
    weapon: 'bomb',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'blood-industrial-engines',
      cell: 5,
      frame: 1157,
    },
  },
  ABYS_MUSKET: {
    name: 'Fusilier naufragé',
    hp: 48,
    attack: 18,
    defense: 4,
    move: 3,
    vision: 5,
    range: 3,
    buildingAttack: 18,
    capture: 2,
    cost: {
      GOLD: 89,
      WOOD: 36,
      STONE: 0,
      IRON: 37,
      FOOD: 28,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 3,
      role: 'Mousquet à poudre : tir direct, soutien de ligne.',
    },
    family: 'abyss',
    group: 'MUSKET',
    category: 'Armes à feu',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-troops',
      cell: 0,
      frame: 1176,
    },
  },
  ABYS_GRENADIER: {
    name: 'Grenadier des épaves',
    hp: 56,
    attack: 20,
    defense: 5,
    move: 3,
    vision: 4,
    range: 2,
    buildingAttack: 29,
    capture: 2,
    cost: {
      GOLD: 116,
      WOOD: 46,
      STONE: 0,
      IRON: 49,
      FOOD: 37,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Grenades lancées en cloche ; utile contre les positions fortifiées, une cible par attaque.',
    },
    family: 'abyss',
    group: 'GRENADIER',
    category: 'Armes à feu',
    tier: 2,
    era: 2,
    weapon: 'bomb',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-troops',
      cell: 1,
      frame: 1177,
    },
  },
  ABYS_PIKE: {
    name: 'Piquier des profondeurs',
    hp: 70,
    attack: 16,
    defense: 8,
    move: 3,
    vision: 4,
    range: 1,
    buildingAttack: 16,
    capture: 2,
    cost: {
      GOLD: 105,
      WOOD: 42,
      STONE: 0,
      IRON: 44,
      FOOD: 34,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Piques de défense : bonus contre la cavalerie, combat au contact.',
      antiCavalry: 24,
    },
    family: 'abyss',
    group: 'PIKE',
    category: 'Infanterie médiévale',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-troops',
      cell: 2,
      frame: 1178,
    },
  },
  ABYS_SCOUT: {
    name: 'Éclaireur des grèves',
    hp: 51,
    attack: 13,
    defense: 3,
    move: 8,
    vision: 9,
    range: 1,
    buildingAttack: 13,
    capture: 2,
    cost: {
      GOLD: 105,
      WOOD: 42,
      STONE: 0,
      IRON: 44,
      FOOD: 34,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Reconnaissance montée : grande vision et mobilité, résistance limitée.',
      mounted: true,
    },
    family: 'abyss',
    group: 'SCOUT',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: true,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-troops',
      cell: 3,
      frame: 1179,
    },
  },
  ABYS_LANCER: {
    name: 'Lancier des marées',
    hp: 73,
    attack: 23,
    defense: 6,
    move: 7,
    vision: 5,
    range: 1,
    buildingAttack: 23,
    capture: 2,
    cost: {
      GOLD: 152,
      WOOD: 61,
      STONE: 0,
      IRON: 64,
      FOOD: 49,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 5,
      role: 'Charge au contact ; efficace contre les cavaliers.',
      mounted: true,
      antiCavalry: 8,
    },
    family: 'abyss',
    group: 'LANCER',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-troops',
      cell: 4,
      frame: 1180,
    },
  },
  ABYS_CUIRASSIER: {
    name: 'Cuirassier du récif',
    hp: 90,
    attack: 25,
    defense: 10,
    move: 5,
    vision: 4,
    range: 1,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 194,
      WOOD: 78,
      STONE: 0,
      IRON: 81,
      FOOD: 62,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 6,
      role: 'Cavalerie cuirassée pour tenir le contact, vulnérable aux armes antichars.',
      mounted: true,
      armored: true,
    },
    family: 'abyss',
    group: 'CUIRASSIER',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-troops',
      cell: 5,
      frame: 1181,
    },
  },
  ABYS_CANNON: {
    name: 'Canon du Kraken',
    hp: 72,
    attack: 21,
    defense: 5,
    move: 2,
    vision: 5,
    range: 4,
    buildingAttack: 50,
    capture: 2,
    cost: {
      GOLD: 200,
      WOOD: 80,
      STONE: 0,
      IRON: 84,
      FOOD: 26,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Canon à poudre : tir direct de siège intercepté par les remparts, 2 PA par tir.',
      mechanical: true,
      siege: true,
    },
    family: 'abyss',
    group: 'CANNON',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-engines',
      cell: 0,
      frame: 1200,
    },
  },
  ABYS_MORTAR: {
    name: 'Mortier des fosses',
    hp: 65,
    attack: 18,
    defense: 4,
    move: 2,
    vision: 5,
    range: 5,
    buildingAttack: 45,
    capture: 2,
    cost: {
      GOLD: 220,
      WOOD: 88,
      STONE: 0,
      IRON: 92,
      FOOD: 29,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Mortier de siège : tir en cloche au-dessus des remparts, 2 PA, une cible.',
      mechanical: true,
      siege: true,
    },
    family: 'abyss',
    group: 'MORTAR',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'shell',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-engines',
      cell: 1,
      frame: 1201,
    },
  },
  ABYS_VOLLEY: {
    name: 'Orgue des naufrages',
    hp: 68,
    attack: 27,
    defense: 4,
    move: 2,
    vision: 4,
    range: 3,
    buildingAttack: 29,
    capture: 2,
    cost: {
      GOLD: 242,
      WOOD: 97,
      STONE: 0,
      IRON: 102,
      FOOD: 31,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Orgue à poudre : rafale directe contre une cible, défense fragile.',
      mechanical: true,
    },
    family: 'abyss',
    group: 'VOLLEY',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'abyss-empire-engines',
      cell: 2,
      frame: 1202,
    },
  },
  ABYS_WAGON: {
    name: 'Attelage des contrebandiers',
    hp: 73,
    attack: 18,
    defense: 5,
    move: 5,
    vision: 5,
    range: 3,
    buildingAttack: 18,
    capture: 2,
    cost: {
      GOLD: 168,
      WOOD: 67,
      STONE: 0,
      IRON: 71,
      FOOD: 22,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 6,
      role: 'Attelage de tir mobile ; circule au sol, ne transporte pas de troupes.',
      mechanical: true,
    },
    family: 'abyss',
    group: 'WAGON',
    category: 'Véhicules',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-engines',
      cell: 3,
      frame: 1203,
    },
  },
  ABYS_FORT_WAGON: {
    name: 'Fourgon du bathyscaphe',
    hp: 100,
    attack: 20,
    defense: 11,
    move: 3,
    vision: 4,
    range: 2,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 242,
      WOOD: 97,
      STONE: 0,
      IRON: 102,
      FOOD: 31,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 8,
      role: 'Fourgon blindé à arbalète : lent et résistant, tir direct.',
      mechanical: true,
      armored: true,
    },
    family: 'abyss',
    group: 'FORT_WAGON',
    category: 'Véhicules',
    tier: 2,
    era: 2,
    weapon: 'bolt',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-engines',
      cell: 4,
      frame: 1204,
    },
  },
  ABYS_BALLOON: {
    name: 'Ballon des brumes salées',
    hp: 66,
    attack: 16,
    defense: 3,
    move: 3,
    vision: 10,
    range: 3,
    buildingAttack: 41,
    capture: 0,
    cost: {
      GOLD: 252,
      WOOD: 101,
      STONE: 0,
      IRON: 106,
      FOOD: 33,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE', 'LIBRARY'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Ballon de reconnaissance et de siège : vol lent, aucune capture, 2 PA par attaque.',
      mechanical: true,
      flying: true,
      siege: true,
    },
    family: 'abyss',
    group: 'BALLOON',
    category: 'Aviation',
    tier: 2,
    era: 2,
    weapon: 'bomb',
    indirect: false,
    recon: true,
    automatic: false,
    sprite: {
      sheet: 'abyss-empire-engines',
      cell: 5,
      frame: 1205,
    },
  },
  ABYS_RIFLE: {
    name: 'Commando scaphandrier',
    hp: 82,
    attack: 28,
    defense: 8,
    move: 4,
    vision: 6,
    range: 4,
    buildingAttack: 28,
    capture: 2,
    cost: {
      GOLD: 242,
      WOOD: 36,
      STONE: 0,
      IRON: 145,
      FOOD: 77,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 5,
      role: 'Infanterie de ligne industrielle ; tir direct polyvalent.',
    },
    family: 'abyss',
    group: 'RIFLE',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-industrial-troops',
      cell: 0,
      frame: 1224,
    },
  },
  ABYS_MG: {
    name: 'Mitrailleur du Léviathan',
    hp: 96,
    attack: 31,
    defense: 10,
    move: 3,
    vision: 5,
    range: 4,
    buildingAttack: 31,
    capture: 2,
    cost: {
      GOLD: 315,
      WOOD: 47,
      STONE: 0,
      IRON: 189,
      FOOD: 101,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Mitrailleuse de soutien : rafale directe contre une cible.',
    },
    family: 'abyss',
    group: 'MG',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'abyss-industrial-troops',
      cell: 1,
      frame: 1225,
    },
  },
  ABYS_ANTITANK: {
    name: 'Harponneur antichar',
    hp: 71,
    attack: 24,
    defense: 6,
    move: 3,
    vision: 5,
    range: 4,
    buildingAttack: 40,
    capture: 2,
    cost: {
      GOLD: 326,
      WOOD: 49,
      STONE: 0,
      IRON: 196,
      FOOD: 104,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Lance-roquettes antichar : bonus contre les blindés, tir intercepté par les murs.',
      antiArmor: 28,
    },
    family: 'abyss',
    group: 'ANTITANK',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'rocket',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-industrial-troops',
      cell: 2,
      frame: 1226,
    },
  },
  ABYS_BIKE: {
    name: 'Moto des embruns',
    hp: 78,
    attack: 23,
    defense: 5,
    move: 8,
    vision: 8,
    range: 3,
    buildingAttack: 23,
    capture: 2,
    cost: {
      GOLD: 262,
      WOOD: 39,
      STONE: 0,
      IRON: 157,
      FOOD: 34,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Moto de reconnaissance : rapide, bonne vision et faible blindage.',
      mechanical: true,
    },
    family: 'abyss',
    group: 'BIKE',
    category: 'Motos',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    automatic: true,
    sprite: {
      sheet: 'abyss-industrial-troops',
      cell: 3,
      frame: 1227,
    },
  },
  ABYS_SIDECAR: {
    name: 'Side-car des épaves',
    hp: 108,
    attack: 28,
    defense: 8,
    move: 6,
    vision: 6,
    range: 4,
    buildingAttack: 28,
    capture: 2,
    cost: {
      GOLD: 346,
      WOOD: 52,
      STONE: 0,
      IRON: 208,
      FOOD: 45,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 7,
      role: 'Side-car de soutien armé : tir direct, sans transport de troupes.',
      mechanical: true,
    },
    family: 'abyss',
    group: 'SIDECAR',
    category: 'Motos',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'abyss-industrial-troops',
      cell: 4,
      frame: 1228,
    },
  },
  ABYS_DRAGOON: {
    name: 'Dragon des récifs',
    hp: 108,
    attack: 30,
    defense: 9,
    move: 6,
    vision: 6,
    range: 3,
    buildingAttack: 30,
    capture: 2,
    cost: {
      GOLD: 336,
      WOOD: 50,
      STONE: 0,
      IRON: 202,
      FOOD: 108,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Cavalerie au fusil : déplacement rapide et tir direct.',
      mounted: true,
    },
    family: 'abyss',
    group: 'DRAGOON',
    category: 'Cavalerie',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-industrial-troops',
      cell: 5,
      frame: 1229,
    },
  },
  ABYS_LIGHT_TANK: {
    name: 'Blindé des marées',
    hp: 143,
    attack: 32,
    defense: 13,
    move: 5,
    vision: 5,
    range: 4,
    buildingAttack: 48,
    capture: 2,
    cost: {
      GOLD: 462,
      WOOD: 69,
      STONE: 0,
      IRON: 277,
      FOOD: 60,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 9,
      role: 'Char mobile de soutien : blindage léger, tir direct.',
      mechanical: true,
      armored: true,
    },
    family: 'abyss',
    group: 'LIGHT_TANK',
    category: 'Blindés',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-industrial-engines',
      cell: 0,
      frame: 1248,
    },
  },
  ABYS_HEAVY_TANK: {
    name: 'Char Léviathan',
    hp: 188,
    attack: 36,
    defense: 17,
    move: 3,
    vision: 4,
    range: 4,
    buildingAttack: 59,
    capture: 2,
    cost: {
      GOLD: 682,
      WOOD: 102,
      STONE: 0,
      IRON: 409,
      FOOD: 89,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 12,
      role: 'Char lourd : blindage élevé, lent et vulnérable aux antichars.',
      mechanical: true,
      armored: true,
    },
    family: 'abyss',
    group: 'HEAVY_TANK',
    category: 'Blindés',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-industrial-engines',
      cell: 1,
      frame: 1249,
    },
  },
  ABYS_HOWITZER: {
    name: 'Obusier du gouffre',
    hp: 102,
    attack: 29,
    defense: 8,
    move: 2,
    vision: 5,
    range: 6,
    buildingAttack: 69,
    capture: 2,
    cost: {
      GOLD: 504,
      WOOD: 76,
      STONE: 0,
      IRON: 302,
      FOOD: 66,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 9,
      role: 'Obusier de siège : tir en cloche, 2 PA, une cible par obus.',
      mechanical: true,
      siege: true,
    },
    family: 'abyss',
    group: 'HOWITZER',
    category: 'Artillerie',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-industrial-engines',
      cell: 2,
      frame: 1250,
    },
  },
  ABYS_FLAK: {
    name: 'DCA des abysses',
    hp: 98,
    attack: 25,
    defense: 8,
    move: 3,
    vision: 6,
    range: 5,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 483,
      WOOD: 72,
      STONE: 0,
      IRON: 290,
      FOOD: 63,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 8,
      role: 'Défense antiaérienne : bonus contre les aéronefs, tir direct.',
      mechanical: true,
      antiAir: 32,
    },
    family: 'abyss',
    group: 'FLAK',
    category: 'Artillerie',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-industrial-engines',
      cell: 3,
      frame: 1251,
    },
  },
  ABYS_FIGHTER: {
    name: 'Chasseur Pétrel',
    hp: 96,
    attack: 27,
    defense: 7,
    move: 9,
    vision: 8,
    range: 4,
    buildingAttack: 27,
    capture: 0,
    cost: {
      GOLD: 504,
      WOOD: 76,
      STONE: 0,
      IRON: 302,
      FOOD: 66,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['MUNITIONS', 'REFINERY', 'RADIO'],
      minRecruitLevel: 3,
      population: 8,
      role: 'Intercepteur à hélice : bonus antiaérien, aucune capture.',
      mechanical: true,
      flying: true,
      antiAir: 30,
    },
    family: 'abyss',
    group: 'FIGHTER',
    category: 'Aviation',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    automatic: true,
    sprite: {
      sheet: 'abyss-industrial-engines',
      cell: 4,
      frame: 1252,
    },
  },
  ABYS_BOMBER: {
    name: 'Bombardier Albatros',
    hp: 138,
    attack: 29,
    defense: 9,
    move: 6,
    vision: 6,
    range: 4,
    buildingAttack: 65,
    capture: 0,
    cost: {
      GOLD: 714,
      WOOD: 107,
      STONE: 0,
      IRON: 428,
      FOOD: 93,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['MUNITIONS', 'REFINERY', 'RADIO'],
      minRecruitLevel: 3,
      population: 11,
      role: 'Bombardier industriel : dégâts de siège, 2 PA, aucune capture ni dégâts de zone.',
      mechanical: true,
      flying: true,
      siege: true,
    },
    family: 'abyss',
    group: 'BOMBER',
    category: 'Aviation',
    tier: 3,
    era: 3,
    weapon: 'bomb',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'abyss-industrial-engines',
      cell: 5,
      frame: 1253,
    },
  },
  RONC_MUSKET: {
    name: 'Arquebusier des bois noirs',
    hp: 36,
    attack: 18,
    defense: 3,
    move: 4,
    vision: 6,
    range: 3,
    buildingAttack: 18,
    capture: 2,
    cost: {
      GOLD: 85,
      WOOD: 34,
      STONE: 0,
      IRON: 36,
      FOOD: 27,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 3,
      role: 'Mousquet à poudre : tir direct, soutien de ligne.',
    },
    family: 'briar',
    group: 'MUSKET',
    category: 'Armes à feu',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-troops',
      cell: 0,
      frame: 1272,
    },
  },
  RONC_GRENADIER: {
    name: 'Grenadier des spores',
    hp: 43,
    attack: 20,
    defense: 4,
    move: 4,
    vision: 5,
    range: 2,
    buildingAttack: 29,
    capture: 2,
    cost: {
      GOLD: 110,
      WOOD: 44,
      STONE: 0,
      IRON: 46,
      FOOD: 35,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Grenades lancées en cloche ; utile contre les positions fortifiées, une cible par attaque.',
    },
    family: 'briar',
    group: 'GRENADIER',
    category: 'Armes à feu',
    tier: 2,
    era: 2,
    weapon: 'bomb',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-troops',
      cell: 1,
      frame: 1273,
    },
  },
  RONC_PIKE: {
    name: 'Piquier des épines',
    hp: 56,
    attack: 16,
    defense: 7,
    move: 4,
    vision: 5,
    range: 1,
    buildingAttack: 16,
    capture: 2,
    cost: {
      GOLD: 100,
      WOOD: 40,
      STONE: 0,
      IRON: 42,
      FOOD: 32,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Piques de défense : bonus contre la cavalerie, combat au contact.',
      antiCavalry: 24,
    },
    family: 'briar',
    group: 'PIKE',
    category: 'Infanterie médiévale',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-troops',
      cell: 2,
      frame: 1274,
    },
  },
  RONC_SCOUT: {
    name: 'Éclaireur des clairières',
    hp: 39,
    attack: 13,
    defense: 2,
    move: 9,
    vision: 10,
    range: 1,
    buildingAttack: 13,
    capture: 2,
    cost: {
      GOLD: 100,
      WOOD: 40,
      STONE: 0,
      IRON: 42,
      FOOD: 32,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Reconnaissance montée : grande vision et mobilité, résistance limitée.',
      mounted: true,
    },
    family: 'briar',
    group: 'SCOUT',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: true,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-troops',
      cell: 3,
      frame: 1275,
    },
  },
  RONC_LANCER: {
    name: 'Lancier au cerf maudit',
    hp: 58,
    attack: 23,
    defense: 5,
    move: 8,
    vision: 6,
    range: 1,
    buildingAttack: 23,
    capture: 2,
    cost: {
      GOLD: 145,
      WOOD: 58,
      STONE: 0,
      IRON: 61,
      FOOD: 46,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 5,
      role: 'Charge au contact ; efficace contre les cavaliers.',
      mounted: true,
      antiCavalry: 8,
    },
    family: 'briar',
    group: 'LANCER',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-troops',
      cell: 4,
      frame: 1276,
    },
  },
  RONC_CUIRASSIER: {
    name: 'Cuirassier des ramures',
    hp: 74,
    attack: 25,
    defense: 9,
    move: 6,
    vision: 5,
    range: 1,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 185,
      WOOD: 74,
      STONE: 0,
      IRON: 78,
      FOOD: 59,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 6,
      role: 'Cavalerie cuirassée pour tenir le contact, vulnérable aux armes antichars.',
      mounted: true,
      armored: true,
    },
    family: 'briar',
    group: 'CUIRASSIER',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-troops',
      cell: 5,
      frame: 1277,
    },
  },
  RONC_CANNON: {
    name: 'Couleuvrine de ronces',
    hp: 58,
    attack: 21,
    defense: 4,
    move: 2,
    vision: 6,
    range: 4,
    buildingAttack: 45,
    capture: 2,
    cost: {
      GOLD: 190,
      WOOD: 76,
      STONE: 0,
      IRON: 80,
      FOOD: 25,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Canon à poudre : tir direct de siège intercepté par les remparts, 2 PA par tir.',
      mechanical: true,
      siege: true,
    },
    family: 'briar',
    group: 'CANNON',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-engines',
      cell: 0,
      frame: 1296,
    },
  },
  RONC_MORTAR: {
    name: 'Mortier des souches',
    hp: 51,
    attack: 18,
    defense: 3,
    move: 2,
    vision: 6,
    range: 5,
    buildingAttack: 40,
    capture: 2,
    cost: {
      GOLD: 210,
      WOOD: 84,
      STONE: 0,
      IRON: 88,
      FOOD: 27,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Mortier de siège : tir en cloche au-dessus des remparts, 2 PA, une cible.',
      mechanical: true,
      siege: true,
    },
    family: 'briar',
    group: 'MORTAR',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'shell',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-engines',
      cell: 1,
      frame: 1297,
    },
  },
  RONC_VOLLEY: {
    name: 'Orgue des épines',
    hp: 54,
    attack: 27,
    defense: 3,
    move: 3,
    vision: 5,
    range: 3,
    buildingAttack: 29,
    capture: 2,
    cost: {
      GOLD: 230,
      WOOD: 92,
      STONE: 0,
      IRON: 97,
      FOOD: 30,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Orgue à poudre : rafale directe contre une cible, défense fragile.',
      mechanical: true,
    },
    family: 'briar',
    group: 'VOLLEY',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'briar-empire-engines',
      cell: 2,
      frame: 1298,
    },
  },
  RONC_WAGON: {
    name: 'Chariot des sorcières',
    hp: 58,
    attack: 18,
    defense: 4,
    move: 6,
    vision: 6,
    range: 3,
    buildingAttack: 18,
    capture: 2,
    cost: {
      GOLD: 160,
      WOOD: 64,
      STONE: 0,
      IRON: 67,
      FOOD: 21,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 6,
      role: 'Attelage de tir mobile ; circule au sol, ne transporte pas de troupes.',
      mechanical: true,
    },
    family: 'briar',
    group: 'WAGON',
    category: 'Véhicules',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-engines',
      cell: 3,
      frame: 1299,
    },
  },
  RONC_FORT_WAGON: {
    name: 'Fourgon des racines',
    hp: 83,
    attack: 20,
    defense: 10,
    move: 4,
    vision: 5,
    range: 2,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 230,
      WOOD: 92,
      STONE: 0,
      IRON: 97,
      FOOD: 30,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 8,
      role: 'Fourgon blindé à arbalète : lent et résistant, tir direct.',
      mechanical: true,
      armored: true,
    },
    family: 'briar',
    group: 'FORT_WAGON',
    category: 'Véhicules',
    tier: 2,
    era: 2,
    weapon: 'bolt',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-engines',
      cell: 4,
      frame: 1300,
    },
  },
  RONC_BALLOON: {
    name: 'Ballon de la chasse sauvage',
    hp: 52,
    attack: 16,
    defense: 2,
    move: 3,
    vision: 11,
    range: 3,
    buildingAttack: 36,
    capture: 0,
    cost: {
      GOLD: 240,
      WOOD: 96,
      STONE: 0,
      IRON: 101,
      FOOD: 31,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE', 'LIBRARY'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Ballon de reconnaissance et de siège : vol lent, aucune capture, 2 PA par attaque.',
      mechanical: true,
      flying: true,
      siege: true,
    },
    family: 'briar',
    group: 'BALLOON',
    category: 'Aviation',
    tier: 2,
    era: 2,
    weapon: 'bomb',
    indirect: false,
    recon: true,
    automatic: false,
    sprite: {
      sheet: 'briar-empire-engines',
      cell: 5,
      frame: 1301,
    },
  },
  RONC_RIFLE: {
    name: 'Tireur des brumes',
    hp: 67,
    attack: 28,
    defense: 7,
    move: 5,
    vision: 7,
    range: 4,
    buildingAttack: 28,
    capture: 2,
    cost: {
      GOLD: 230,
      WOOD: 34,
      STONE: 0,
      IRON: 138,
      FOOD: 74,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 5,
      role: 'Infanterie de ligne industrielle ; tir direct polyvalent.',
    },
    family: 'briar',
    group: 'RIFLE',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-industrial-troops',
      cell: 0,
      frame: 1320,
    },
  },
  RONC_MG: {
    name: 'Mitrailleur des halliers',
    hp: 79,
    attack: 31,
    defense: 9,
    move: 4,
    vision: 6,
    range: 4,
    buildingAttack: 31,
    capture: 2,
    cost: {
      GOLD: 300,
      WOOD: 45,
      STONE: 0,
      IRON: 180,
      FOOD: 96,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Mitrailleuse de soutien : rafale directe contre une cible.',
    },
    family: 'briar',
    group: 'MG',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'briar-industrial-troops',
      cell: 1,
      frame: 1321,
    },
  },
  RONC_ANTITANK: {
    name: 'Briseur de sève',
    hp: 57,
    attack: 24,
    defense: 5,
    move: 4,
    vision: 6,
    range: 4,
    buildingAttack: 35,
    capture: 2,
    cost: {
      GOLD: 310,
      WOOD: 46,
      STONE: 0,
      IRON: 186,
      FOOD: 99,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Lance-roquettes antichar : bonus contre les blindés, tir intercepté par les murs.',
      antiArmor: 28,
    },
    family: 'briar',
    group: 'ANTITANK',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'rocket',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-industrial-troops',
      cell: 2,
      frame: 1322,
    },
  },
  RONC_BIKE: {
    name: 'Moto aux racines',
    hp: 63,
    attack: 23,
    defense: 4,
    move: 9,
    vision: 9,
    range: 3,
    buildingAttack: 23,
    capture: 2,
    cost: {
      GOLD: 250,
      WOOD: 38,
      STONE: 0,
      IRON: 150,
      FOOD: 32,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Moto de reconnaissance : rapide, bonne vision et faible blindage.',
      mechanical: true,
    },
    family: 'briar',
    group: 'BIKE',
    category: 'Motos',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    automatic: true,
    sprite: {
      sheet: 'briar-industrial-troops',
      cell: 3,
      frame: 1323,
    },
  },
  RONC_SIDECAR: {
    name: 'Side-car des sous-bois',
    hp: 90,
    attack: 28,
    defense: 7,
    move: 7,
    vision: 7,
    range: 4,
    buildingAttack: 28,
    capture: 2,
    cost: {
      GOLD: 330,
      WOOD: 50,
      STONE: 0,
      IRON: 198,
      FOOD: 43,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 7,
      role: 'Side-car de soutien armé : tir direct, sans transport de troupes.',
      mechanical: true,
    },
    family: 'briar',
    group: 'SIDECAR',
    category: 'Motos',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'briar-industrial-troops',
      cell: 4,
      frame: 1324,
    },
  },
  RONC_DRAGOON: {
    name: 'Dragon des futaies',
    hp: 90,
    attack: 30,
    defense: 8,
    move: 7,
    vision: 7,
    range: 3,
    buildingAttack: 30,
    capture: 2,
    cost: {
      GOLD: 320,
      WOOD: 48,
      STONE: 0,
      IRON: 192,
      FOOD: 102,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Cavalerie au fusil : déplacement rapide et tir direct.',
      mounted: true,
    },
    family: 'briar',
    group: 'DRAGOON',
    category: 'Cavalerie',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-industrial-troops',
      cell: 5,
      frame: 1325,
    },
  },
  RONC_LIGHT_TANK: {
    name: 'Char des taillis',
    hp: 122,
    attack: 32,
    defense: 12,
    move: 6,
    vision: 6,
    range: 4,
    buildingAttack: 43,
    capture: 2,
    cost: {
      GOLD: 440,
      WOOD: 66,
      STONE: 0,
      IRON: 264,
      FOOD: 57,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 9,
      role: 'Char mobile de soutien : blindage léger, tir direct.',
      mechanical: true,
      armored: true,
    },
    family: 'briar',
    group: 'LIGHT_TANK',
    category: 'Blindés',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-industrial-engines',
      cell: 0,
      frame: 1344,
    },
  },
  RONC_HEAVY_TANK: {
    name: 'Char sylvestre',
    hp: 162,
    attack: 36,
    defense: 16,
    move: 3,
    vision: 5,
    range: 4,
    buildingAttack: 54,
    capture: 2,
    cost: {
      GOLD: 650,
      WOOD: 98,
      STONE: 0,
      IRON: 390,
      FOOD: 84,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 12,
      role: 'Char lourd : blindage élevé, lent et vulnérable aux antichars.',
      mechanical: true,
      armored: true,
    },
    family: 'briar',
    group: 'HEAVY_TANK',
    category: 'Blindés',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-industrial-engines',
      cell: 1,
      frame: 1345,
    },
  },
  RONC_HOWITZER: {
    name: 'Obusier des ronces',
    hp: 85,
    attack: 29,
    defense: 7,
    move: 2,
    vision: 6,
    range: 6,
    buildingAttack: 64,
    capture: 2,
    cost: {
      GOLD: 480,
      WOOD: 72,
      STONE: 0,
      IRON: 288,
      FOOD: 62,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 9,
      role: 'Obusier de siège : tir en cloche, 2 PA, une cible par obus.',
      mechanical: true,
      siege: true,
    },
    family: 'briar',
    group: 'HOWITZER',
    category: 'Artillerie',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-industrial-engines',
      cell: 2,
      frame: 1346,
    },
  },
  RONC_FLAK: {
    name: 'DCA des corbeaux',
    hp: 81,
    attack: 25,
    defense: 7,
    move: 4,
    vision: 7,
    range: 5,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 460,
      WOOD: 69,
      STONE: 0,
      IRON: 276,
      FOOD: 60,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 8,
      role: 'Défense antiaérienne : bonus contre les aéronefs, tir direct.',
      mechanical: true,
      antiAir: 32,
    },
    family: 'briar',
    group: 'FLAK',
    category: 'Artillerie',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-industrial-engines',
      cell: 3,
      frame: 1347,
    },
  },
  RONC_FIGHTER: {
    name: 'Chasseur de la canopée',
    hp: 79,
    attack: 27,
    defense: 6,
    move: 10,
    vision: 9,
    range: 4,
    buildingAttack: 27,
    capture: 0,
    cost: {
      GOLD: 480,
      WOOD: 72,
      STONE: 0,
      IRON: 288,
      FOOD: 62,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['MUNITIONS', 'REFINERY', 'RADIO'],
      minRecruitLevel: 3,
      population: 8,
      role: 'Intercepteur à hélice : bonus antiaérien, aucune capture.',
      mechanical: true,
      flying: true,
      antiAir: 30,
    },
    family: 'briar',
    group: 'FIGHTER',
    category: 'Aviation',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    automatic: true,
    sprite: {
      sheet: 'briar-industrial-engines',
      cell: 4,
      frame: 1348,
    },
  },
  RONC_BOMBER: {
    name: 'Bombardier des spores',
    hp: 117,
    attack: 29,
    defense: 8,
    move: 7,
    vision: 7,
    range: 4,
    buildingAttack: 60,
    capture: 0,
    cost: {
      GOLD: 680,
      WOOD: 102,
      STONE: 0,
      IRON: 408,
      FOOD: 88,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['MUNITIONS', 'REFINERY', 'RADIO'],
      minRecruitLevel: 3,
      population: 11,
      role: 'Bombardier industriel : dégâts de siège, 2 PA, aucune capture ni dégâts de zone.',
      mechanical: true,
      flying: true,
      siege: true,
    },
    family: 'briar',
    group: 'BOMBER',
    category: 'Aviation',
    tier: 3,
    era: 3,
    weapon: 'bomb',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'briar-industrial-engines',
      cell: 5,
      frame: 1349,
    },
  },
  GIVR_MUSKET: {
    name: 'Chasseur polaire',
    hp: 44,
    attack: 18,
    defense: 6,
    move: 3,
    vision: 5,
    range: 3,
    buildingAttack: 18,
    capture: 2,
    cost: {
      GOLD: 92,
      WOOD: 37,
      STONE: 0,
      IRON: 39,
      FOOD: 29,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 3,
      role: 'Mousquet à poudre : tir direct, soutien de ligne.',
    },
    family: 'frost',
    group: 'MUSKET',
    category: 'Armes à feu',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-troops',
      cell: 0,
      frame: 1368,
    },
  },
  GIVR_GRENADIER: {
    name: 'Grenadier des congères',
    hp: 53,
    attack: 20,
    defense: 7,
    move: 3,
    vision: 4,
    range: 2,
    buildingAttack: 29,
    capture: 2,
    cost: {
      GOLD: 119,
      WOOD: 48,
      STONE: 0,
      IRON: 50,
      FOOD: 38,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Grenades lancées en cloche ; utile contre les positions fortifiées, une cible par attaque.',
    },
    family: 'frost',
    group: 'GRENADIER',
    category: 'Armes à feu',
    tier: 2,
    era: 2,
    weapon: 'bomb',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-troops',
      cell: 1,
      frame: 1369,
    },
  },
  GIVR_PIKE: {
    name: 'Piquier du gel noir',
    hp: 68,
    attack: 16,
    defense: 10,
    move: 3,
    vision: 4,
    range: 1,
    buildingAttack: 16,
    capture: 2,
    cost: {
      GOLD: 108,
      WOOD: 43,
      STONE: 0,
      IRON: 45,
      FOOD: 35,
    },
    profile: {
      recruitAt: ['BARRACKS'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Piques de défense : bonus contre la cavalerie, combat au contact.',
      antiCavalry: 24,
    },
    family: 'frost',
    group: 'PIKE',
    category: 'Infanterie médiévale',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-troops',
      cell: 2,
      frame: 1370,
    },
  },
  GIVR_SCOUT: {
    name: 'Éclaireur des blizzards',
    hp: 47,
    attack: 13,
    defense: 5,
    move: 7,
    vision: 9,
    range: 1,
    buildingAttack: 13,
    capture: 2,
    cost: {
      GOLD: 108,
      WOOD: 43,
      STONE: 0,
      IRON: 45,
      FOOD: 35,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 4,
      role: 'Reconnaissance montée : grande vision et mobilité, résistance limitée.',
      mounted: true,
    },
    family: 'frost',
    group: 'SCOUT',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: true,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-troops',
      cell: 3,
      frame: 1371,
    },
  },
  GIVR_LANCER: {
    name: 'Lancier sur loup',
    hp: 72,
    attack: 23,
    defense: 8,
    move: 6,
    vision: 5,
    range: 1,
    buildingAttack: 23,
    capture: 2,
    cost: {
      GOLD: 157,
      WOOD: 63,
      STONE: 0,
      IRON: 66,
      FOOD: 50,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 5,
      role: 'Charge au contact ; efficace contre les cavaliers.',
      mounted: true,
      antiCavalry: 8,
    },
    family: 'frost',
    group: 'LANCER',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-troops',
      cell: 4,
      frame: 1372,
    },
  },
  GIVR_CUIRASSIER: {
    name: 'Cuirassier du grand hiver',
    hp: 90,
    attack: 25,
    defense: 12,
    move: 5,
    vision: 4,
    range: 1,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 200,
      WOOD: 80,
      STONE: 0,
      IRON: 84,
      FOOD: 64,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 6,
      role: 'Cavalerie cuirassée pour tenir le contact, vulnérable aux armes antichars.',
      mounted: true,
      armored: true,
    },
    family: 'frost',
    group: 'CUIRASSIER',
    category: 'Cavalerie',
    tier: 2,
    era: 2,
    weapon: 'none',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-troops',
      cell: 5,
      frame: 1373,
    },
  },
  GIVR_CANNON: {
    name: 'Canon de l’hiver',
    hp: 70,
    attack: 21,
    defense: 7,
    move: 2,
    vision: 5,
    range: 4,
    buildingAttack: 45,
    capture: 2,
    cost: {
      GOLD: 205,
      WOOD: 82,
      STONE: 0,
      IRON: 86,
      FOOD: 27,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Canon à poudre : tir direct de siège intercepté par les remparts, 2 PA par tir.',
      mechanical: true,
      siege: true,
    },
    family: 'frost',
    group: 'CANNON',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-engines',
      cell: 0,
      frame: 1392,
    },
  },
  GIVR_MORTAR: {
    name: 'Mortier des glaces',
    hp: 63,
    attack: 18,
    defense: 6,
    move: 2,
    vision: 5,
    range: 5,
    buildingAttack: 40,
    capture: 2,
    cost: {
      GOLD: 227,
      WOOD: 91,
      STONE: 0,
      IRON: 95,
      FOOD: 30,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Mortier de siège : tir en cloche au-dessus des remparts, 2 PA, une cible.',
      mechanical: true,
      siege: true,
    },
    family: 'frost',
    group: 'MORTAR',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'shell',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-engines',
      cell: 1,
      frame: 1393,
    },
  },
  GIVR_VOLLEY: {
    name: 'Orgue des avalanches',
    hp: 66,
    attack: 27,
    defense: 6,
    move: 2,
    vision: 4,
    range: 3,
    buildingAttack: 29,
    capture: 2,
    cost: {
      GOLD: 248,
      WOOD: 99,
      STONE: 0,
      IRON: 104,
      FOOD: 32,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Orgue à poudre : rafale directe contre une cible, défense fragile.',
      mechanical: true,
    },
    family: 'frost',
    group: 'VOLLEY',
    category: 'Artillerie',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'frost-empire-engines',
      cell: 2,
      frame: 1394,
    },
  },
  GIVR_WAGON: {
    name: 'Traîneau de guerre',
    hp: 72,
    attack: 18,
    defense: 7,
    move: 5,
    vision: 5,
    range: 3,
    buildingAttack: 18,
    capture: 2,
    cost: {
      GOLD: 173,
      WOOD: 69,
      STONE: 0,
      IRON: 73,
      FOOD: 22,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 6,
      role: 'Attelage de tir mobile ; circule au sol, ne transporte pas de troupes.',
      mechanical: true,
    },
    family: 'frost',
    group: 'WAGON',
    category: 'Véhicules',
    tier: 2,
    era: 2,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-engines',
      cell: 3,
      frame: 1395,
    },
  },
  GIVR_FORT_WAGON: {
    name: 'Fourgon des banquises',
    hp: 101,
    attack: 20,
    defense: 13,
    move: 3,
    vision: 4,
    range: 2,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 248,
      WOOD: 99,
      STONE: 0,
      IRON: 104,
      FOOD: 32,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE'],
      minRecruitLevel: 2,
      population: 8,
      role: 'Fourgon blindé à arbalète : lent et résistant, tir direct.',
      mechanical: true,
      armored: true,
    },
    family: 'frost',
    group: 'FORT_WAGON',
    category: 'Véhicules',
    tier: 2,
    era: 2,
    weapon: 'bolt',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-engines',
      cell: 4,
      frame: 1396,
    },
  },
  GIVR_BALLOON: {
    name: 'Ballon de l’aurore',
    hp: 64,
    attack: 16,
    defense: 5,
    move: 3,
    vision: 10,
    range: 3,
    buildingAttack: 36,
    capture: 0,
    cost: {
      GOLD: 259,
      WOOD: 104,
      STONE: 0,
      IRON: 109,
      FOOD: 34,
    },
    profile: {
      recruitAt: ['WORKSHOP'],
      requires: ['FORGE', 'LIBRARY'],
      minRecruitLevel: 2,
      population: 7,
      role: 'Ballon de reconnaissance et de siège : vol lent, aucune capture, 2 PA par attaque.',
      mechanical: true,
      flying: true,
      siege: true,
    },
    family: 'frost',
    group: 'BALLOON',
    category: 'Aviation',
    tier: 2,
    era: 2,
    weapon: 'bomb',
    indirect: false,
    recon: true,
    automatic: false,
    sprite: {
      sheet: 'frost-empire-engines',
      cell: 5,
      frame: 1397,
    },
  },
  GIVR_RIFLE: {
    name: 'Fantassin du pergélisol',
    hp: 81,
    attack: 28,
    defense: 10,
    move: 4,
    vision: 6,
    range: 4,
    buildingAttack: 28,
    capture: 2,
    cost: {
      GOLD: 248,
      WOOD: 37,
      STONE: 0,
      IRON: 149,
      FOOD: 79,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 5,
      role: 'Infanterie de ligne industrielle ; tir direct polyvalent.',
    },
    family: 'frost',
    group: 'RIFLE',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-industrial-troops',
      cell: 0,
      frame: 1416,
    },
  },
  GIVR_MG: {
    name: 'Mitrailleur du bunker gelé',
    hp: 97,
    attack: 31,
    defense: 12,
    move: 3,
    vision: 5,
    range: 4,
    buildingAttack: 31,
    capture: 2,
    cost: {
      GOLD: 324,
      WOOD: 49,
      STONE: 0,
      IRON: 194,
      FOOD: 104,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Mitrailleuse de soutien : rafale directe contre une cible.',
    },
    family: 'frost',
    group: 'MG',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'frost-industrial-troops',
      cell: 1,
      frame: 1417,
    },
  },
  GIVR_ANTITANK: {
    name: 'Briseur de glaciers',
    hp: 69,
    attack: 24,
    defense: 8,
    move: 3,
    vision: 5,
    range: 4,
    buildingAttack: 35,
    capture: 2,
    cost: {
      GOLD: 335,
      WOOD: 50,
      STONE: 0,
      IRON: 201,
      FOOD: 107,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Lance-roquettes antichar : bonus contre les blindés, tir intercepté par les murs.',
      antiArmor: 28,
    },
    family: 'frost',
    group: 'ANTITANK',
    category: 'Armes à feu',
    tier: 3,
    era: 3,
    weapon: 'rocket',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-industrial-troops',
      cell: 2,
      frame: 1418,
    },
  },
  GIVR_BIKE: {
    name: 'Moto chenillée',
    hp: 77,
    attack: 23,
    defense: 7,
    move: 7,
    vision: 8,
    range: 3,
    buildingAttack: 23,
    capture: 2,
    cost: {
      GOLD: 270,
      WOOD: 40,
      STONE: 0,
      IRON: 162,
      FOOD: 35,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Moto de reconnaissance : rapide, bonne vision et faible blindage.',
      mechanical: true,
    },
    family: 'frost',
    group: 'BIKE',
    category: 'Motos',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    automatic: true,
    sprite: {
      sheet: 'frost-industrial-troops',
      cell: 3,
      frame: 1419,
    },
  },
  GIVR_SIDECAR: {
    name: 'Side-car du blizzard',
    hp: 110,
    attack: 28,
    defense: 10,
    move: 6,
    vision: 6,
    range: 4,
    buildingAttack: 28,
    capture: 2,
    cost: {
      GOLD: 356,
      WOOD: 53,
      STONE: 0,
      IRON: 214,
      FOOD: 46,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 7,
      role: 'Side-car de soutien armé : tir direct, sans transport de troupes.',
      mechanical: true,
    },
    family: 'frost',
    group: 'SIDECAR',
    category: 'Motos',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: true,
    sprite: {
      sheet: 'frost-industrial-troops',
      cell: 4,
      frame: 1420,
    },
  },
  GIVR_DRAGOON: {
    name: 'Dragon des neiges',
    hp: 110,
    attack: 30,
    defense: 11,
    move: 5,
    vision: 6,
    range: 3,
    buildingAttack: 30,
    capture: 2,
    cost: {
      GOLD: 346,
      WOOD: 52,
      STONE: 0,
      IRON: 208,
      FOOD: 111,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['MUNITIONS'],
      minRecruitLevel: 3,
      population: 6,
      role: 'Cavalerie au fusil : déplacement rapide et tir direct.',
      mounted: true,
    },
    family: 'frost',
    group: 'DRAGOON',
    category: 'Cavalerie',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-industrial-troops',
      cell: 5,
      frame: 1421,
    },
  },
  GIVR_LIGHT_TANK: {
    name: 'Char de la toundra',
    hp: 148,
    attack: 32,
    defense: 15,
    move: 5,
    vision: 5,
    range: 4,
    buildingAttack: 43,
    capture: 2,
    cost: {
      GOLD: 475,
      WOOD: 71,
      STONE: 0,
      IRON: 285,
      FOOD: 62,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 9,
      role: 'Char mobile de soutien : blindage léger, tir direct.',
      mechanical: true,
      armored: true,
    },
    family: 'frost',
    group: 'LIGHT_TANK',
    category: 'Blindés',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-industrial-engines',
      cell: 0,
      frame: 1440,
    },
  },
  GIVR_HEAVY_TANK: {
    name: 'Char brise-glace',
    hp: 198,
    attack: 36,
    defense: 19,
    move: 3,
    vision: 4,
    range: 4,
    buildingAttack: 54,
    capture: 2,
    cost: {
      GOLD: 702,
      WOOD: 105,
      STONE: 0,
      IRON: 421,
      FOOD: 91,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 12,
      role: 'Char lourd : blindage élevé, lent et vulnérable aux antichars.',
      mechanical: true,
      armored: true,
    },
    family: 'frost',
    group: 'HEAVY_TANK',
    category: 'Blindés',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-industrial-engines',
      cell: 1,
      frame: 1441,
    },
  },
  GIVR_HOWITZER: {
    name: 'Obusier des avalanches',
    hp: 103,
    attack: 29,
    defense: 10,
    move: 2,
    vision: 5,
    range: 6,
    buildingAttack: 64,
    capture: 2,
    cost: {
      GOLD: 518,
      WOOD: 78,
      STONE: 0,
      IRON: 311,
      FOOD: 67,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 9,
      role: 'Obusier de siège : tir en cloche, 2 PA, une cible par obus.',
      mechanical: true,
      siege: true,
    },
    family: 'frost',
    group: 'HOWITZER',
    category: 'Artillerie',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: true,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-industrial-engines',
      cell: 2,
      frame: 1442,
    },
  },
  GIVR_FLAK: {
    name: 'DCA de l’aurore',
    hp: 99,
    attack: 25,
    defense: 10,
    move: 3,
    vision: 6,
    range: 5,
    buildingAttack: 25,
    capture: 2,
    cost: {
      GOLD: 497,
      WOOD: 75,
      STONE: 0,
      IRON: 298,
      FOOD: 65,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['MUNITIONS', 'REFINERY'],
      minRecruitLevel: 3,
      population: 8,
      role: 'Défense antiaérienne : bonus contre les aéronefs, tir direct.',
      mechanical: true,
      antiAir: 32,
    },
    family: 'frost',
    group: 'FLAK',
    category: 'Artillerie',
    tier: 3,
    era: 3,
    weapon: 'shell',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-industrial-engines',
      cell: 3,
      frame: 1443,
    },
  },
  GIVR_FIGHTER: {
    name: 'Chasseur du blizzard',
    hp: 97,
    attack: 27,
    defense: 9,
    move: 9,
    vision: 8,
    range: 4,
    buildingAttack: 27,
    capture: 0,
    cost: {
      GOLD: 518,
      WOOD: 78,
      STONE: 0,
      IRON: 311,
      FOOD: 67,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['MUNITIONS', 'REFINERY', 'RADIO'],
      minRecruitLevel: 3,
      population: 8,
      role: 'Intercepteur à hélice : bonus antiaérien, aucune capture.',
      mechanical: true,
      flying: true,
      antiAir: 30,
    },
    family: 'frost',
    group: 'FIGHTER',
    category: 'Aviation',
    tier: 3,
    era: 3,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    automatic: true,
    sprite: {
      sheet: 'frost-industrial-engines',
      cell: 4,
      frame: 1444,
    },
  },
  GIVR_BOMBER: {
    name: 'Bombardier Boréal',
    hp: 143,
    attack: 29,
    defense: 11,
    move: 6,
    vision: 6,
    range: 4,
    buildingAttack: 60,
    capture: 0,
    cost: {
      GOLD: 734,
      WOOD: 110,
      STONE: 0,
      IRON: 440,
      FOOD: 95,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['MUNITIONS', 'REFINERY', 'RADIO'],
      minRecruitLevel: 3,
      population: 11,
      role: 'Bombardier industriel : dégâts de siège, 2 PA, aucune capture ni dégâts de zone.',
      mechanical: true,
      flying: true,
      siege: true,
    },
    family: 'frost',
    group: 'BOMBER',
    category: 'Aviation',
    tier: 3,
    era: 3,
    weapon: 'bomb',
    indirect: false,
    recon: false,
    automatic: false,
    sprite: {
      sheet: 'frost-industrial-engines',
      cell: 5,
      frame: 1445,
    },
  },
} as const;
export type CampaignUnitKind = keyof typeof CAMPAIGN_ROSTER;
export const CAMPAIGN_KINDS = Object.keys(CAMPAIGN_ROSTER) as CampaignUnitKind[];
function mapped<T>(
  fn: (entry: (typeof CAMPAIGN_ROSTER)[CampaignUnitKind], kind: CampaignUnitKind) => T,
): Record<CampaignUnitKind, T> {
  return Object.fromEntries(
    CAMPAIGN_KINDS.map((kind) => [kind, fn(CAMPAIGN_ROSTER[kind], kind)]),
  ) as Record<CampaignUnitKind, T>;
}
export const CAMPAIGN_UNITS = mapped(
  ({ name, hp, attack, defense, move, vision, range, buildingAttack, capture, cost }) => ({
    name,
    hp,
    attack,
    defense,
    move,
    vision,
    range,
    buildingAttack,
    capture,
    cost,
  }),
);
export const CAMPAIGN_PROFILES = mapped<UnitProfile>((e) => ({
  ...e.profile,
  recruitAt: [...e.profile.recruitAt],
  requires: [...e.profile.requires],
}));
export const CAMPAIGN_TIERS = mapped((e) => e.tier);
export const CAMPAIGN_ERAS = mapped((e) => e.era);
export const CAMPAIGN_CATEGORIES = mapped<UnitTab>((e) => e.category);
export const CAMPAIGN_FRAMES = mapped((e) => e.sprite.frame);
export const CAMPAIGN_INDIRECT = CAMPAIGN_KINDS.filter((k) => CAMPAIGN_ROSTER[k].indirect);
export const CAMPAIGN_RECON = CAMPAIGN_KINDS.filter((k) => CAMPAIGN_ROSTER[k].recon);
export function campaignUnit(kind: string) {
  return Object.hasOwn(CAMPAIGN_ROSTER, kind)
    ? CAMPAIGN_ROSTER[kind as CampaignUnitKind]
    : undefined;
}

export const CAMPAIGN_AUTOMATIC = CAMPAIGN_KINDS.filter((k) => CAMPAIGN_ROSTER[k].automatic);
