import type { UnitProfile, UnitTab } from './index';

export const ELITE_FAMILIES = { solar: 'Dynasties du Soleil noir', neon: 'Shogunat néon' } as const;
export const ELITE_SHEETS = [
  'solar-legions',
  'solar-motors',
  'solar-siege',
  'solar-air',
  'neon-legions',
  'neon-motors',
  'neon-siege',
  'neon-air',
] as const;

/** Explicit late-game designs. Costs are base prices, repriced once by UNIT_TIERS. */
export const ELITE_ROSTER = {
  SOL_KHOPESH: {
    name: 'Gardien au khopesh noir',
    hp: 112,
    attack: 38,
    defense: 12,
    move: 4,
    vision: 5,
    range: 1,
    buildingAttack: 38,
    capture: 2,
    cost: {
      GOLD: 720,
      WOOD: 65,
      STONE: 86,
      IRON: 432,
      FOOD: 115,
    },
    profile: {
      recruitAt: ['CRYPT_BARRACKS', 'ARSENAL'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY'],
      minRecruitLevel: 4,
      population: 8,
      role: 'Infanterie de contact cuirassée, efficace contre la cavalerie.',
      antiCavalry: 24,
    },
    family: 'solar',
    group: 'infantry',
    category: 'Infanterie d’élite',
    tier: 5,
    era: 4,
    weapon: 'none',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-legions',
      cell: 0,
      frame: 888,
    },
  },
  SOL_ANUBIS_GUNNER: {
    name: 'Fusilier d’Anubis',
    hp: 138,
    attack: 46,
    defense: 13,
    move: 3,
    vision: 6,
    range: 4,
    buildingAttack: 46,
    capture: 2,
    cost: {
      GOLD: 1100,
      WOOD: 99,
      STONE: 132,
      IRON: 660,
      FOOD: 176,
    },
    profile: {
      recruitAt: ['CRYPT_BARRACKS', 'ARSENAL'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 10,
      role: 'Infanterie de ligne lourde, tir direct et bonne défense.',
      armored: true,
    },
    family: 'solar',
    group: 'infantry',
    category: 'Infanterie d’élite',
    tier: 6,
    era: 5,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-legions',
      cell: 1,
      frame: 889,
    },
  },
  SOL_OSIRIS_IMMORTAL: {
    name: 'Immortel d’Osiris',
    hp: 205,
    attack: 59,
    defense: 19,
    move: 3,
    vision: 5,
    range: 4,
    buildingAttack: 80,
    capture: 2,
    cost: {
      GOLD: 1700,
      WOOD: 153,
      STONE: 204,
      IRON: 1020,
      FOOD: 272,
    },
    profile: {
      recruitAt: ['CRYPT_BARRACKS', 'ARSENAL'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 14,
      role: 'Garde atomique au sceptre solaire ; lente, blindée et dévastatrice à distance.',
      armored: true,
    },
    family: 'solar',
    group: 'infantry',
    category: 'Infanterie d’élite',
    tier: 6,
    era: 5,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-legions',
      cell: 2,
      frame: 890,
    },
  },
  SOL_SCARAB_LANCER: {
    name: 'Lancier scarabée',
    hp: 145,
    attack: 40,
    defense: 13,
    move: 6,
    vision: 5,
    range: 1,
    buildingAttack: 42,
    capture: 2,
    cost: {
      GOLD: 900,
      WOOD: 81,
      STONE: 108,
      IRON: 540,
      FOOD: 144,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY'],
      minRecruitLevel: 4,
      population: 10,
      role: 'Cavalerie de choc à lance, résistante mais exposée aux armes antichars.',
      mounted: true,
      armored: true,
    },
    family: 'solar',
    group: 'cavalry',
    category: 'Cavalerie',
    tier: 5,
    era: 4,
    weapon: 'none',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-legions',
      cell: 3,
      frame: 891,
    },
  },
  SOL_SOBEK_RIDER: {
    name: 'Dragonnier de Sobek',
    hp: 172,
    attack: 49,
    defense: 15,
    move: 6,
    vision: 6,
    range: 3,
    buildingAttack: 54,
    capture: 2,
    cost: {
      GOLD: 1350,
      WOOD: 122,
      STONE: 162,
      IRON: 810,
      FOOD: 216,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 12,
      role: 'Cavalier sur reptile cuirassé, fusil solaire à moyenne portée.',
      mounted: true,
      armored: true,
    },
    family: 'solar',
    group: 'cavalry',
    category: 'Cavalerie',
    tier: 6,
    era: 5,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-legions',
      cell: 4,
      frame: 892,
    },
  },
  SOL_SPHINX_GUARD: {
    name: 'Garde du sphinx noir',
    hp: 235,
    attack: 64,
    defense: 23,
    move: 5,
    vision: 5,
    range: 1,
    buildingAttack: 84,
    capture: 2,
    cost: {
      GOLD: 1900,
      WOOD: 171,
      STONE: 228,
      IRON: 1140,
      FOOD: 304,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 17,
      role: 'Cavalerie royale de contact, très résistante ; vulnérable aux piquiers.',
      mounted: true,
      armored: true,
    },
    family: 'solar',
    group: 'cavalry',
    category: 'Cavalerie',
    tier: 6,
    era: 5,
    weapon: 'none',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-legions',
      cell: 5,
      frame: 893,
    },
  },
  SOL_DUNE_BIKE: {
    name: 'Moto des dunes noires',
    hp: 102,
    attack: 31,
    defense: 8,
    move: 9,
    vision: 9,
    range: 3,
    buildingAttack: 31,
    capture: 1,
    cost: {
      GOLD: 780,
      WOOD: 70,
      STONE: 94,
      IRON: 468,
      FOOD: 55,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY'],
      minRecruitLevel: 4,
      population: 8,
      role: 'Reconnaissance armée très mobile, blindage léger.',
      mechanical: true,
    },
    family: 'solar',
    group: 'motorcycles',
    category: 'Motos',
    tier: 5,
    era: 4,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    sprite: {
      sheet: 'solar-motors',
      cell: 0,
      frame: 912,
    },
  },
  SOL_KEPHRI_SIDECAR: {
    name: 'Side-car de Khépri',
    hp: 145,
    attack: 43,
    defense: 12,
    move: 7,
    vision: 6,
    range: 4,
    buildingAttack: 45,
    capture: 1,
    cost: {
      GOLD: 1200,
      WOOD: 108,
      STONE: 144,
      IRON: 720,
      FOOD: 84,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 11,
      role: 'Appui mobile à la mitrailleuse, compromis entre vitesse et défense.',
      mechanical: true,
    },
    family: 'solar',
    group: 'motorcycles',
    category: 'Motos',
    tier: 6,
    era: 5,
    weapon: 'bullet',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-motors',
      cell: 1,
      frame: 913,
    },
  },
  SOL_SETH_TRICYCLE: {
    name: 'Tricycle de Seth',
    hp: 175,
    attack: 49,
    defense: 15,
    move: 6,
    vision: 6,
    range: 5,
    buildingAttack: 67,
    capture: 1,
    cost: {
      GOLD: 1650,
      WOOD: 148,
      STONE: 198,
      IRON: 990,
      FOOD: 116,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 13,
      role: 'Moto lourde lance-roquettes antichars, lente pour sa catégorie.',
      mechanical: true,
      antiArmor: 26,
    },
    family: 'solar',
    group: 'motorcycles',
    category: 'Motos',
    tier: 6,
    era: 5,
    weapon: 'rocket',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-motors',
      cell: 2,
      frame: 914,
    },
  },
  SOL_JACKAL_SCOUT: {
    name: 'Automitrailleuse du chacal',
    hp: 145,
    attack: 33,
    defense: 11,
    move: 8,
    vision: 10,
    range: 3,
    buildingAttack: 33,
    capture: 1,
    cost: {
      GOLD: 950,
      WOOD: 86,
      STONE: 114,
      IRON: 570,
      FOOD: 66,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY'],
      minRecruitLevel: 4,
      population: 10,
      role: 'Véhicule léger de reconnaissance à grande vision.',
      mechanical: true,
    },
    family: 'solar',
    group: 'light',
    category: 'Véhicules',
    tier: 5,
    era: 4,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    sprite: {
      sheet: 'solar-motors',
      cell: 3,
      frame: 915,
    },
  },
  SOL_COBRA_CARRIER: {
    name: 'Blindé du cobra royal',
    hp: 205,
    attack: 46,
    defense: 18,
    move: 6,
    vision: 6,
    range: 4,
    buildingAttack: 57,
    capture: 1,
    cost: {
      GOLD: 1550,
      WOOD: 140,
      STONE: 186,
      IRON: 930,
      FOOD: 109,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 14,
      role: 'Véhicule d’appui cuirassé ; canon direct, sans transport de troupes.',
      mechanical: true,
      armored: true,
    },
    family: 'solar',
    group: 'light',
    category: 'Véhicules',
    tier: 6,
    era: 5,
    weapon: 'shell',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-motors',
      cell: 4,
      frame: 916,
    },
  },
  SOL_HORUS_HUNTER: {
    name: 'Chasseur de chars d’Horus',
    hp: 190,
    attack: 44,
    defense: 13,
    move: 6,
    vision: 7,
    range: 5,
    buildingAttack: 64,
    capture: 1,
    cost: {
      GOLD: 1800,
      WOOD: 162,
      STONE: 216,
      IRON: 1080,
      FOOD: 126,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 14,
      role: 'Canon solaire antichar à longue portée, blindage modéré.',
      mechanical: true,
      armored: true,
      antiArmor: 32,
    },
    family: 'solar',
    group: 'light',
    category: 'Véhicules',
    tier: 6,
    era: 5,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-motors',
      cell: 5,
      frame: 917,
    },
  },
  SOL_SCARAB_TANK: {
    name: 'Char scarabée noir',
    hp: 235,
    attack: 49,
    defense: 18,
    move: 4,
    vision: 5,
    range: 4,
    buildingAttack: 65,
    capture: 1,
    cost: {
      GOLD: 1400,
      WOOD: 126,
      STONE: 168,
      IRON: 840,
      FOOD: 98,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY'],
      minRecruitLevel: 4,
      population: 16,
      role: 'Char d’assaut équilibré, canon direct arrêté par les remparts.',
      mechanical: true,
      armored: true,
    },
    family: 'solar',
    group: 'tanks',
    category: 'Blindés',
    tier: 5,
    era: 4,
    weapon: 'shell',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-siege',
      cell: 0,
      frame: 936,
    },
  },
  SOL_OBELISK_TANK: {
    name: 'Char obélisque',
    hp: 275,
    attack: 59,
    defense: 23,
    move: 3,
    vision: 6,
    range: 4,
    buildingAttack: 88,
    capture: 1,
    cost: {
      GOLD: 2100,
      WOOD: 189,
      STONE: 252,
      IRON: 1260,
      FOOD: 147,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 20,
      role: 'Char lourd à rayon solaire, efficace contre les blindés.',
      mechanical: true,
      armored: true,
      antiArmor: 26,
    },
    family: 'solar',
    group: 'tanks',
    category: 'Blindés',
    tier: 6,
    era: 5,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-siege',
      cell: 1,
      frame: 937,
    },
  },
  SOL_PYRAMID_BEHEMOTH: {
    name: 'Pyramide de guerre',
    hp: 335,
    attack: 68,
    defense: 27,
    move: 2,
    vision: 5,
    range: 4,
    buildingAttack: 140,
    capture: 1,
    cost: {
      GOLD: 3200,
      WOOD: 288,
      STONE: 384,
      IRON: 1920,
      FOOD: 224,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 26,
      role: 'Forteresse de siège chenillée, très lente ; 2 PA par tir direct.',
      mechanical: true,
      armored: true,
      siege: true,
    },
    family: 'solar',
    group: 'tanks',
    category: 'Blindés',
    tier: 6,
    era: 5,
    weapon: 'shell',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-siege',
      cell: 2,
      frame: 938,
    },
  },
  SOL_SUN_LANCE: {
    name: 'Lance solaire',
    hp: 145,
    attack: 40,
    defense: 10,
    move: 3,
    vision: 7,
    range: 6,
    buildingAttack: 62,
    capture: 0,
    cost: {
      GOLD: 1300,
      WOOD: 117,
      STONE: 156,
      IRON: 780,
      FOOD: 91,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY'],
      minRecruitLevel: 4,
      population: 12,
      role: 'Artillerie antichar à tir tendu ; les murs interceptent son rayon.',
      mechanical: true,
      siege: true,
      antiArmor: 26,
    },
    family: 'solar',
    group: 'artillery',
    category: 'Artillerie',
    tier: 5,
    era: 4,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-siege',
      cell: 3,
      frame: 939,
    },
  },
  SOL_SARCOPHAGUS_MORTAR: {
    name: 'Mortier sarcophage',
    hp: 170,
    attack: 43,
    defense: 12,
    move: 2,
    vision: 6,
    range: 6,
    buildingAttack: 112,
    capture: 0,
    cost: {
      GOLD: 1900,
      WOOD: 171,
      STONE: 228,
      IRON: 1140,
      FOOD: 133,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 16,
      role: 'Mortier de siège en cloche ; franchit les remparts, une cible par tir.',
      mechanical: true,
      siege: true,
    },
    family: 'solar',
    group: 'artillery',
    category: 'Artillerie',
    tier: 6,
    era: 5,
    weapon: 'shell',
    indirect: true,
    recon: false,
    sprite: {
      sheet: 'solar-siege',
      cell: 4,
      frame: 940,
    },
  },
  SOL_APOPHIS_BATTERY: {
    name: 'Batterie d’Apophis',
    hp: 200,
    attack: 53,
    defense: 14,
    move: 2,
    vision: 7,
    range: 7,
    buildingAttack: 150,
    capture: 0,
    cost: {
      GOLD: 2900,
      WOOD: 261,
      STONE: 348,
      IRON: 1740,
      FOOD: 203,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 22,
      role: 'Missiles de siège plongeants à longue portée ; une cible, 2 PA par tir.',
      mechanical: true,
      siege: true,
    },
    family: 'solar',
    group: 'artillery',
    category: 'Artillerie',
    tier: 6,
    era: 5,
    weapon: 'rocket',
    indirect: true,
    recon: false,
    sprite: {
      sheet: 'solar-siege',
      cell: 5,
      frame: 941,
    },
  },
  SOL_IBIS_INTERCEPTOR: {
    name: 'Intercepteur ibis',
    hp: 145,
    attack: 37,
    defense: 10,
    move: 10,
    vision: 9,
    range: 4,
    buildingAttack: 37,
    capture: 0,
    cost: {
      GOLD: 1300,
      WOOD: 117,
      STONE: 156,
      IRON: 780,
      FOOD: 91,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY'],
      minRecruitLevel: 4,
      population: 12,
      role: 'Chasseur rapide spécialisé contre les aéronefs.',
      mechanical: true,
      flying: true,
      antiAir: 42,
    },
    family: 'solar',
    group: 'planes',
    category: 'Aviation',
    tier: 5,
    era: 4,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    sprite: {
      sheet: 'solar-air',
      cell: 0,
      frame: 960,
    },
  },
  SOL_FALCON_STRIKER: {
    name: 'Faucon de guerre',
    hp: 190,
    attack: 51,
    defense: 14,
    move: 8,
    vision: 7,
    range: 4,
    buildingAttack: 75,
    capture: 0,
    cost: {
      GOLD: 2000,
      WOOD: 180,
      STONE: 240,
      IRON: 1200,
      FOOD: 140,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 16,
      role: 'Avion d’assaut à canon solaire, puissant contre les blindés.',
      mechanical: true,
      flying: true,
      antiArmor: 26,
    },
    family: 'solar',
    group: 'planes',
    category: 'Aviation',
    tier: 6,
    era: 5,
    weapon: 'shell',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-air',
      cell: 1,
      frame: 961,
    },
  },
  SOL_ECLIPSE_BOMBER: {
    name: 'Bombardier de l’éclipse',
    hp: 245,
    attack: 49,
    defense: 17,
    move: 5,
    vision: 7,
    range: 5,
    buildingAttack: 135,
    capture: 0,
    cost: {
      GOLD: 2850,
      WOOD: 256,
      STONE: 342,
      IRON: 1710,
      FOOD: 200,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 22,
      role: 'Bombardier lourd contre les bâtiments ; une cible par largage, 2 PA.',
      mechanical: true,
      flying: true,
      siege: true,
    },
    family: 'solar',
    group: 'planes',
    category: 'Aviation',
    tier: 6,
    era: 5,
    weapon: 'bomb',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-air',
      cell: 2,
      frame: 962,
    },
  },
  SOL_ANKH_GYRO: {
    name: 'Gyrocoptère Ânkh',
    hp: 135,
    attack: 32,
    defense: 8,
    move: 8,
    vision: 11,
    range: 4,
    buildingAttack: 32,
    capture: 0,
    cost: {
      GOLD: 1150,
      WOOD: 104,
      STONE: 138,
      IRON: 690,
      FOOD: 81,
    },
    profile: {
      recruitAt: ['HELIPAD'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY'],
      minRecruitLevel: 4,
      population: 10,
      role: 'Aéronef léger de reconnaissance et d’escorte antiaérienne.',
      mechanical: true,
      flying: true,
      antiAir: 24,
    },
    family: 'solar',
    group: 'hover',
    category: 'Hélicoptères',
    tier: 5,
    era: 4,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    sprite: {
      sheet: 'solar-air',
      cell: 3,
      frame: 963,
    },
  },
  SOL_RA_GUNSHIP: {
    name: 'Canonnière de Râ',
    hp: 195,
    attack: 49,
    defense: 15,
    move: 6,
    vision: 8,
    range: 4,
    buildingAttack: 74,
    capture: 0,
    cost: {
      GOLD: 1900,
      WOOD: 171,
      STONE: 228,
      IRON: 1140,
      FOOD: 133,
    },
    profile: {
      recruitAt: ['HELIPAD'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 16,
      role: 'Hélicoptère lourd antichar ; roquettes guidées, vulnérable à la DCA.',
      mechanical: true,
      flying: true,
      antiArmor: 26,
    },
    family: 'solar',
    group: 'hover',
    category: 'Hélicoptères',
    tier: 6,
    era: 5,
    weapon: 'rocket',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-air',
      cell: 4,
      frame: 964,
    },
  },
  SOL_SOLAR_BARGE: {
    name: 'Barque du soleil noir',
    hp: 300,
    attack: 63,
    defense: 22,
    move: 3,
    vision: 8,
    range: 5,
    buildingAttack: 138,
    capture: 0,
    cost: {
      GOLD: 3200,
      WOOD: 288,
      STONE: 384,
      IRON: 1920,
      FOOD: 224,
    },
    profile: {
      recruitAt: ['HELIPAD'],
      requires: ['RADIO', 'OCCULT_LAB', 'BLACK_OBSERVATORY', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 24,
      role: 'Barge volante de siège à orbes, lente et massive ; une cible par tir.',
      mechanical: true,
      flying: true,
      armored: true,
      siege: true,
    },
    family: 'solar',
    group: 'hover',
    category: 'Hélicoptères',
    tier: 6,
    era: 5,
    weapon: 'orb',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'solar-air',
      cell: 5,
      frame: 965,
    },
  },
  CYB_RONIN: {
    name: 'Rônin chromé',
    hp: 101,
    attack: 40,
    defense: 10,
    move: 5,
    vision: 5,
    range: 1,
    buildingAttack: 38,
    capture: 2,
    cost: {
      GOLD: 763,
      WOOD: 69,
      STONE: 0,
      IRON: 572,
      FOOD: 122,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL'],
      minRecruitLevel: 4,
      population: 8,
      role: 'Duelliste cybernétique au katana, rapide au contact et efficace contre la cavalerie.',
      antiCavalry: 24,
    },
    family: 'neon',
    group: 'infantry',
    category: 'Infanterie d’élite',
    tier: 5,
    era: 4,
    weapon: 'none',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-legions',
      cell: 0,
      frame: 984,
    },
  },
  CYB_RAIL_ASHIGARU: {
    name: 'Ashigaru électromagnétique',
    hp: 108,
    attack: 48,
    defense: 9,
    move: 4,
    vision: 6,
    range: 5,
    buildingAttack: 46,
    capture: 2,
    cost: {
      GOLD: 1166,
      WOOD: 105,
      STONE: 0,
      IRON: 874,
      FOOD: 187,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 10,
      role: 'Tireur de précision à longue portée, fragile au contact.',
      armored: true,
    },
    family: 'neon',
    group: 'infantry',
    category: 'Infanterie d’élite',
    tier: 6,
    era: 5,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-legions',
      cell: 1,
      frame: 985,
    },
  },
  CYB_ONI_GUARD: {
    name: 'Garde Oni',
    hp: 184,
    attack: 67,
    defense: 20,
    move: 4,
    vision: 5,
    range: 1,
    buildingAttack: 80,
    capture: 2,
    cost: {
      GOLD: 1802,
      WOOD: 162,
      STONE: 0,
      IRON: 1352,
      FOOD: 288,
    },
    profile: {
      recruitAt: ['ARSENAL'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 14,
      role: 'Samouraï atomique au tetsubō, lourde frappe de contact contre les blindés.',
      armored: true,
      antiArmor: 30,
    },
    family: 'neon',
    group: 'infantry',
    category: 'Infanterie d’élite',
    tier: 6,
    era: 5,
    weapon: 'none',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-legions',
      cell: 2,
      frame: 986,
    },
  },
  CYB_KIRIN_LANCER: {
    name: 'Lancier Kirin',
    hp: 130,
    attack: 42,
    defense: 11,
    move: 7,
    vision: 5,
    range: 1,
    buildingAttack: 42,
    capture: 2,
    cost: {
      GOLD: 954,
      WOOD: 86,
      STONE: 0,
      IRON: 716,
      FOOD: 153,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL'],
      minRecruitLevel: 4,
      population: 10,
      role: 'Lancier sur destrier mécanique, rapide et vulnérable aux armes antichars.',
      mounted: true,
      armored: true,
      mechanical: true,
    },
    family: 'neon',
    group: 'cavalry',
    category: 'Cavalerie',
    tier: 5,
    era: 4,
    weapon: 'none',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-legions',
      cell: 3,
      frame: 987,
    },
  },
  CYB_NEON_DRAGOON: {
    name: 'Dragon néon',
    hp: 155,
    attack: 51,
    defense: 13,
    move: 7,
    vision: 6,
    range: 3,
    buildingAttack: 54,
    capture: 2,
    cost: {
      GOLD: 1431,
      WOOD: 129,
      STONE: 0,
      IRON: 1073,
      FOOD: 229,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 12,
      role: 'Cavalier cybernétique au fusil électromagnétique, harcèlement à distance.',
      mounted: true,
      armored: true,
      mechanical: true,
    },
    family: 'neon',
    group: 'cavalry',
    category: 'Cavalerie',
    tier: 6,
    era: 5,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-legions',
      cell: 4,
      frame: 988,
    },
  },
  CYB_TIGER_DAIMYO: {
    name: 'Daimyō du tigre d’acier',
    hp: 212,
    attack: 66,
    defense: 21,
    move: 6,
    vision: 5,
    range: 1,
    buildingAttack: 84,
    capture: 2,
    cost: {
      GOLD: 2014,
      WOOD: 181,
      STONE: 0,
      IRON: 1510,
      FOOD: 322,
    },
    profile: {
      recruitAt: ['STABLE'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 17,
      role: 'Cavalerie lourde sur tigre mécanique ; puissante charge de contact.',
      mounted: true,
      armored: true,
      mechanical: true,
    },
    family: 'neon',
    group: 'cavalry',
    category: 'Cavalerie',
    tier: 6,
    era: 5,
    weapon: 'none',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-legions',
      cell: 5,
      frame: 989,
    },
  },
  CYB_SHINOBI_BIKE: {
    name: 'Moto Shinobi',
    hp: 92,
    attack: 33,
    defense: 6,
    move: 10,
    vision: 9,
    range: 3,
    buildingAttack: 31,
    capture: 1,
    cost: {
      GOLD: 827,
      WOOD: 74,
      STONE: 0,
      IRON: 620,
      FOOD: 58,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL'],
      minRecruitLevel: 4,
      population: 8,
      role: 'Éclaireur à moto et pistolet-mitrailleur ; rapide, sans invisibilité.',
      mechanical: true,
    },
    family: 'neon',
    group: 'motorcycles',
    category: 'Motos',
    tier: 5,
    era: 4,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    sprite: {
      sheet: 'neon-motors',
      cell: 0,
      frame: 1008,
    },
  },
  CYB_RAIJIN_SIDECAR: {
    name: 'Side-car Raijin',
    hp: 130,
    attack: 45,
    defense: 10,
    move: 8,
    vision: 6,
    range: 4,
    buildingAttack: 45,
    capture: 1,
    cost: {
      GOLD: 1272,
      WOOD: 114,
      STONE: 0,
      IRON: 954,
      FOOD: 89,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 11,
      role: 'Appui mobile au railgun, précision et vitesse.',
      mechanical: true,
    },
    family: 'neon',
    group: 'motorcycles',
    category: 'Motos',
    tier: 6,
    era: 5,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-motors',
      cell: 1,
      frame: 1009,
    },
  },
  CYB_SHOGUN_TRIKE: {
    name: 'Tricycle du shōgun',
    hp: 158,
    attack: 51,
    defense: 13,
    move: 7,
    vision: 6,
    range: 5,
    buildingAttack: 67,
    capture: 1,
    cost: {
      GOLD: 1749,
      WOOD: 157,
      STONE: 0,
      IRON: 1312,
      FOOD: 122,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 13,
      role: 'Moto lourde à missiles antichars, mobilité inférieure aux éclaireurs.',
      mechanical: true,
      antiArmor: 26,
    },
    family: 'neon',
    group: 'motorcycles',
    category: 'Motos',
    tier: 6,
    era: 5,
    weapon: 'rocket',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-motors',
      cell: 2,
      frame: 1010,
    },
  },
  CYB_KITSUNE_SCOUT: {
    name: 'Éclaireur Kitsune',
    hp: 130,
    attack: 35,
    defense: 9,
    move: 9,
    vision: 10,
    range: 3,
    buildingAttack: 33,
    capture: 1,
    cost: {
      GOLD: 1007,
      WOOD: 91,
      STONE: 0,
      IRON: 755,
      FOOD: 70,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL'],
      minRecruitLevel: 4,
      population: 10,
      role: 'Buggy blindé de reconnaissance à grande vision.',
      mechanical: true,
    },
    family: 'neon',
    group: 'light',
    category: 'Véhicules',
    tier: 5,
    era: 4,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    sprite: {
      sheet: 'neon-motors',
      cell: 3,
      frame: 1011,
    },
  },
  CYB_TANUKI_CARRIER: {
    name: 'Blindé Tanuki',
    hp: 184,
    attack: 48,
    defense: 16,
    move: 7,
    vision: 6,
    range: 4,
    buildingAttack: 57,
    capture: 1,
    cost: {
      GOLD: 1643,
      WOOD: 148,
      STONE: 0,
      IRON: 1232,
      FOOD: 115,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 14,
      role: 'Véhicule d’appui à canon, blindage intermédiaire ; sans transport de troupes.',
      mechanical: true,
      armored: true,
    },
    family: 'neon',
    group: 'light',
    category: 'Véhicules',
    tier: 6,
    era: 5,
    weapon: 'shell',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-motors',
      cell: 4,
      frame: 1012,
    },
  },
  CYB_TENGU_HUNTER: {
    name: 'Chasseur Tengu',
    hp: 171,
    attack: 46,
    defense: 11,
    move: 7,
    vision: 7,
    range: 5,
    buildingAttack: 64,
    capture: 1,
    cost: {
      GOLD: 1908,
      WOOD: 172,
      STONE: 0,
      IRON: 1431,
      FOOD: 134,
    },
    profile: {
      recruitAt: ['GARAGE'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 14,
      role: 'Chasseur de chars au railgun, précis mais vulnérable au siège.',
      mechanical: true,
      armored: true,
      antiArmor: 32,
    },
    family: 'neon',
    group: 'light',
    category: 'Véhicules',
    tier: 6,
    era: 5,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-motors',
      cell: 5,
      frame: 1013,
    },
  },
  CYB_TETSUBO_TANK: {
    name: 'Char Tetsubō',
    hp: 212,
    attack: 51,
    defense: 16,
    move: 5,
    vision: 5,
    range: 4,
    buildingAttack: 65,
    capture: 1,
    cost: {
      GOLD: 1484,
      WOOD: 134,
      STONE: 0,
      IRON: 1113,
      FOOD: 104,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL'],
      minRecruitLevel: 4,
      population: 16,
      role: 'Char d’assaut mobile à canon court, tir direct.',
      mechanical: true,
      armored: true,
    },
    family: 'neon',
    group: 'tanks',
    category: 'Blindés',
    tier: 5,
    era: 4,
    weapon: 'shell',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-siege',
      cell: 0,
      frame: 1032,
    },
  },
  CYB_KABUTO_TANK: {
    name: 'Char Kabuto',
    hp: 248,
    attack: 61,
    defense: 21,
    move: 4,
    vision: 6,
    range: 4,
    buildingAttack: 88,
    capture: 1,
    cost: {
      GOLD: 2226,
      WOOD: 200,
      STONE: 0,
      IRON: 1670,
      FOOD: 156,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 20,
      role: 'Char lourd au railgun, bonus antichar et blindage renforcé.',
      mechanical: true,
      armored: true,
      antiArmor: 26,
    },
    family: 'neon',
    group: 'tanks',
    category: 'Blindés',
    tier: 6,
    era: 5,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-siege',
      cell: 1,
      frame: 1033,
    },
  },
  CYB_ONI_FORTRESS: {
    name: 'Forteresse Oni',
    hp: 302,
    attack: 70,
    defense: 25,
    move: 3,
    vision: 5,
    range: 4,
    buildingAttack: 140,
    capture: 1,
    cost: {
      GOLD: 3392,
      WOOD: 305,
      STONE: 0,
      IRON: 2544,
      FOOD: 237,
    },
    profile: {
      recruitAt: ['TANK_FACTORY'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 26,
      role: 'Char de siège à canon lourd, massif et lent ; 2 PA par tir.',
      mechanical: true,
      armored: true,
      siege: true,
    },
    family: 'neon',
    group: 'tanks',
    category: 'Blindés',
    tier: 6,
    era: 5,
    weapon: 'shell',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-siege',
      cell: 2,
      frame: 1034,
    },
  },
  CYB_YUMI_RAILGUN: {
    name: 'Railgun Yumi',
    hp: 130,
    attack: 42,
    defense: 8,
    move: 4,
    vision: 7,
    range: 6,
    buildingAttack: 62,
    capture: 0,
    cost: {
      GOLD: 1378,
      WOOD: 124,
      STONE: 0,
      IRON: 1034,
      FOOD: 96,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL'],
      minRecruitLevel: 4,
      population: 12,
      role: 'Artillerie électromagnétique antichar à tir direct, arrêtée par les murs.',
      mechanical: true,
      siege: true,
      antiArmor: 26,
    },
    family: 'neon',
    group: 'artillery',
    category: 'Artillerie',
    tier: 5,
    era: 4,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-siege',
      cell: 3,
      frame: 1035,
    },
  },
  CYB_TAIKO_MORTAR: {
    name: 'Mortier Taiko',
    hp: 153,
    attack: 45,
    defense: 10,
    move: 3,
    vision: 6,
    range: 6,
    buildingAttack: 112,
    capture: 0,
    cost: {
      GOLD: 2014,
      WOOD: 181,
      STONE: 0,
      IRON: 1510,
      FOOD: 141,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 16,
      role: 'Mortier de siège en cloche ; frappe au-delà des remparts, une cible.',
      mechanical: true,
      siege: true,
    },
    family: 'neon',
    group: 'artillery',
    category: 'Artillerie',
    tier: 6,
    era: 5,
    weapon: 'shell',
    indirect: true,
    recon: false,
    sprite: {
      sheet: 'neon-siege',
      cell: 4,
      frame: 1036,
    },
  },
  CYB_OROCHI_MISSILES: {
    name: 'Batterie Orochi',
    hp: 180,
    attack: 55,
    defense: 12,
    move: 3,
    vision: 7,
    range: 7,
    buildingAttack: 150,
    capture: 0,
    cost: {
      GOLD: 3074,
      WOOD: 277,
      STONE: 0,
      IRON: 2306,
      FOOD: 215,
    },
    profile: {
      recruitAt: ['GUN_BATTERY'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 22,
      role: 'Missiles plongeants à longue portée ; spécialisée contre les bâtiments.',
      mechanical: true,
      siege: true,
    },
    family: 'neon',
    group: 'artillery',
    category: 'Artillerie',
    tier: 6,
    era: 5,
    weapon: 'rocket',
    indirect: true,
    recon: false,
    sprite: {
      sheet: 'neon-siege',
      cell: 5,
      frame: 1037,
    },
  },
  CYB_TSURU_INTERCEPTOR: {
    name: 'Intercepteur Tsuru',
    hp: 130,
    attack: 39,
    defense: 8,
    move: 11,
    vision: 9,
    range: 4,
    buildingAttack: 37,
    capture: 0,
    cost: {
      GOLD: 1378,
      WOOD: 124,
      STONE: 0,
      IRON: 1034,
      FOOD: 96,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL'],
      minRecruitLevel: 4,
      population: 12,
      role: 'Chasseur à railguns très mobile, spécialisé dans la chasse aérienne.',
      mechanical: true,
      flying: true,
      antiAir: 42,
    },
    family: 'neon',
    group: 'planes',
    category: 'Aviation',
    tier: 5,
    era: 4,
    weapon: 'lightning',
    indirect: false,
    recon: true,
    sprite: {
      sheet: 'neon-air',
      cell: 0,
      frame: 1056,
    },
  },
  CYB_HAYABUSA_STRIKER: {
    name: 'Avion d’assaut Hayabusa',
    hp: 171,
    attack: 53,
    defense: 12,
    move: 9,
    vision: 7,
    range: 4,
    buildingAttack: 75,
    capture: 0,
    cost: {
      GOLD: 2120,
      WOOD: 191,
      STONE: 0,
      IRON: 1590,
      FOOD: 148,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 16,
      role: 'Avion à railguns antichars, blindage plus léger que son homologue solaire.',
      mechanical: true,
      flying: true,
      antiArmor: 26,
    },
    family: 'neon',
    group: 'planes',
    category: 'Aviation',
    tier: 6,
    era: 5,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-air',
      cell: 1,
      frame: 1057,
    },
  },
  CYB_YOMI_BOMBER: {
    name: 'Bombardier Yomi',
    hp: 220,
    attack: 51,
    defense: 15,
    move: 6,
    vision: 7,
    range: 5,
    buildingAttack: 135,
    capture: 0,
    cost: {
      GOLD: 3021,
      WOOD: 272,
      STONE: 0,
      IRON: 2266,
      FOOD: 211,
    },
    profile: {
      recruitAt: ['AERODROME'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 22,
      role: 'Bombardier de siège à silhouette furtive, sans invisibilité ; une cible.',
      mechanical: true,
      flying: true,
      siege: true,
    },
    family: 'neon',
    group: 'planes',
    category: 'Aviation',
    tier: 6,
    era: 5,
    weapon: 'bomb',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-air',
      cell: 2,
      frame: 1058,
    },
  },
  CYB_TONBO_ROTOR: {
    name: 'Hélicoptère Tonbo',
    hp: 122,
    attack: 34,
    defense: 6,
    move: 9,
    vision: 11,
    range: 4,
    buildingAttack: 32,
    capture: 0,
    cost: {
      GOLD: 1219,
      WOOD: 110,
      STONE: 0,
      IRON: 914,
      FOOD: 85,
    },
    profile: {
      recruitAt: ['HELIPAD'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL'],
      minRecruitLevel: 4,
      population: 10,
      role: 'Éclaireur aérien rapide, escorte antiaérienne et grande vision.',
      mechanical: true,
      flying: true,
      antiAir: 24,
    },
    family: 'neon',
    group: 'hover',
    category: 'Hélicoptères',
    tier: 5,
    era: 4,
    weapon: 'bullet',
    indirect: false,
    recon: true,
    sprite: {
      sheet: 'neon-air',
      cell: 3,
      frame: 1059,
    },
  },
  CYB_RAIJU_GUNSHIP: {
    name: 'Canonnière Raijū',
    hp: 176,
    attack: 51,
    defense: 13,
    move: 7,
    vision: 8,
    range: 4,
    buildingAttack: 74,
    capture: 0,
    cost: {
      GOLD: 2014,
      WOOD: 181,
      STONE: 0,
      IRON: 1510,
      FOOD: 141,
    },
    profile: {
      recruitAt: ['HELIPAD'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 16,
      role: 'Hélicoptère de chasse aux blindés avec missiles guidés.',
      mechanical: true,
      flying: true,
      antiArmor: 26,
    },
    family: 'neon',
    group: 'hover',
    category: 'Hélicoptères',
    tier: 6,
    era: 5,
    weapon: 'rocket',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-air',
      cell: 4,
      frame: 1060,
    },
  },
  CYB_SHOGUN_CITADEL: {
    name: 'Citadelle volante du shōgun',
    hp: 270,
    attack: 65,
    defense: 20,
    move: 4,
    vision: 8,
    range: 5,
    buildingAttack: 138,
    capture: 0,
    cost: {
      GOLD: 3392,
      WOOD: 305,
      STONE: 0,
      IRON: 2544,
      FOOD: 237,
    },
    profile: {
      recruitAt: ['HELIPAD'],
      requires: ['RADIO', 'OCCULT_LAB', 'TESLA_COIL', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
      minRecruitLevel: 5,
      population: 24,
      role: 'Forteresse volante de siège ; lourd rayon direct depuis les airs, une cible.',
      mechanical: true,
      flying: true,
      armored: true,
      siege: true,
    },
    family: 'neon',
    group: 'hover',
    category: 'Hélicoptères',
    tier: 6,
    era: 5,
    weapon: 'lightning',
    indirect: false,
    recon: false,
    sprite: {
      sheet: 'neon-air',
      cell: 5,
      frame: 1061,
    },
  },
} as const;
export type EliteUnitKind = keyof typeof ELITE_ROSTER;
export const ELITE_KINDS = Object.keys(ELITE_ROSTER) as EliteUnitKind[];
function mapped<T>(
  fn: (entry: (typeof ELITE_ROSTER)[EliteUnitKind], kind: EliteUnitKind) => T,
): Record<EliteUnitKind, T> {
  return Object.fromEntries(
    ELITE_KINDS.map((kind) => [kind, fn(ELITE_ROSTER[kind], kind)]),
  ) as Record<EliteUnitKind, T>;
}
export const ELITE_UNITS = mapped(
  ({ name, hp, attack, defense, move, vision, range, buildingAttack, capture, cost }) => ({
    name,
    hp,
    attack,
    defense,
    move,
    vision,
    range,
    buildingAttack,
    capture,
    cost,
  }),
);
export const ELITE_PROFILES = mapped<UnitProfile>((e) => ({
  ...e.profile,
  recruitAt: [...e.profile.recruitAt],
  requires: [...e.profile.requires],
}));
export const ELITE_TIERS = mapped((e) => e.tier);
export const ELITE_ERAS = mapped((e) => e.era);
export const ELITE_CATEGORIES = mapped<UnitTab>((e) => e.category);
export const ELITE_FRAMES = mapped((e) => e.sprite.frame);
export const ELITE_INDIRECT = ELITE_KINDS.filter((k) => ELITE_ROSTER[k].indirect);
export const ELITE_RECON = ELITE_KINDS.filter((k) => ELITE_ROSTER[k].recon);
export function eliteUnit(kind: string) {
  return Object.hasOwn(ELITE_ROSTER, kind) ? ELITE_ROSTER[kind as EliteUnitKind] : undefined;
}
