/** Shared catalogue for player banners and newly awarded mission medals. */
export const EMBLEM_IDS = [
  'crown',
  'sword',
  'eye',
  'tower',
  'bird',
  'star',
  'key',
  'bell',
  'shield',
  'swords',
  'moon',
  'flame',
  'skull',
  'axe',
  'anchor',
  'snowflake',
  'sun',
  'eclipse',
  'atom',
  'radiation',
  'zap',
  'cog',
  'orbit',
  'gem',
  'feather',
  'tree-pine',
  'mountain',
  'compass',
] as const;
export type EmblemId = (typeof EMBLEM_IDS)[number];
export const EMBLEM_NAMES: Record<EmblemId, string> = {
  crown: 'Couronne',
  sword: 'Épée',
  eye: 'Œil',
  tower: 'Tour',
  bird: 'Oiseau',
  star: 'Étoile',
  key: 'Clé',
  bell: 'Cloche',
  shield: 'Bouclier',
  swords: 'Lames',
  moon: 'Lune',
  flame: 'Flamme',
  skull: 'Crâne',
  axe: 'Hache',
  anchor: 'Ancre',
  snowflake: 'Flocon',
  sun: 'Soleil',
  eclipse: 'Éclipse',
  atom: 'Atome',
  radiation: 'Radiation',
  zap: 'Foudre',
  cog: 'Engrenage',
  orbit: 'Orbite',
  gem: 'Cristal',
  feather: 'Plume',
  'tree-pine': 'Sapin',
  mountain: 'Montagne',
  compass: 'Boussole',
};
