import {
  ERA_REINFORCEMENTS,
  ERA_REINFORCEMENT_PROFILES,
  ERA_REINFORCEMENT_AGES,
} from './era-reinforcements';
import type { UnitProfile } from './index';

/** Complements the medieval, industrial and occult roster without replacing it. */
export const EPOCH_UNITS = {
  ...ERA_REINFORCEMENTS,
  MUSKETEER: {
    name: 'Mousquetaire impérial',
    hp: 38,
    attack: 18,
    defense: 4,
    move: 3,
    vision: 5,
    range: 3,
    capture: 2,
    cost: { GOLD: 85, WOOD: 35, STONE: 0, IRON: 40, FOOD: 30 },
  },
  IMPERIAL_GRENADIER: {
    name: 'Grenadier des cendres',
    hp: 48,
    attack: 21,
    buildingAttack: 30,
    defense: 5,
    move: 3,
    vision: 4,
    range: 2,
    capture: 2,
    cost: { GOLD: 110, WOOD: 25, STONE: 0, IRON: 55, FOOD: 35 },
  },
  CUIRASSIER: {
    name: 'Cuirassier du crépuscule',
    hp: 72,
    attack: 24,
    defense: 8,
    move: 6,
    vision: 5,
    range: 1,
    capture: 2,
    cost: { GOLD: 150, WOOD: 30, STONE: 0, IRON: 70, FOOD: 70 },
  },
  COMMANDO: {
    name: 'Commando de l’éclipse',
    hp: 100,
    attack: 40,
    defense: 11,
    move: 5,
    vision: 7,
    range: 4,
    capture: 3,
    cost: { GOLD: 320, WOOD: 50, STONE: 0, IRON: 210, FOOD: 65 },
  },
  DRONE_OPERATOR: {
    name: 'Escouade de drones spectres',
    hp: 86,
    attack: 38,
    buildingAttack: 48,
    defense: 8,
    move: 4,
    vision: 9,
    range: 5,
    capture: 1,
    cost: { GOLD: 420, WOOD: 40, STONE: 0, IRON: 280, FOOD: 60 },
  },
  NEUTRON_GUARD: {
    name: 'Garde à neutrons',
    hp: 180,
    attack: 62,
    buildingAttack: 82,
    defense: 18,
    move: 3,
    vision: 6,
    range: 4,
    capture: 2,
    cost: { GOLD: 950, WOOD: 90, STONE: 0, IRON: 700, FOOD: 100 },
  },
} as const;
export const EPOCH_PROFILES = {
  ...ERA_REINFORCEMENT_PROFILES,
  MUSKETEER: {
    recruitAt: ['BARRACKS'],
    requires: ['FORGE'],
    minRecruitLevel: 2,
    role: 'Infanterie impériale à mousquet ; tir direct. Caserne niveau 2, forge nécessaire.',
  },
  IMPERIAL_GRENADIER: {
    recruitAt: ['BARRACKS'],
    requires: ['FORGE'],
    minRecruitLevel: 2,
    role: 'Grenades en cloche, efficaces contre les fortifications. Caserne niveau 2, forge nécessaire.',
    siege: true,
  },
  CUIRASSIER: {
    recruitAt: ['STABLE'],
    requires: ['FORGE'],
    minRecruitLevel: 2,
    role: 'Cavalerie impériale cuirassée, rapide et résistante au corps à corps. Écurie niveau 2.',
    mounted: true,
    armored: true,
  },
  COMMANDO: {
    recruitAt: ['BARRACKS', 'ARSENAL'],
    requires: ['RADIO'],
    minRecruitLevel: 4,
    role: 'Infanterie moderne mobile, fusil à longue portée et reconnaissance. Bâtiment recruteur niveau 4, relais radio nécessaire.',
  },
  DRONE_OPERATOR: {
    recruitAt: ['WORKSHOP'],
    requires: ['RADIO', 'MUNITIONS'],
    minRecruitLevel: 4,
    role: 'Opérateurs au sol et drones de frappe : attaques aériennes au-dessus des remparts. Atelier niveau 4. Vulnérables au contact.',
    mechanical: true,
  },
  NEUTRON_GUARD: {
    recruitAt: ['BARRACKS', 'CRYPT_BARRACKS'],
    requires: ['NUCLEAR_REACTOR'],
    minRecruitLevel: 5,
    role: 'Infanterie atomique lourde, rayons directs dévastateurs. Bâtiment recruteur niveau 5 et réacteur noir nécessaires.',
    armored: true,
    radioactive: true,
  },
} satisfies Record<keyof typeof EPOCH_UNITS, UnitProfile>;

export const UNIT_ERAS = {
  ...ERA_REINFORCEMENT_AGES,
  MUSKETEER: 2,
  IMPERIAL_GRENADIER: 2,
  CUIRASSIER: 2,
  COMMANDO: 4,
  DRONE_OPERATOR: 4,
  NEUTRON_GUARD: 5,
} as const;
