import type { UnitProfile, UnitTab } from './index';

/** Four complementary recruits per age; existing units remain available. */
export const ERA_REINFORCEMENTS = {
  HALBERDIER: {
    name: 'Hallebardier des remparts',
    hp: 42,
    attack: 10,
    defense: 5,
    move: 3,
    vision: 4,
    range: 1,
    capture: 2,
    cost: {
      GOLD: 45,
      WOOD: 25,
      STONE: 0,
      IRON: 20,
      FOOD: 25,
    },
  },
  LONGBOWMAN: {
    name: 'Archer des longues ombres',
    hp: 25,
    attack: 11,
    defense: 2,
    move: 3,
    vision: 6,
    range: 4,
    capture: 1,
    cost: {
      GOLD: 50,
      WOOD: 50,
      STONE: 0,
      IRON: 10,
      FOOD: 20,
    },
  },
  MOUNTED_OUTRIDER: {
    name: 'Éclaireur des landes',
    hp: 32,
    attack: 7,
    defense: 2,
    move: 8,
    vision: 9,
    range: 1,
    capture: 1,
    cost: {
      GOLD: 65,
      WOOD: 20,
      STONE: 0,
      IRON: 10,
      FOOD: 50,
    },
  },
  WAR_WAGON: {
    name: 'Chariot de guerre',
    hp: 62,
    attack: 12,
    defense: 7,
    move: 3,
    vision: 4,
    range: 2,
    capture: 1,
    cost: {
      GOLD: 90,
      WOOD: 100,
      STONE: 0,
      IRON: 35,
      FOOD: 30,
    },
  },
  IMPERIAL_PIKEMAN: {
    name: 'Piquier de la Cour noire',
    hp: 60,
    attack: 17,
    defense: 8,
    move: 3,
    vision: 4,
    range: 1,
    capture: 2,
    cost: {
      GOLD: 100,
      WOOD: 40,
      STONE: 0,
      IRON: 55,
      FOOD: 35,
    },
  },
  BLACK_DRAGOON: {
    name: 'Dragon de l’Empire noir',
    hp: 66,
    attack: 20,
    defense: 6,
    move: 6,
    vision: 6,
    range: 3,
    capture: 2,
    cost: {
      GOLD: 170,
      WOOD: 40,
      STONE: 0,
      IRON: 70,
      FOOD: 80,
    },
  },
  IMPERIAL_CANNON: {
    name: 'Canon impérial',
    hp: 72,
    attack: 16,
    buildingAttack: 44,
    defense: 5,
    move: 2,
    vision: 5,
    range: 4,
    capture: 1,
    cost: {
      GOLD: 220,
      WOOD: 90,
      STONE: 0,
      IRON: 130,
      FOOD: 45,
    },
  },
  WAR_BALLOON: {
    name: 'Aérostat des augures',
    hp: 55,
    attack: 12,
    defense: 3,
    move: 4,
    vision: 11,
    range: 3,
    capture: 0,
    cost: {
      GOLD: 190,
      WOOD: 150,
      STONE: 0,
      IRON: 45,
      FOOD: 65,
    },
  },
  ASSAULT_SAPPER: {
    name: 'Sapeur des tranchées',
    hp: 72,
    attack: 24,
    buildingAttack: 48,
    defense: 7,
    move: 3,
    vision: 5,
    range: 2,
    capture: 2,
    cost: {
      GOLD: 220,
      WOOD: 45,
      STONE: 0,
      IRON: 130,
      FOOD: 50,
    },
  },
  ASH_FLAMETHROWER: {
    name: 'Lance-flammes des cendres',
    hp: 82,
    attack: 31,
    buildingAttack: 38,
    defense: 8,
    move: 3,
    vision: 4,
    range: 2,
    capture: 2,
    cost: {
      GOLD: 280,
      WOOD: 35,
      STONE: 0,
      IRON: 180,
      FOOD: 55,
    },
  },
  CASEMATE_HUNTER: {
    name: 'Chasseur de chars funéraire',
    hp: 138,
    attack: 25,
    defense: 13,
    move: 4,
    vision: 5,
    range: 4,
    capture: 1,
    cost: {
      GOLD: 480,
      WOOD: 60,
      STONE: 0,
      IRON: 330,
      FOOD: 70,
    },
  },
  DIVE_BOMBER: {
    name: 'Bombardier des corbeaux',
    hp: 100,
    attack: 29,
    buildingAttack: 53,
    defense: 7,
    move: 8,
    vision: 8,
    range: 3,
    capture: 0,
    cost: {
      GOLD: 450,
      WOOD: 70,
      STONE: 0,
      IRON: 280,
      FOOD: 70,
    },
  },
  RAIL_SNIPER: {
    name: 'Tireur électromagnétique',
    hp: 78,
    attack: 45,
    defense: 6,
    move: 3,
    vision: 8,
    range: 6,
    capture: 1,
    cost: {
      GOLD: 430,
      WOOD: 45,
      STONE: 0,
      IRON: 290,
      FOOD: 60,
    },
  },
  STEALTH_BIKE: {
    name: 'Moto spectre',
    hp: 112,
    attack: 37,
    defense: 11,
    move: 9,
    vision: 8,
    range: 4,
    capture: 2,
    cost: {
      GOLD: 550,
      WOOD: 50,
      STONE: 0,
      IRON: 360,
      FOOD: 75,
    },
  },
  MISSILE_TANK: {
    name: 'Blindé lance-missiles',
    hp: 196,
    attack: 47,
    buildingAttack: 76,
    defense: 17,
    move: 4,
    vision: 6,
    range: 6,
    capture: 1,
    cost: {
      GOLD: 760,
      WOOD: 65,
      STONE: 0,
      IRON: 520,
      FOOD: 90,
    },
  },
  NIGHT_INTERCEPTOR: {
    name: 'Intercepteur de minuit',
    hp: 140,
    attack: 39,
    defense: 10,
    move: 12,
    vision: 10,
    range: 5,
    capture: 0,
    cost: {
      GOLD: 800,
      WOOD: 45,
      STONE: 0,
      IRON: 550,
      FOOD: 95,
    },
  },
  REACTOR_DREADNOUGHT: {
    name: 'Cuirassé du réacteur',
    hp: 270,
    attack: 68,
    buildingAttack: 102,
    defense: 24,
    move: 3,
    vision: 6,
    range: 5,
    capture: 1,
    cost: {
      GOLD: 1600,
      WOOD: 100,
      STONE: 0,
      IRON: 1250,
      FOOD: 160,
    },
  },
  GAMMA_INTERCEPTOR: {
    name: 'Intercepteur gamma',
    hp: 175,
    attack: 52,
    defense: 15,
    move: 12,
    vision: 11,
    range: 5,
    capture: 0,
    cost: {
      GOLD: 1500,
      WOOD: 70,
      STONE: 0,
      IRON: 1050,
      FOOD: 130,
    },
  },
  NEUTRON_MORTAR: {
    name: 'Mortier à neutrons',
    hp: 118,
    attack: 36,
    buildingAttack: 118,
    defense: 10,
    move: 2,
    vision: 5,
    range: 7,
    capture: 1,
    cost: {
      GOLD: 1400,
      WOOD: 120,
      STONE: 0,
      IRON: 1100,
      FOOD: 100,
    },
  },
  REACTOR_SERAPH: {
    name: 'Séraphin du réacteur',
    hp: 230,
    attack: 64,
    buildingAttack: 92,
    defense: 17,
    move: 7,
    vision: 8,
    range: 3,
    capture: 0,
    cost: {
      GOLD: 1800,
      WOOD: 100,
      STONE: 0,
      IRON: 950,
      FOOD: 250,
    },
  },
} as const;
export const ERA_REINFORCEMENT_PROFILES = {
  HALBERDIER: {
    recruitAt: ['BARRACKS'],
    requires: [],
    minRecruitLevel: 1,
    antiCavalry: 14,
    role: 'Infanterie de protection : +14 attaque contre la cavalerie. Lent, sans tir à distance.',
  },
  LONGBOWMAN: {
    recruitAt: ['ARCHERY'],
    requires: [],
    minRecruitLevel: 1,
    role: 'Arc long : portée 4, tirs en cloche au-dessus des remparts. Fragile au contact.',
  },
  MOUNTED_OUTRIDER: {
    recruitAt: ['STABLE'],
    requires: [],
    minRecruitLevel: 1,
    mounted: true,
    role: 'Reconnaissance montée : vision 9 et déplacement 8. Rapide mais peu adapté aux combats prolongés.',
  },
  WAR_WAGON: {
    recruitAt: ['WORKSHOP'],
    requires: ['ARCHERY'],
    minRecruitLevel: 1,
    mechanical: true,
    armored: true,
    population: 8,
    role: 'Chariot protégé par des pavois, armé d’une arbalète. Résistant et lent ; tir direct bloqué par les murs.',
  },
  IMPERIAL_PIKEMAN: {
    recruitAt: ['BARRACKS'],
    requires: ['FORGE'],
    minRecruitLevel: 2,
    antiCavalry: 24,
    role: 'Formation de longues piques : +24 attaque contre la cavalerie. Protège les mousquetaires, vulnérable aux tirs.',
  },
  BLACK_DRAGOON: {
    recruitAt: ['STABLE'],
    requires: ['FORGE'],
    minRecruitLevel: 2,
    mounted: true,
    role: 'Cavalier au mousquet : mobilité et tir direct à 3 cases. Moins résistant qu’un cuirassier.',
  },
  IMPERIAL_CANNON: {
    recruitAt: ['WORKSHOP'],
    requires: ['FORGE'],
    minRecruitLevel: 2,
    mechanical: true,
    siege: true,
    population: 8,
    role: 'Canon à poudre en tir tendu : 44 attaque contre les bâtiments, portée 4. Tir : 2 PA ; le premier mur intercepte le boulet.',
  },
  WAR_BALLOON: {
    recruitAt: ['WORKSHOP'],
    requires: ['LIBRARY', 'FORGE'],
    minRecruitLevel: 2,
    flying: true,
    mechanical: true,
    siege: true,
    population: 8,
    role: 'Ballon d’observation et bombardement léger. Vision 11, vol lent, sans capture ; bombardement : 2 PA.',
  },
  ASSAULT_SAPPER: {
    recruitAt: ['ARSENAL'],
    requires: ['MUNITIONS'],
    minRecruitLevel: 3,
    siege: true,
    population: 6,
    role: 'Charges explosives lancées en cloche : 48 attaque contre les bâtiments à 2 cases. Attaque : 2 PA.',
  },
  ASH_FLAMETHROWER: {
    recruitAt: ['ARSENAL'],
    requires: ['REFINERY'],
    minRecruitLevel: 3,
    population: 7,
    role: 'Assaut à courte portée, jet de flammes occultes direct. Les murs interceptent le feu.',
  },
  CASEMATE_HUNTER: {
    recruitAt: ['TANK_FACTORY'],
    requires: ['MUNITIONS', 'REFINERY'],
    minRecruitLevel: 3,
    mechanical: true,
    armored: true,
    antiArmor: 34,
    population: 12,
    role: 'Canon antichar : +34 attaque contre les blindés, ignore 75 % de leur défense. Tir direct ; moins efficace contre l’infanterie.',
  },
  DIVE_BOMBER: {
    recruitAt: ['AERODROME'],
    requires: ['MUNITIONS', 'REFINERY'],
    minRecruitLevel: 3,
    flying: true,
    mechanical: true,
    siege: true,
    population: 12,
    role: 'Bombardier en piqué : 53 attaque contre les bâtiments. Survole les remparts, sans capture ; attaque : 2 PA.',
  },
  RAIL_SNIPER: {
    recruitAt: ['ARSENAL'],
    requires: ['RADIO', 'OCCULT_LAB'],
    minRecruitLevel: 4,
    population: 7,
    role: 'Fusil électromagnétique de précision, portée 6. Fragile face à une percée ; rayon direct intercepté par les remparts.',
  },
  STEALTH_BIKE: {
    recruitAt: ['GARAGE'],
    requires: ['RADIO', 'REFINERY'],
    minRecruitLevel: 4,
    mechanical: true,
    population: 10,
    role: 'Moto d’assaut à silhouette basse : déplacement 9, rafales à 4 cases. Aucun pouvoir d’invisibilité ; vulnérable aux blindés.',
  },
  MISSILE_TANK: {
    recruitAt: ['TANK_FACTORY'],
    requires: ['RADIO', 'MUNITIONS'],
    minRecruitLevel: 4,
    mechanical: true,
    armored: true,
    siege: true,
    population: 16,
    role: 'Missiles en trajectoire plongeante : portée 6, 76 attaque contre les bâtiments. Passe les remparts ; attaque : 2 PA.',
  },
  NIGHT_INTERCEPTOR: {
    recruitAt: ['AERODROME'],
    requires: ['RADIO', 'REFINERY', 'MUNITIONS'],
    minRecruitLevel: 4,
    flying: true,
    mechanical: true,
    antiAir: 30,
    population: 14,
    role: 'Chasseur à réaction : +30 attaque contre les aéronefs, déplacement 12. Sans capture, sensible aux batteries antiaériennes.',
  },
  REACTOR_DREADNOUGHT: {
    recruitAt: ['ATOMIC_FOUNDRY'],
    requires: ['NUCLEAR_REACTOR'],
    minRecruitLevel: 5,
    mechanical: true,
    armored: true,
    radioactive: true,
    siege: true,
    population: 20,
    role: 'Char superlourd atomique : 102 attaque contre les bâtiments, tir neutronique direct. Très lent, coûteux, vulnérable aux armes antichars. Attaque : 2 PA.',
  },
  GAMMA_INTERCEPTOR: {
    recruitAt: ['AERODROME'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    minRecruitLevel: 5,
    flying: true,
    mechanical: true,
    radioactive: true,
    antiAir: 46,
    population: 16,
    role: 'Supériorité aérienne atomique : +46 attaque contre les aéronefs. Sans capture ; coût et entretien élevés.',
  },
  NEUTRON_MORTAR: {
    recruitAt: ['GUN_BATTERY'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    minRecruitLevel: 5,
    mechanical: true,
    radioactive: true,
    siege: true,
    population: 14,
    role: 'Siège atomique : 118 attaque contre les bâtiments à 7 cases, tir en cloche. Fragile et très lent ; attaque : 2 PA.',
  },
  REACTOR_SERAPH: {
    recruitAt: ['DRAGON_ROOST'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    minRecruitLevel: 5,
    flying: true,
    radioactive: true,
    siege: true,
    population: 20,
    role: 'Dragon occulte irradié : souffle de siège, vol au-dessus des remparts. Sans capture ; coûte 2 PA par attaque et reste vulnérable à l’antiaérien.',
  },
} satisfies Record<keyof typeof ERA_REINFORCEMENTS, UnitProfile>;
export const ERA_REINFORCEMENT_TIERS = {
  HALBERDIER: 1,
  LONGBOWMAN: 1,
  MOUNTED_OUTRIDER: 1,
  WAR_WAGON: 1,
  IMPERIAL_PIKEMAN: 2,
  BLACK_DRAGOON: 2,
  IMPERIAL_CANNON: 2,
  WAR_BALLOON: 2,
  ASSAULT_SAPPER: 3,
  ASH_FLAMETHROWER: 3,
  CASEMATE_HUNTER: 3,
  DIVE_BOMBER: 3,
  RAIL_SNIPER: 4,
  STEALTH_BIKE: 4,
  MISSILE_TANK: 4,
  NIGHT_INTERCEPTOR: 4,
  REACTOR_DREADNOUGHT: 6,
  GAMMA_INTERCEPTOR: 6,
  NEUTRON_MORTAR: 6,
  REACTOR_SERAPH: 6,
} as const;
export const ERA_REINFORCEMENT_CATEGORIES = {
  HALBERDIER: 'Infanterie médiévale',
  LONGBOWMAN: 'Armes à distance',
  MOUNTED_OUTRIDER: 'Cavalerie',
  WAR_WAGON: 'Véhicules',
  IMPERIAL_PIKEMAN: 'Infanterie médiévale',
  BLACK_DRAGOON: 'Cavalerie',
  IMPERIAL_CANNON: 'Artillerie',
  WAR_BALLOON: 'Aviation',
  ASSAULT_SAPPER: 'Armes à feu',
  ASH_FLAMETHROWER: 'Armes à feu',
  CASEMATE_HUNTER: 'Véhicules',
  DIVE_BOMBER: 'Aviation',
  RAIL_SNIPER: 'Armes à distance',
  STEALTH_BIKE: 'Motos',
  MISSILE_TANK: 'Véhicules',
  NIGHT_INTERCEPTOR: 'Aviation',
  REACTOR_DREADNOUGHT: 'Véhicules',
  GAMMA_INTERCEPTOR: 'Aviation',
  NEUTRON_MORTAR: 'Artillerie',
  REACTOR_SERAPH: 'Occulte',
} satisfies Record<keyof typeof ERA_REINFORCEMENTS, UnitTab>;
export const ERA_REINFORCEMENT_AGES = {
  HALBERDIER: 1,
  LONGBOWMAN: 1,
  MOUNTED_OUTRIDER: 1,
  WAR_WAGON: 1,
  IMPERIAL_PIKEMAN: 2,
  BLACK_DRAGOON: 2,
  IMPERIAL_CANNON: 2,
  WAR_BALLOON: 2,
  ASSAULT_SAPPER: 3,
  ASH_FLAMETHROWER: 3,
  CASEMATE_HUNTER: 3,
  DIVE_BOMBER: 3,
  RAIL_SNIPER: 4,
  STEALTH_BIKE: 4,
  MISSILE_TANK: 4,
  NIGHT_INTERCEPTOR: 4,
  REACTOR_DREADNOUGHT: 5,
  GAMMA_INTERCEPTOR: 5,
  NEUTRON_MORTAR: 5,
  REACTOR_SERAPH: 5,
} as const;
