export const GAME_NAME = 'VOIDMARCH';
export const RULES = {
  maxAP: 15,
  startingAP: 30,
  constructionRadius: 3,
  guestLifetime: 24 * 60 * 60 * 1000,
  apInterval: 60_000,
  grace: 180_000,
  protection: 600_000,
  defeatCooldown: 600_000,
  botInterval: 600_000,
  chunkSize: 32,
  realmSpacing: 70,
  settlementScale: 5,
  minTruce: 60_000,
  maxTruce: 7 * 86_400_000,
  tradeDuration: 3_600_000,
};
export const ACTION_COST = {
  MOVE: 1,
  GATHER: 1,
  ATTACK: 1,
  CAPTURE: 1,
  BUILD: 1,
  ROAD: 1,
  RECRUIT: 1,
  REPAIR: 1,
  DEMOLISH: 1,
  UPGRADE: 2,
  INTERACT: 1,
  ABILITY: 2,
  PROPOSE: 0,
  RESPOND: 0,
  RESPAWN: 0,
} as const;
export const RESOURCES = ['GOLD', 'WOOD', 'STONE', 'IRON', 'FOOD'] as const;
export type Resource = (typeof RESOURCES)[number];
export type Wallet = Record<Resource, number>;
export const RESOURCE_NAMES: Record<Resource, string> = {
  STONE: 'Pierre',
  GOLD: 'Or',
  WOOD: 'Bois',
  IRON: 'Fer',
  FOOD: 'Vivres',
};
export const FACTIONS = {
  ASH: {
    name: 'Ordre de la Cendre',
    short: 'La Cendre',
    color: '#bc9860',
    symbol: 'crown',
    description: 'Sous la cendre, le royaume demeure.',
    bonus: 'Bâtiments 10 % moins coûteux.',
  },
  MASK: {
    name: 'Confrérie du Masque',
    short: 'Le Masque',
    color: '#799484',
    symbol: 'eye',
    description: 'Voir ce que les autres redoutent.',
    bonus: 'Éclaireurs : +2 de vision.',
  },
  IRON: {
    name: 'Cavaliers du Fer Mort',
    short: 'Le Fer Mort',
    color: '#999cb8',
    symbol: 'sword',
    description: 'Le fer se souvient des étoiles.',
    bonus: 'Unités montées : +1 déplacement.',
  },
} as const;
export type Faction = keyof typeof FACTIONS;
export const TERRAINS = {
  PLAIN: { name: 'Plaine', color: 0x465140, cost: 1, defense: 0, yield: 'FOOD' },
  FOREST: { name: 'Forêt ancienne', color: 0x293e34, cost: 2, defense: 1, yield: 'WOOD' },
  HILL: {
    name: 'Collines rocheuses et ferrifères',
    color: 0x666457,
    cost: 2,
    defense: 1,
    yield: 'IRON',
  },
  MOUNTAIN: { name: 'Montagne rocheuse', color: 0x777b74, cost: 3, defense: 3, yield: 'STONE' },
  RIVER: { name: 'Rivière', color: 0x354c50, cost: 3, defense: 0, yield: 'FOOD' },
  MARSH: { name: 'Marais', color: 0x3e4b3c, cost: 3, defense: 1, yield: 'FOOD' },
  RUINS: { name: 'Ruines oubliées', color: 0x655e51, cost: 2, defense: 2, yield: 'GOLD' },
  CORRUPTION: { name: 'Sol corrompu', color: 0x45414b, cost: 2, defense: 0, yield: 'GOLD' },
  ALIEN: { name: 'Structure antique', color: 0x30494a, cost: 2, defense: 2, yield: 'GOLD' },
} as const;
export type Terrain = keyof typeof TERRAINS;
export const UNITS = {
  TESLA_TROOPER: {
    name: 'Voltigeur Tesla',
    hp: 14,
    attack: 8,
    defense: 2,
    move: 2,
    vision: 5,
    range: 3,
    capture: 1,
    cost: { STONE: 0, GOLD: 120, WOOD: 20, IRON: 80, FOOD: 25 },
  },
  HEX_HUNTER: {
    name: 'Chasseur de maléfices',
    hp: 11,
    attack: 7,
    defense: 2,
    move: 4,
    vision: 7,
    range: 3,
    capture: 1,
    cost: { STONE: 0, GOLD: 100, WOOD: 35, IRON: 40, FOOD: 25 },
  },
  PLAGUE_MEDIC: {
    name: 'Médecin de la peste',
    hp: 9,
    attack: 1,
    defense: 2,
    move: 3,
    vision: 5,
    range: 1,
    capture: 0,
    cost: { STONE: 0, GOLD: 85, WOOD: 20, IRON: 20, FOOD: 35 },
  },
  GHOUL_INFANTRY: {
    name: 'Grenadier revenant',
    hp: 16,
    attack: 6,
    defense: 3,
    move: 2,
    vision: 4,
    range: 2,
    capture: 1,
    cost: { STONE: 0, GOLD: 95, WOOD: 15, IRON: 60, FOOD: 20 },
  },
  SPECTRAL_RIDER: {
    name: 'Cavalier spectral',
    hp: 15,
    attack: 8,
    defense: 3,
    move: 5,
    vision: 6,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 160, WOOD: 25, IRON: 70, FOOD: 40 },
  },
  SIEGE_WALKER: {
    name: 'Marcheur de siège',
    hp: 24,
    attack: 9,
    defense: 5,
    move: 2,
    vision: 5,
    range: 4,
    capture: 0,
    buildingAttack: 16,
    cost: { STONE: 0, GOLD: 220, WOOD: 60, IRON: 180, FOOD: 30 },
  },
  HEX_TANK: {
    name: 'Char possédé',
    hp: 34,
    attack: 12,
    defense: 7,
    move: 2,
    vision: 5,
    range: 3,
    capture: 1,
    cost: { STONE: 0, GOLD: 300, WOOD: 65, IRON: 250, FOOD: 45 },
  },
  MORTAR: {
    name: 'Section de mortier',
    hp: 9,
    attack: 6,
    defense: 1,
    move: 2,
    vision: 5,
    range: 5,
    capture: 0,
    buildingAttack: 10,
    cost: { STONE: 0, GOLD: 110, WOOD: 40, IRON: 75, FOOD: 20 },
  },

  RIFLEMAN: {
    name: 'Fusilier',
    hp: 10,
    attack: 5,
    defense: 2,
    move: 3,
    vision: 5,
    range: 4,
    capture: 1,
    cost: { STONE: 0, GOLD: 45, WOOD: 15, IRON: 30, FOOD: 15 },
  },
  STORMTROOPER: {
    name: 'Soldat d’assaut',
    hp: 13,
    attack: 7,
    defense: 3,
    move: 3,
    vision: 4,
    range: 2,
    capture: 1,
    cost: { STONE: 0, GOLD: 70, WOOD: 10, IRON: 45, FOOD: 20 },
  },
  MACHINE_GUNNER: {
    name: 'Mitrailleur',
    hp: 12,
    attack: 8,
    defense: 2,
    move: 2,
    vision: 5,
    range: 4,
    capture: 0,
    cost: { STONE: 0, GOLD: 85, WOOD: 20, IRON: 55, FOOD: 20 },
  },
  SNIPER: {
    name: 'Tireur des brumes',
    hp: 7,
    attack: 8,
    defense: 1,
    move: 3,
    vision: 8,
    range: 6,
    capture: 0,
    cost: { STONE: 0, GOLD: 95, WOOD: 25, IRON: 50, FOOD: 15 },
  },
  BAZOOKA: {
    name: 'Chasseur de blindés',
    hp: 9,
    attack: 5,
    defense: 1,
    move: 2,
    vision: 5,
    range: 4,
    capture: 0,
    cost: { STONE: 0, GOLD: 100, WOOD: 20, IRON: 65, FOOD: 20 },
    buildingAttack: 10,
  },
  OFFICER: {
    name: 'Officier au sabre',
    hp: 12,
    attack: 5,
    defense: 3,
    move: 4,
    vision: 5,
    range: 2,
    capture: 1,
    cost: { STONE: 0, GOLD: 65, WOOD: 15, IRON: 30, FOOD: 25 },
  },
  MOTORCYCLE: {
    name: 'Moto de reconnaissance',
    hp: 11,
    attack: 4,
    defense: 1,
    move: 8,
    vision: 8,
    range: 2,
    capture: 1,
    cost: { STONE: 0, GOLD: 85, WOOD: 20, IRON: 65, FOOD: 15 },
  },
  ARMORED_CAR: {
    name: 'Automitrailleuse',
    hp: 19,
    attack: 7,
    defense: 4,
    move: 6,
    vision: 6,
    range: 3,
    capture: 1,
    cost: { STONE: 0, GOLD: 130, WOOD: 25, IRON: 100, FOOD: 20 },
  },
  TANK: {
    name: 'Char de rupture',
    hp: 32,
    attack: 10,
    defense: 6,
    move: 3,
    vision: 5,
    range: 4,
    capture: 1,
    cost: { STONE: 0, GOLD: 190, WOOD: 35, IRON: 170, FOOD: 25 },
    buildingAttack: 13,
  },
  FIELD_GUN: {
    name: 'Canon de campagne',
    hp: 13,
    attack: 8,
    defense: 1,
    move: 2,
    vision: 6,
    range: 6,
    capture: 0,
    cost: { STONE: 0, GOLD: 125, WOOD: 50, IRON: 100, FOOD: 15 },
    buildingAttack: 17,
  },
  ROCKET_LAUNCHER: {
    name: 'Batterie de fusées',
    hp: 16,
    attack: 11,
    defense: 2,
    move: 2,
    vision: 7,
    range: 7,
    capture: 0,
    cost: { STONE: 0, GOLD: 220, WOOD: 40, IRON: 180, FOOD: 20 },
    buildingAttack: 22,
  },
  IRON_REVENANT: {
    name: 'Chevalier mécanique',
    hp: 23,
    attack: 9,
    defense: 5,
    move: 3,
    vision: 4,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 170, WOOD: 30, IRON: 140, FOOD: 20 },
  },

  PEASANT: {
    name: 'Paysan',
    hp: 5,
    attack: 0,
    defense: 0,
    move: 3,
    vision: 3,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 5, WOOD: 10, IRON: 0, FOOD: 10 },
  },
  MILITIA: {
    name: 'Milicien',
    hp: 7,
    attack: 2,
    defense: 1,
    move: 3,
    vision: 3,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 12, WOOD: 10, IRON: 0, FOOD: 8 },
  },
  SPEARMAN: {
    name: 'Lancier',
    hp: 11,
    attack: 3,
    defense: 3,
    move: 3,
    vision: 3,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 30, WOOD: 20, IRON: 12, FOOD: 12 },
  },
  CROSSBOW: {
    name: 'Arbalétrier',
    hp: 8,
    attack: 5,
    defense: 2,
    move: 2,
    vision: 4,
    range: 3,
    capture: 0,
    cost: { STONE: 0, GOLD: 45, WOOD: 25, IRON: 20, FOOD: 15 },
  },
  RANGER: {
    name: 'Rôdeur',
    hp: 8,
    attack: 4,
    defense: 2,
    move: 4,
    vision: 7,
    range: 3,
    capture: 0,
    cost: { STONE: 0, GOLD: 55, WOOD: 35, IRON: 10, FOOD: 20 },
  },
  LIGHT_CAVALRY: {
    name: 'Cavalier léger',
    hp: 9,
    attack: 3,
    defense: 1,
    move: 6,
    vision: 5,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 50, WOOD: 10, IRON: 15, FOOD: 30 },
  },
  PALADIN: {
    name: 'Paladin',
    hp: 18,
    attack: 5,
    defense: 5,
    move: 2,
    vision: 4,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 110, WOOD: 10, IRON: 60, FOOD: 35 },
  },
  RAM: {
    name: 'Bélier',
    hp: 20,
    attack: 1,
    defense: 4,
    move: 2,
    vision: 3,
    range: 1,
    capture: 0,
    cost: { STONE: 0, GOLD: 75, WOOD: 90, IRON: 35, FOOD: 15 },
    buildingAttack: 12,
  },
  HEALER: {
    name: 'Guérisseuse',
    hp: 7,
    attack: 0,
    defense: 1,
    move: 3,
    vision: 4,
    range: 1,
    capture: 0,
    cost: { STONE: 0, GOLD: 45, WOOD: 10, IRON: 5, FOOD: 25 },
  },
  ENGINEER: {
    name: 'Ingénieur',
    hp: 9,
    attack: 1,
    defense: 2,
    move: 3,
    vision: 4,
    range: 1,
    capture: 0,
    cost: { STONE: 0, GOLD: 45, WOOD: 30, IRON: 20, FOOD: 15 },
  },
  BERSERKER: {
    name: 'Berserker',
    hp: 13,
    attack: 7,
    defense: 0,
    move: 3,
    vision: 3,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 65, WOOD: 10, IRON: 30, FOOD: 30 },
  },
  VOID_ACOLYTE: {
    name: 'Acolyte du Vide',
    hp: 7,
    attack: 6,
    defense: 0,
    move: 2,
    vision: 6,
    range: 3,
    capture: 0,
    cost: { STONE: 0, GOLD: 100, WOOD: 20, IRON: 30, FOOD: 25 },
  },
  SCOUT: {
    name: 'Éclaireur',
    hp: 5,
    attack: 1,
    defense: 0,
    move: 5,
    vision: 6,
    range: 1,
    capture: 0,
    cost: { STONE: 0, GOLD: 20, WOOD: 12, IRON: 0, FOOD: 8 },
  },
  INFANTRY: {
    name: 'Fantassin',
    hp: 10,
    attack: 3,
    defense: 2,
    move: 3,
    vision: 3,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 30, WOOD: 8, IRON: 12, FOOD: 10 },
  },
  GUARD: {
    name: 'Garde',
    hp: 15,
    attack: 2,
    defense: 5,
    move: 2,
    vision: 3,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 45, WOOD: 0, IRON: 25, FOOD: 15 },
  },
  ARCHER: {
    name: 'Archer',
    hp: 7,
    attack: 4,
    defense: 1,
    move: 2,
    vision: 4,
    range: 3,
    capture: 0,
    cost: { STONE: 0, GOLD: 35, WOOD: 25, IRON: 5, FOOD: 10 },
  },
  KNIGHT: {
    name: 'Chevalier',
    hp: 10,
    attack: 5,
    defense: 2,
    move: 5,
    vision: 4,
    range: 1,
    capture: 1,
    cost: { STONE: 0, GOLD: 70, WOOD: 10, IRON: 30, FOOD: 25 },
  },
  SIEGE: {
    name: 'Engin de siège',
    hp: 8,
    attack: 3,
    buildingAttack: 8,
    defense: 1,
    move: 1,
    vision: 4,
    range: 4,
    capture: 0,
    cost: { STONE: 0, GOLD: 90, WOOD: 65, IRON: 40, FOOD: 10 },
  },
} as const;
export type UnitKind = keyof typeof UNITS;
export const BUILDINGS = {
  WOOD_WALL: {
    name: 'Palissade en bois',
    hp: 30,
    capture: 0,
    cost: { STONE: 0, GOLD: 0, WOOD: 30, IRON: 0, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS', 'MOUNTAIN'],
  },
  STONE_WALL: {
    name: 'Rempart de pierre',
    hp: 65,
    capture: 0,
    cost: { STONE: 45, GOLD: 0, WOOD: 0, IRON: 0, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS', 'MOUNTAIN'],
  },
  STEEL_WALL: {
    name: 'Mur en acier',
    hp: 100,
    capture: 0,
    cost: { STONE: 0, GOLD: 0, WOOD: 0, IRON: 45, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS', 'MOUNTAIN'],
  },
  TESLA_COIL: {
    name: 'Tour Tesla',
    hp: 95,
    capture: 5,
    cost: { STONE: 70, GOLD: 90, WOOD: 45, IRON: 90, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  CRYPT_BARRACKS: {
    name: 'Caserne des revenants',
    hp: 75,
    capture: 4,
    cost: { STONE: 65, GOLD: 100, WOOD: 60, IRON: 50, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  ALCHEMY_FOUNDRY: {
    name: 'Fonderie alchimique',
    hp: 65,
    capture: 4,
    cost: { STONE: 50, GOLD: 130, WOOD: 70, IRON: 80, FOOD: 0 },
    production: { GOLD: 5 },
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  BLACK_OBSERVATORY: {
    name: 'Observatoire noir',
    hp: 55,
    capture: 3,
    cost: { STONE: 60, GOLD: 140, WOOD: 80, IRON: 65, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },

  QUARRY: {
    name: 'Carrière de pierre',
    hp: 30,
    capture: 3,
    cost: { GOLD: 25, WOOD: 30, STONE: 0, IRON: 5, FOOD: 0 },
    production: { STONE: 4 },
    terrains: ['HILL', 'MOUNTAIN'],
  },
  ARSENAL: {
    name: 'Arsenal',
    hp: 50,
    capture: 3,
    cost: { STONE: 35, GOLD: 70, WOOD: 65, IRON: 35, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  BUNKER: {
    name: 'Bunker',
    hp: 100,
    capture: 4,
    cost: { STONE: 80, GOLD: 70, WOOD: 35, IRON: 100, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  GARAGE: {
    name: 'Garage militaire',
    hp: 50,
    capture: 3,
    cost: { STONE: 0, GOLD: 80, WOOD: 65, IRON: 55, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  TANK_FACTORY: {
    name: 'Usine de blindés',
    hp: 75,
    capture: 4,
    cost: { STONE: 65, GOLD: 160, WOOD: 100, IRON: 130, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  REFINERY: {
    name: 'Raffinerie',
    hp: 45,
    capture: 3,
    cost: { STONE: 35, GOLD: 100, WOOD: 70, IRON: 70, FOOD: 0 },
    production: { GOLD: 4 },
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  MUNITIONS: {
    name: 'Manufacture de munitions',
    hp: 45,
    capture: 3,
    cost: { STONE: 25, GOLD: 85, WOOD: 65, IRON: 60, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  RADIO: {
    name: 'Relais radio',
    hp: 35,
    capture: 3,
    cost: { STONE: 15, GOLD: 75, WOOD: 40, IRON: 65, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  FIELD_HOSPITAL: {
    name: 'Hôpital militaire',
    hp: 50,
    capture: 3,
    cost: { STONE: 20, GOLD: 65, WOOD: 65, IRON: 25, FOOD: 30 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  GUN_BATTERY: {
    name: 'Batterie fortifiée',
    hp: 85,
    capture: 4,
    cost: { STONE: 50, GOLD: 110, WOOD: 60, IRON: 100, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  OCCULT_LAB: {
    name: 'Laboratoire des cendres',
    hp: 60,
    capture: 3,
    cost: { STONE: 60, GOLD: 150, WOOD: 80, IRON: 100, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  ROCKET_SILO: {
    name: 'Rampe de lancement',
    hp: 65,
    capture: 3,
    cost: { STONE: 60, GOLD: 170, WOOD: 80, IRON: 140, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  RAIL_DEPOT: {
    name: 'Dépôt ferroviaire',
    hp: 55,
    capture: 3,
    cost: { STONE: 30, GOLD: 90, WOOD: 90, IRON: 75, FOOD: 0 },
    production: { GOLD: 3 },
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },

  CAMP: {
    name: 'Campement',
    hp: 30,
    capture: 2,
    cost: { STONE: 0, GOLD: 0, WOOD: 25, IRON: 0, FOOD: 0 },
    production: { GOLD: 1, FOOD: 3 },
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS'],
  },
  HOUSE: {
    name: 'Chaumière',
    hp: 20,
    capture: 2,
    cost: { STONE: 0, GOLD: 0, WOOD: 20, IRON: 0, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS'],
  },
  GRANARY: {
    name: 'Grenier',
    hp: 25,
    capture: 2,
    cost: { STONE: 0, GOLD: 15, WOOD: 40, IRON: 0, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS'],
  },
  HUNTER: {
    name: 'Cabane de chasse',
    hp: 20,
    capture: 2,
    cost: { STONE: 0, GOLD: 0, WOOD: 20, IRON: 0, FOOD: 0 },
    production: { FOOD: 4 },
    terrains: ['FOREST'],
  },
  FISHERY: {
    name: 'Pêcherie',
    hp: 20,
    capture: 2,
    cost: { STONE: 0, GOLD: 10, WOOD: 30, IRON: 0, FOOD: 0 },
    production: { FOOD: 8 },
    terrains: ['RIVER', 'MARSH'],
  },
  STABLE: {
    name: 'Écurie',
    hp: 35,
    capture: 2,
    cost: { STONE: 0, GOLD: 55, WOOD: 60, IRON: 15, FOOD: 25 },
    production: {},
    terrains: ['PLAIN', 'HILL'],
  },
  ARCHERY: {
    name: 'Archerie',
    hp: 30,
    capture: 2,
    cost: { STONE: 0, GOLD: 40, WOOD: 55, IRON: 10, FOOD: 10 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS'],
  },
  MONASTERY: {
    name: 'Monastère',
    hp: 45,
    capture: 3,
    cost: { STONE: 40, GOLD: 80, WOOD: 60, IRON: 30, FOOD: 20 },
    production: { FOOD: 2, GOLD: 2 },
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  FORGE: {
    name: 'Forge',
    hp: 40,
    capture: 3,
    cost: { STONE: 20, GOLD: 65, WOOD: 45, IRON: 35, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  LIBRARY: {
    name: 'Bibliothèque des astres',
    hp: 35,
    capture: 3,
    cost: { STONE: 30, GOLD: 100, WOOD: 70, IRON: 30, FOOD: 20 },
    production: { GOLD: 3 },
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  BAKERY: {
    name: 'Boulangerie',
    hp: 25,
    capture: 2,
    cost: { STONE: 10, GOLD: 25, WOOD: 35, IRON: 5, FOOD: 10 },
    production: { FOOD: 7 },
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS'],
  },
  WELL: {
    name: 'Puits',
    hp: 30,
    capture: 2,
    cost: { STONE: 10, GOLD: 5, WOOD: 20, IRON: 0, FOOD: 0 },
    production: { FOOD: 2 },
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS'],
  },
  OUTPOST: {
    name: 'Avant-poste',
    hp: 35,
    capture: 2,
    cost: { STONE: 0, GOLD: 35, WOOD: 35, IRON: 5, FOOD: 0 },
    production: { GOLD: 1, FOOD: 3 },
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS'],
  },
  VILLAGE: {
    name: 'Village',
    hp: 35,
    capture: 2,
    cost: { STONE: 20, GOLD: 60, WOOD: 50, IRON: 10, FOOD: 25 },
    production: { GOLD: 3, FOOD: 4 },
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS'],
  },
  FARM: {
    name: 'Ferme',
    hp: 15,
    capture: 2,
    cost: { STONE: 0, GOLD: 20, WOOD: 25, IRON: 0, FOOD: 0 },
    production: { FOOD: 6 },
    terrains: ['PLAIN'],
  },
  LUMBER: {
    name: 'Scierie',
    hp: 20,
    capture: 2,
    cost: { STONE: 0, GOLD: 25, WOOD: 20, IRON: 5, FOOD: 0 },
    production: { WOOD: 5 },
    terrains: ['FOREST'],
  },
  MINE: {
    name: 'Mine',
    hp: 25,
    capture: 3,
    cost: { STONE: 0, GOLD: 35, WOOD: 35, IRON: 5, FOOD: 0 },
    production: { IRON: 4 },
    terrains: ['HILL'],
  },
  MARKET: {
    name: 'Marché',
    hp: 25,
    capture: 2,
    cost: { STONE: 0, GOLD: 50, WOOD: 35, IRON: 10, FOOD: 10 },
    production: { GOLD: 5 },
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  WAREHOUSE: {
    name: 'Entrepôt',
    hp: 30,
    capture: 2,
    cost: { STONE: 15, GOLD: 35, WOOD: 45, IRON: 10, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS'],
  },
  WORKSHOP: {
    name: 'Atelier',
    hp: 30,
    capture: 3,
    cost: { STONE: 15, GOLD: 65, WOOD: 45, IRON: 25, FOOD: 0 },
    production: { GOLD: 2 },
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  BARRACKS: {
    name: 'Caserne',
    hp: 40,
    capture: 3,
    cost: { STONE: 20, GOLD: 60, WOOD: 45, IRON: 25, FOOD: 10 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  FORT: {
    name: 'Fort',
    hp: 65,
    capture: 4,
    cost: { STONE: 65, GOLD: 90, WOOD: 45, IRON: 65, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'RUINS'],
  },
  TOWER: {
    name: 'Tour de guet',
    hp: 40,
    capture: 3,
    cost: { STONE: 25, GOLD: 45, WOOD: 25, IRON: 30, FOOD: 0 },
    production: {},
    terrains: ['PLAIN', 'HILL', 'FOREST', 'RUINS'],
  },
} satisfies Record<
  string,
  {
    name: string;
    hp: number;
    capture: number;
    cost: Wallet;
    production: Partial<Wallet>;
    terrains: string[];
  }
>;
export type BuildingKind = keyof typeof BUILDINGS;
export const WALL_KINDS = ['WOOD_WALL', 'STONE_WALL', 'STEEL_WALL'] as const;
export type WallKind = (typeof WALL_KINDS)[number];
export const isWall = (kind: string): kind is WallKind => WALL_KINDS.includes(kind as WallKind);
export const isBuildable = (kind: BuildingKind) => kind !== 'STONE_WALL' && kind !== 'STEEL_WALL';
export function buildingConstructionCost(kind: BuildingKind, faction: Faction): Partial<Wallet> {
  const discount = faction === 'ASH' ? 0.9 : 1;
  return Object.fromEntries(
    Object.entries(BUILDINGS[kind].cost).map(([resource, value]) => [
      resource,
      Math.ceil(value * discount),
    ]),
  );
}
export const EXTRACTOR_BUILDINGS: readonly BuildingKind[] = [
  'LUMBER',
  'MINE',
  'QUARRY',
  'FARM',
  'FISHERY',
  'HUNTER',
];
export function productionOnTerrain(kind: BuildingKind, terrain: Terrain): Partial<Wallet> {
  return EXTRACTOR_BUILDINGS.includes(kind) && !BUILDINGS[kind].terrains.includes(terrain)
    ? {}
    : BUILDINGS[kind].production;
}

export interface UnitProfile {
  role: string;
  recruitAt: BuildingKind[];
  requires: BuildingKind[];
  mounted?: boolean;
  mechanical?: boolean;
  armored?: boolean;
  siege?: boolean;
  builder?: boolean;
  healer?: boolean;
}
export const UNIT_PROFILES: Record<UnitKind, UnitProfile> = {
  TESLA_TROOPER: {
    role: 'Fusil électrique à moyenne portée ; puissance élevée, déplacement lent.',
    recruitAt: ['TESLA_COIL'],
    requires: ['OCCULT_LAB'],
  },
  HEX_HUNTER: {
    role: 'Éclaireur armé de pistolet et d’arbalète ; vision étendue.',
    recruitAt: ['BLACK_OBSERVATORY'],
    requires: ['ARSENAL'],
  },
  PLAGUE_MEDIC: {
    role: 'Soigne les alliés voisins ; le soin de groupe coûte 1 PA.',
    recruitAt: ['FIELD_HOSPITAL'],
    requires: ['MONASTERY'],
    healer: true,
  },
  GHOUL_INFANTRY: {
    role: 'Infanterie revenante résistante capable de revendiquer les terres.',
    recruitAt: ['CRYPT_BARRACKS'],
    requires: ['ARSENAL'],
  },
  SPECTRAL_RIDER: {
    role: 'Cavalerie occulte rapide, armée d’une épée et d’un pistolet.',
    recruitAt: ['CRYPT_BARRACKS'],
    requires: ['STABLE'],
    mounted: true,
  },
  SIEGE_WALKER: {
    role: 'Marcheur blindé contre les fortifications. Attaque : 2 PA.',
    recruitAt: ['TANK_FACTORY'],
    requires: ['ALCHEMY_FOUNDRY'],
    mechanical: true,
    armored: true,
    siege: true,
  },
  HEX_TANK: {
    role: 'Blindé lourd possédé ; coûteux à produire et entretenir.',
    recruitAt: ['TANK_FACTORY'],
    requires: ['ALCHEMY_FOUNDRY', 'OCCULT_LAB'],
    mechanical: true,
    armored: true,
  },
  MORTAR: {
    role: 'Artillerie mobile à longue portée et fragile au contact. Attaque : 2 PA.',
    recruitAt: ['GUN_BATTERY'],
    requires: ['MUNITIONS'],
    siege: true,
  },

  RIFLEMAN: {
    role: 'Tir à 4 cases ; infanterie de conquête.',
    recruitAt: ['ARSENAL'],
    requires: ['ARSENAL'],
  },
  STORMTROOPER: {
    role: 'Infanterie d’assaut à courte portée.',
    recruitAt: ['ARSENAL'],
    requires: ['ARSENAL'],
  },
  MACHINE_GUNNER: {
    role: 'Feu puissant à distance, déplacement lent.',
    recruitAt: ['ARSENAL'],
    requires: ['ARSENAL', 'MUNITIONS'],
  },
  SNIPER: {
    role: 'Tir à 6 cases et grande vision ; très fragile.',
    recruitAt: ['ARSENAL'],
    requires: ['ARSENAL', 'RADIO'],
  },
  BAZOOKA: {
    role: 'Bonus de +6 contre les blindés, efficace contre les bâtiments.',
    recruitAt: ['ARSENAL'],
    requires: ['ARSENAL', 'MUNITIONS'],
  },
  OFFICER: {
    role: 'Pistolet et sabre ; capture et ralliement des soldats.',
    recruitAt: ['ARSENAL'],
    requires: ['ARSENAL'],
  },
  MOTORCYCLE: {
    role: 'Reconnaissance motorisée : mouvement 8, vision 8.',
    recruitAt: ['GARAGE'],
    requires: ['GARAGE'],
    mechanical: true,
  },
  ARMORED_CAR: {
    role: 'Véhicule blindé rapide pour reconnaissance et capture.',
    recruitAt: ['GARAGE'],
    requires: ['GARAGE', 'REFINERY'],
    mechanical: true,
    armored: true,
  },
  TANK: {
    role: 'Blindé lourd, puissant contre les fortifications.',
    recruitAt: ['TANK_FACTORY'],
    requires: ['TANK_FACTORY', 'MUNITIONS'],
    mechanical: true,
    armored: true,
  },
  FIELD_GUN: {
    role: 'Artillerie à 6 cases ; attaque 2 PA.',
    recruitAt: ['GUN_BATTERY', 'TANK_FACTORY'],
    requires: ['MUNITIONS'],
    mechanical: true,
    siege: true,
  },
  ROCKET_LAUNCHER: {
    role: 'Fusées à 7 cases, très puissantes contre les bâtiments ; attaque 2 PA.',
    recruitAt: ['ROCKET_SILO'],
    requires: ['ROCKET_SILO', 'MUNITIONS'],
    mechanical: true,
    siege: true,
  },
  IRON_REVENANT: {
    role: 'Armure mécanique de mêlée ; nécessite des réparations.',
    recruitAt: ['OCCULT_LAB'],
    requires: ['OCCULT_LAB', 'TANK_FACTORY'],
    mechanical: true,
    armored: true,
  },

  PEASANT: {
    role: 'Récolte uniquement sur sa case : bois en forêt, pierre sur relief rocheux, fer sur colline, vivres sur terrain nourricier. Premier paysan gratuit.',
    recruitAt: ['CAMP', 'VILLAGE', 'OUTPOST'],
    requires: [],
    builder: true,
  },
  MILITIA: {
    role: 'Défense bon marché et conquête des premières terres.',
    recruitAt: ['BARRACKS', 'FORT'],
    requires: [],
  },
  SCOUT: {
    role: 'Exploration rapide et reconnaissance à longue distance.',
    recruitAt: ['BARRACKS', 'FORT'],
    requires: [],
  },
  INFANTRY: {
    role: 'Infanterie polyvalente pour tenir et capturer les territoires.',
    recruitAt: ['BARRACKS', 'FORT'],
    requires: [],
  },
  GUARD: {
    role: 'Défenseur lourd, solide mais lent.',
    recruitAt: ['BARRACKS', 'FORT'],
    requires: ['BARRACKS'],
  },
  ARCHER: {
    role: 'Tir à distance, fragile au contact.',
    recruitAt: ['ARCHERY'],
    requires: [],
  },
  KNIGHT: {
    role: 'Cavalerie lourde pour percer et capturer.',
    recruitAt: ['STABLE'],
    requires: ['BARRACKS'],
    mounted: true,
  },
  SIEGE: {
    role: 'Bombardement des fortifications à longue portée. Attaque : 2 PA.',
    recruitAt: ['WORKSHOP'],
    requires: ['BARRACKS'],
    siege: true,
  },
  SPEARMAN: {
    role: 'Bonus de +3 en attaque contre la cavalerie.',
    recruitAt: ['BARRACKS', 'FORT'],
    requires: ['BARRACKS'],
  },
  CROSSBOW: {
    role: 'Bonus de +2 contre gardes, chevaliers et paladins.',
    recruitAt: ['ARCHERY'],
    requires: ['ARCHERY', 'FORGE'],
  },
  RANGER: {
    role: 'Éclaireur archer ; +2 de défense en forêt et reconnaissance.',
    recruitAt: ['ARCHERY'],
    requires: ['ARCHERY'],
  },
  LIGHT_CAVALRY: {
    role: 'Mobilité supérieure et reconnaissance montée.',
    recruitAt: ['STABLE'],
    requires: ['STABLE'],
    mounted: true,
  },
  PALADIN: {
    role: 'Infanterie lourde capable de soigner les alliés proches.',
    recruitAt: ['MONASTERY'],
    requires: ['MONASTERY', 'FORGE'],
    healer: true,
  },
  RAM: {
    role: 'Très solide au contact des bâtiments. Attaque : 2 PA.',
    recruitAt: ['WORKSHOP'],
    requires: ['WORKSHOP'],
    siege: true,
  },
  HEALER: {
    role: 'Soigne de 6 PV les alliés blessés proches pour 1 PA.',
    recruitAt: ['MONASTERY', 'FIELD_HOSPITAL'],
    requires: ['MONASTERY'],
    healer: true,
  },
  ENGINEER: {
    role: 'Construit aux frontières et répare les bâtiments proches.',
    recruitAt: ['WORKSHOP'],
    requires: ['WORKSHOP'],
    builder: true,
  },
  BERSERKER: {
    role: 'Attaque très élevée, sans protection défensive.',
    recruitAt: ['BARRACKS', 'FORT'],
    requires: ['BARRACKS', 'FORGE'],
  },
  VOID_ACOLYTE: {
    role: 'Attaquant à distance ; observe les vestiges et les régions lointaines.',
    recruitAt: ['LIBRARY', 'OCCULT_LAB'],
    requires: ['LIBRARY', 'MONASTERY'],
  },
};
export const GATHER_YIELD: Wallet = { STONE: 16, GOLD: 12, WOOD: 20, IRON: 12, FOOD: 18 };
export const BUILDING_REQUIREMENTS: Partial<Record<BuildingKind, BuildingKind[]>> = {
  TESLA_COIL: ['FORGE', 'OCCULT_LAB'],
  CRYPT_BARRACKS: ['BARRACKS', 'OCCULT_LAB'],
  ALCHEMY_FOUNDRY: ['REFINERY', 'OCCULT_LAB'],
  BLACK_OBSERVATORY: ['LIBRARY', 'RADIO'],
  ARSENAL: ['BARRACKS', 'FORGE'],
  BUNKER: ['FORGE'],
  GARAGE: ['WORKSHOP'],
  TANK_FACTORY: ['GARAGE', 'REFINERY'],
  REFINERY: ['FORGE'],
  MUNITIONS: ['ARSENAL'],
  RADIO: ['WORKSHOP'],
  FIELD_HOSPITAL: ['HOUSE', 'MONASTERY'],
  GUN_BATTERY: ['MUNITIONS'],
  OCCULT_LAB: ['LIBRARY', 'FORGE'],
  ROCKET_SILO: ['TANK_FACTORY', 'OCCULT_LAB'],
  RAIL_DEPOT: ['WORKSHOP', 'WAREHOUSE'],

  STABLE: ['BARRACKS'],
  MONASTERY: ['HOUSE'],
  FORGE: ['WORKSHOP'],
  LIBRARY: ['MONASTERY'],
  BAKERY: ['FARM'],
};
export const BUILDING_POPULATION: Partial<Record<BuildingKind, number>> = {
  CAMP: 5,
  HOUSE: 12,
  VILLAGE: 35,
  OUTPOST: 10,
};
export const BUILDING_ROLES: Partial<Record<BuildingKind, string>> = {
  WOOD_WALL:
    'Occupe une case, bloque tous les ennemis et laisse passer vos unités. Se raccorde aux remparts voisins. Évolue avec 45 pierre, puis 45 fer pour l’acier (2 PA par évolution).',
  STONE_WALL:
    'Remplace une palissade : 65 PV, défense 2. Vos unités traversent ; les ennemis doivent ouvrir une brèche. Évolue en acier avec 45 fer et 2 PA.',
  STEEL_WALL:
    'Dernière évolution : 100 PV, défense 4. Bloque les ennemis, même sur une route. L’acier est construit à partir de votre réserve de fer.',
  TESLA_COIL: 'Fortification électrique (+4 défense) ; forme les voltigeurs Tesla.',
  CRYPT_BARRACKS: 'Forme grenadiers revenants et cavaliers spectraux.',
  ALCHEMY_FOUNDRY: 'Produit 5 or par minute et débloque marcheurs de siège et chars possédés.',
  BLACK_OBSERVATORY: 'Observe dans un rayon de 12 cases et forme les chasseurs de maléfices.',
  FARM: 'Produit des vivres pour nourrir les habitants et entretenir les troupes.',
  LUMBER: 'Exploite le bois en forêt ; finance les premières constructions.',
  MINE: 'Extrait le fer des collines pour les armes, les véhicules et les réparations.',
  MARKET: 'Permet de proposer des échanges de ressources par caravane.',
  WAREHOUSE: 'Ajoute 800 places de stockage pour chaque ressource.',
  WORKSHOP: 'Forme ingénieurs, engins de siège et balistes ; débloque forge et garage.',
  BARRACKS: 'Forme les premières troupes et les éclaireurs ; base de la filière militaire.',
  FORT: 'Fortification qui forme les troupes de caserne et sécurise un point de passage.',
  TOWER: 'Poste de surveillance : vision de 7 cases autour de la tour.',
  OUTPOST: 'Forme les paysans, accueille des habitants et évolue en village.',
  VILLAGE: 'Centre civil : forme les paysans, produit des ressources et accueille la population.',

  QUARRY: 'Extrait 4 pierres par minute sur colline ou montagne.',
  ARSENAL: 'Forme fusiliers, troupes d’assaut et officiers.',
  BUNKER: 'Fortification résistante : +5 de défense contre les attaques.',
  GARAGE: 'Produit les motos et automitrailleuses.',
  TANK_FACTORY: 'Assemble chars, canons et batteries de fusées.',
  REFINERY: 'Soutient l’industrie : +4 or par minute ; débloque les blindés.',
  MUNITIONS: 'Débloque les armes lourdes ; le fer nécessaire doit être extrait ou acheté.',
  RADIO: 'Observe le terrain dans un rayon de 10 cases.',
  FIELD_HOSPITAL: 'Forme les guérisseuses et accélère la croissance de population.',
  GUN_BATTERY: 'Position défensive (+3) qui produit les canons de campagne.',
  OCCULT_LAB: 'Unit la forge et les savoirs interdits : chevaliers mécaniques et acolytes.',
  ROCKET_SILO: 'Assemble les batteries de fusées à longue portée.',
  RAIL_DEPOT: 'Logistique industrielle : +1 200 de stockage et +3 or par minute.',

  CAMP: 'Premier paysan gratuit si vous n’en avez aucun. Produit or et vivres ; le bois se récolte en forêt.',
  HOUSE: 'Accueille 12 habitants supplémentaires et augmente votre capacité de recrutement.',
  GRANARY: 'Ajoute 400 places de stockage ; les vivres doivent être récoltés ou produits.',
  HUNTER: 'Fournit des vivres dès les premières récoltes de bois.',
  FISHERY: 'Production importante de vivres sur rivière ou marais.',
  STABLE: 'Recrute la cavalerie légère et les chevaliers.',
  ARCHERY: 'Recrute archers, rôdeurs et arbalétriers.',
  MONASTERY: 'Recrute guérisseuses et paladins ; accélère la croissance de population.',
  FORGE:
    'Transforme les équipements et débloque les troupes lourdement équipées ; le fer vient des mines.',
  LIBRARY: 'Débloque les acolytes du Vide et étend la vision de tous vos bâtiments.',
  BAKERY: 'Transforme votre domaine agricole en production abondante de vivres.',
  WELL: 'Produit des vivres et accélère la croissance de population.',
};

export const BUILDING_DEFENSE: Partial<Record<BuildingKind, number>> = {
  WOOD_WALL: 0,
  STONE_WALL: 2,
  STEEL_WALL: 4,
  TESLA_COIL: 4,
  BUNKER: 5,
  GUN_BATTERY: 3,
};
export const RECON_UNITS: UnitKind[] = [
  'HEX_HUNTER',
  'SCOUT',
  'RANGER',
  'VOID_ACOLYTE',
  'MOTORCYCLE',
  'ARMORED_CAR',
  'SNIPER',
];

export const CITY_LEVELS = ['Avant-poste', 'Village', 'Bourg', 'Ville', 'Cité'];
export const DEFAULT_SETTINGS = {
  locale: 'fr',
  masterVolume: 0,
  musicVolume: 0,
  sfxVolume: 0,
  muteUnfocused: true,
  cameraSpeed: 1,
  edgeScrolling: false,
  grid: true,
  coordinates: false,
  reducedMotion: false,
  highContrast: false,
  confirmDangerous: true,
  autoCenterEvents: false,
  combatNotifications: true,
  realmNotifications: true,
  input: 'mouse',
  uiScale: 1,
  tutorialCompleted: false,
  emblem: 'crown',
  bannerColor: '#bc9860',
  bannerSecondary: '#272b26',
  bannerShape: 'swallow',
  lastCameraQ: 0,
  lastCameraR: 0,
};
export type Settings = typeof DEFAULT_SETTINGS;

/** Manual harvesting is separate from building production and always uses the occupied tile. */
export const TERRAIN_RESOURCES: Record<Terrain, readonly Resource[]> = {
  PLAIN: ['FOOD'],
  FOREST: ['WOOD'],
  HILL: ['STONE', 'IRON'],
  MOUNTAIN: ['STONE'],
  RIVER: ['FOOD'],
  MARSH: ['FOOD'],
  RUINS: ['GOLD'],
  CORRUPTION: [],
  ALIEN: [],
};
export const UNIT_TABS = [
  'Toutes',
  'Civils & soutien',
  'Infanterie médiévale',
  'Armes à distance',
  'Cavalerie',
  'Armes à feu',
  'Véhicules',
  'Artillerie',
  'Occulte',
] as const;
export type UnitTab = (typeof UNIT_TABS)[number];
export const UNIT_CATEGORY: Record<UnitKind, UnitTab> = {
  TESLA_TROOPER: 'Occulte',
  HEX_HUNTER: 'Occulte',
  PLAGUE_MEDIC: 'Civils & soutien',
  GHOUL_INFANTRY: 'Occulte',
  SPECTRAL_RIDER: 'Cavalerie',
  SIEGE_WALKER: 'Véhicules',
  HEX_TANK: 'Véhicules',
  MORTAR: 'Artillerie',
  PEASANT: 'Civils & soutien',
  ENGINEER: 'Civils & soutien',
  HEALER: 'Civils & soutien',
  SCOUT: 'Civils & soutien',
  MILITIA: 'Infanterie médiévale',
  INFANTRY: 'Infanterie médiévale',
  GUARD: 'Infanterie médiévale',
  SPEARMAN: 'Infanterie médiévale',
  BERSERKER: 'Infanterie médiévale',
  PALADIN: 'Infanterie médiévale',
  ARCHER: 'Armes à distance',
  CROSSBOW: 'Armes à distance',
  RANGER: 'Armes à distance',
  KNIGHT: 'Cavalerie',
  LIGHT_CAVALRY: 'Cavalerie',
  RIFLEMAN: 'Armes à feu',
  STORMTROOPER: 'Armes à feu',
  MACHINE_GUNNER: 'Armes à feu',
  SNIPER: 'Armes à feu',
  BAZOOKA: 'Armes à feu',
  OFFICER: 'Armes à feu',
  MOTORCYCLE: 'Véhicules',
  ARMORED_CAR: 'Véhicules',
  TANK: 'Véhicules',
  RAM: 'Artillerie',
  SIEGE: 'Artillerie',
  FIELD_GUN: 'Artillerie',
  ROCKET_LAUNCHER: 'Artillerie',
  IRON_REVENANT: 'Occulte',
  VOID_ACOLYTE: 'Occulte',
};
export const BUILDING_TABS = [
  'Tous',
  'Vie civile',
  'Ressources',
  'Recrutement',
  'Défenses',
  'Industrie',
  'Savoir & logistique',
] as const;
export type BuildingTab = (typeof BUILDING_TABS)[number];
export const BUILDING_CATEGORY: Record<BuildingKind, BuildingTab> = {
  WOOD_WALL: 'Défenses',
  STONE_WALL: 'Défenses',
  STEEL_WALL: 'Défenses',
  TESLA_COIL: 'Défenses',
  CRYPT_BARRACKS: 'Recrutement',
  ALCHEMY_FOUNDRY: 'Industrie',
  BLACK_OBSERVATORY: 'Savoir & logistique',
  CAMP: 'Vie civile',
  HOUSE: 'Vie civile',
  OUTPOST: 'Vie civile',
  VILLAGE: 'Vie civile',
  WELL: 'Vie civile',
  FIELD_HOSPITAL: 'Vie civile',
  FARM: 'Ressources',
  LUMBER: 'Ressources',
  MINE: 'Ressources',
  QUARRY: 'Ressources',
  HUNTER: 'Ressources',
  FISHERY: 'Ressources',
  BAKERY: 'Ressources',
  BARRACKS: 'Recrutement',
  ARCHERY: 'Recrutement',
  STABLE: 'Recrutement',
  ARSENAL: 'Recrutement',
  GARAGE: 'Recrutement',
  FORT: 'Défenses',
  TOWER: 'Défenses',
  BUNKER: 'Défenses',
  GUN_BATTERY: 'Défenses',
  WORKSHOP: 'Industrie',
  FORGE: 'Industrie',
  REFINERY: 'Industrie',
  MUNITIONS: 'Industrie',
  TANK_FACTORY: 'Industrie',
  ROCKET_SILO: 'Industrie',
  MONASTERY: 'Savoir & logistique',
  LIBRARY: 'Savoir & logistique',
  OCCULT_LAB: 'Savoir & logistique',
  RADIO: 'Savoir & logistique',
  RAIL_DEPOT: 'Savoir & logistique',
  WAREHOUSE: 'Savoir & logistique',
  GRANARY: 'Savoir & logistique',
  MARKET: 'Savoir & logistique',
};
export const unitPopulation = (kind: UnitKind) =>
  kind === 'PEASANT'
    ? 3
    : ['TANK', 'HEX_TANK', 'SIEGE_WALKER'].includes(kind)
      ? 12
      : UNIT_PROFILES[kind].mechanical
        ? 8
        : UNIT_PROFILES[kind].siege
          ? 6
          : 5;
export function unitUpkeep(kind: UnitKind): Wallet {
  const cost = Object.values(UNITS[kind].cost).reduce<number>((a, b) => a + b, 0);
  return {
    GOLD: Math.max(0.15, cost / 400),
    WOOD: 0,
    STONE: 0,
    IRON: UNIT_PROFILES[kind].mechanical ? 0.2 + UNITS[kind].attack / 20 : 0,
    FOOD: UNIT_PROFILES[kind].mounted ? 0.65 : 0.25,
  };
}

/** Authoritative upgrade quote shared by the server and the preview. */
export function buildingUpgrade(kind: BuildingKind, level: number) {
  if (isWall(kind)) {
    if (kind === 'STEEL_WALL') return null;
    const next: WallKind = kind === 'WOOD_WALL' ? 'STONE_WALL' : 'STEEL_WALL';
    return {
      kind: next as BuildingKind,
      level: 1,
      name: BUILDINGS[next].name,
      cost: { ...BUILDINGS[next].cost } as Partial<Wallet>,
      population: 0,
      minimumPopulation: 0,
    };
  }
  if (kind === 'CAMP')
    return {
      kind: 'OUTPOST' as BuildingKind,
      level: 1,
      name: BUILDINGS.OUTPOST.name,
      cost: { GOLD: 10, WOOD: 30, FOOD: 15 } as Partial<Wallet>,
      population: 0,
      minimumPopulation: 10,
    };
  if (kind === 'OUTPOST')
    return {
      kind: 'VILLAGE' as BuildingKind,
      level: 1,
      name: CITY_LEVELS[1],
      cost: { STONE: 20, GOLD: 40, WOOD: 45, IRON: 10, FOOD: 20 } as Partial<Wallet>,
      population: 10,
      minimumPopulation: 15,
    };
  if (kind !== 'VILLAGE') {
    if (level >= 3) return null;
    return {
      kind,
      level: level + 1,
      name: `${BUILDINGS[kind].name} · niveau ${level + 1}`,
      cost: Object.fromEntries(
        Object.entries(BUILDINGS[kind].cost).map(([r, value]) => [
          r,
          Math.ceil(value * (0.75 + level * 0.25)),
        ]),
      ) as Partial<Wallet>,
      population: 0,
      minimumPopulation: 0,
    };
  }
  if (level >= 3) return null;
  return {
    kind: 'VILLAGE' as BuildingKind,
    level: level + 1,
    name: CITY_LEVELS[level + 1],
    cost: {
      STONE: 20 * level,
      GOLD: 50 * level,
      WOOD: 40 * level,
      IRON: 20 * level,
      FOOD: 25 * level,
    } as Partial<Wallet>,
    population: level * 25,
    minimumPopulation: 0,
  };
}

export const productionMultiplier = (kind: BuildingKind, level: number) =>
  kind === 'VILLAGE' ? level : 1 + (level - 1) * 0.25;
export const trainingBonusAt = (kind: BuildingKind, level: number) =>
  Object.values(UNIT_PROFILES).some((p) => p.recruitAt.includes(kind) && !p.builder)
    ? Math.max(0, level - 1) * 10
    : 0;
export const storageBonus = (kind: BuildingKind, level: number) =>
  (kind === 'WAREHOUSE' ? 800 : kind === 'GRANARY' ? 400 : kind === 'RAIL_DEPOT' ? 1200 : 0) *
  productionMultiplier(kind, level);
export const populationCapacity = (kind: BuildingKind, level: number) =>
  (BUILDING_POPULATION[kind] ?? 0) *
  (kind === 'VILLAGE' ? level + 1 : 2 * productionMultiplier(kind, level));
