import type { UnitProfile, UnitTab, BuildingTab } from './index';
import type { TransportSpec } from './transports';

export const NAVAL_UNITS = {
  FISHING_CUTTER: {
    name: 'Cotre des brumes',
    hp: 40,
    attack: 0,
    buildingAttack: 0,
    defense: 3,
    move: 6,
    vision: 3,
    range: 1,
    capture: 0,
    cost: { GOLD: 180, WOOD: 108, STONE: 0, IRON: 36, FOOD: 36 },
  },
  TROOP_FERRY: {
    name: 'Bac des marches',
    hp: 85,
    attack: 0,
    buildingAttack: 0,
    defense: 5,
    move: 7,
    vision: 2,
    range: 1,
    capture: 0,
    cost: { GOLD: 350, WOOD: 210, STONE: 0, IRON: 70, FOOD: 70 },
  },
  WAR_GALLEY: {
    name: 'Galère des serments',
    hp: 110,
    attack: 17,
    buildingAttack: 34,
    defense: 6,
    move: 6,
    vision: 4,
    range: 3,
    capture: 0,
    cost: { GOLD: 500, WOOD: 300, STONE: 0, IRON: 100, FOOD: 100 },
  },
  SCOUT_LONGSHIP: {
    name: 'Drakkar des veilleurs',
    hp: 65,
    attack: 11,
    buildingAttack: 0,
    defense: 3,
    move: 9,
    vision: 7,
    range: 2,
    capture: 0,
    cost: { GOLD: 320, WOOD: 192, STONE: 0, IRON: 64, FOOD: 64 },
  },
  FISHING_SCHOONER: {
    name: 'Goélette des filets noirs',
    hp: 70,
    attack: 0,
    buildingAttack: 0,
    defense: 5,
    move: 8,
    vision: 3,
    range: 1,
    capture: 0,
    cost: { GOLD: 700, WOOD: 420, STONE: 0, IRON: 140, FOOD: 140 },
  },
  TROOP_BRIG: {
    name: 'Brigantin des légions',
    hp: 150,
    attack: 0,
    buildingAttack: 0,
    defense: 9,
    move: 9,
    vision: 2,
    range: 1,
    capture: 0,
    cost: { GOLD: 1300, WOOD: 780, STONE: 0, IRON: 260, FOOD: 260 },
  },
  CANNON_FRIGATE: {
    name: 'Frégate des cendres',
    hp: 200,
    attack: 30,
    buildingAttack: 60,
    defense: 10,
    move: 8,
    vision: 4,
    range: 4,
    capture: 0,
    cost: { GOLD: 2200, WOOD: 1320, STONE: 0, IRON: 440, FOOD: 440 },
  },
  ESCORT_CORVETTE: {
    name: 'Corvette du crépuscule',
    hp: 120,
    attack: 23,
    buildingAttack: 0,
    defense: 7,
    move: 11,
    vision: 6,
    range: 3,
    capture: 0,
    cost: { GOLD: 1600, WOOD: 960, STONE: 0, IRON: 320, FOOD: 320 },
  },
  FISHING_TRAWLER: {
    name: 'Chalutier de fer',
    hp: 110,
    attack: 0,
    buildingAttack: 0,
    defense: 8,
    move: 9,
    vision: 3,
    range: 1,
    capture: 0,
    cost: { GOLD: 2400, WOOD: 360, STONE: 0, IRON: 1680, FOOD: 480 },
  },
  LANDING_SHIP: {
    name: 'Péniche de débarquement',
    hp: 220,
    attack: 0,
    buildingAttack: 0,
    defense: 14,
    move: 10,
    vision: 2,
    range: 1,
    capture: 0,
    cost: { GOLD: 4800, WOOD: 720, STONE: 0, IRON: 3360, FOOD: 960 },
  },
  SONAR_DESTROYER: {
    name: 'Destroyer Vigie',
    hp: 290,
    attack: 44,
    buildingAttack: 88,
    defense: 16,
    move: 11,
    vision: 5,
    range: 4,
    capture: 0,
    cost: { GOLD: 7000, WOOD: 1050, STONE: 0, IRON: 4900, FOOD: 1400 },
  },
  BLACK_SUBMARINE: {
    name: 'Sous-marin des profondeurs',
    hp: 170,
    attack: 58,
    buildingAttack: 0,
    defense: 8,
    move: 9,
    vision: 4,
    range: 3,
    capture: 0,
    cost: { GOLD: 8500, WOOD: 1275, STONE: 0, IRON: 5950, FOOD: 1700 },
  },
  AUTO_FISHER: {
    name: 'Collecteur pélagique',
    hp: 150,
    attack: 0,
    buildingAttack: 0,
    defense: 11,
    move: 11,
    vision: 3,
    range: 1,
    capture: 0,
    cost: { GOLD: 9000, WOOD: 1350, STONE: 0, IRON: 6300, FOOD: 1800 },
  },
  AMPHIBIOUS_TRANSPORT: {
    name: 'Transport amphibie Bastion',
    hp: 330,
    attack: 0,
    buildingAttack: 0,
    defense: 19,
    move: 12,
    vision: 2,
    range: 1,
    capture: 0,
    cost: { GOLD: 18000, WOOD: 2700, STONE: 0, IRON: 12600, FOOD: 3600 },
  },
  MISSILE_ESCORT: {
    name: 'Frégate lance-missiles',
    hp: 390,
    attack: 64,
    buildingAttack: 128,
    defense: 22,
    move: 13,
    vision: 6,
    range: 5,
    capture: 0,
    cost: { GOLD: 25000, WOOD: 3750, STONE: 0, IRON: 17500, FOOD: 5000 },
  },
  HUNTER_SUBMARINE: {
    name: 'Sous-marin Spectre',
    hp: 235,
    attack: 85,
    buildingAttack: 0,
    defense: 12,
    move: 11,
    vision: 5,
    range: 4,
    capture: 0,
    cost: { GOLD: 31000, WOOD: 4650, STONE: 0, IRON: 21700, FOOD: 6200 },
  },
  ATOMIC_HARVESTER: {
    name: 'Moissonneur des abysses',
    hp: 210,
    attack: 0,
    buildingAttack: 0,
    defense: 15,
    move: 12,
    vision: 3,
    range: 1,
    capture: 0,
    cost: { GOLD: 32000, WOOD: 4800, STONE: 0, IRON: 22400, FOOD: 6400 },
  },
  OCCULT_ARK: {
    name: 'Arche de la nuit liquide',
    hp: 500,
    attack: 0,
    buildingAttack: 0,
    defense: 26,
    move: 14,
    vision: 2,
    range: 1,
    capture: 0,
    cost: { GOLD: 65000, WOOD: 9750, STONE: 0, IRON: 45500, FOOD: 13000 },
  },
  NUCLEAR_DREADNOUGHT: {
    name: 'Cuirassé du soleil noyé',
    hp: 600,
    attack: 100,
    buildingAttack: 200,
    defense: 32,
    move: 12,
    vision: 6,
    range: 6,
    capture: 0,
    cost: { GOLD: 100000, WOOD: 15000, STONE: 0, IRON: 70000, FOOD: 20000 },
  },
  ABYSSAL_SUBMARINE: {
    name: 'Léviathan submersible',
    hp: 320,
    attack: 130,
    buildingAttack: 0,
    defense: 18,
    move: 13,
    vision: 5,
    range: 5,
    capture: 0,
    cost: { GOLD: 120000, WOOD: 18000, STONE: 0, IRON: 84000, FOOD: 24000 },
  },
};
export type NavalKind = keyof typeof NAVAL_UNITS;
export const NAVAL_PROFILES: Record<NavalKind, UnitProfile> = {
  FISHING_CUTTER: {
    role: 'Pêche en mer : +10 vivres/min automatiquement et 40 vivres par pêche manuelle pour 1 PA. Eaux neutres ou à vous, pendant votre présence. Aucune arme.',
    recruitAt: ['NAVAL_FISHERY'],
    requires: [],
    naval: true,
    minRecruitLevel: 1,
    population: 4,
    fishing: 40,
  },
  TROOP_FERRY: {
    role: 'Transport maritime de 4 places, vision 2. Embarquement et débarquement sur une terre voisine praticable.',
    recruitAt: ['PORT'],
    requires: [],
    naval: true,
    minRecruitLevel: 1,
    population: 4,
    transport: true,
  },
  WAR_GALLEY: {
    role: 'Artillerie navale de siège. Bombarde la côte et protège les convois.',
    recruitAt: ['SHIPYARD'],
    requires: [],
    naval: true,
    minRecruitLevel: 1,
    population: 4,
    siege: true,
    armored: true,
  },
  SCOUT_LONGSHIP: {
    role: 'Éclaireur et escorte maritime, rapide mais peu blindé.',
    recruitAt: ['SHIPYARD'],
    requires: [],
    naval: true,
    minRecruitLevel: 1,
    population: 4,
  },
  FISHING_SCHOONER: {
    role: 'Pêche en mer : +40 vivres/min automatiquement et 160 vivres par pêche manuelle pour 1 PA. Eaux neutres ou à vous, pendant votre présence. Aucune arme.',
    recruitAt: ['NAVAL_FISHERY'],
    requires: [],
    naval: true,
    minRecruitLevel: 2,
    population: 6,
    fishing: 160,
  },
  TROOP_BRIG: {
    role: 'Transport maritime de 8 places, vision 2. Embarquement et débarquement sur une terre voisine praticable.',
    recruitAt: ['PORT'],
    requires: [],
    naval: true,
    minRecruitLevel: 2,
    population: 6,
    transport: true,
  },
  CANNON_FRIGATE: {
    role: 'Artillerie navale de siège. Bombarde la côte et protège les convois.',
    recruitAt: ['SHIPYARD'],
    requires: [],
    naval: true,
    minRecruitLevel: 2,
    population: 6,
    siege: true,
    armored: true,
  },
  ESCORT_CORVETTE: {
    role: 'Éclaireur et escorte maritime, rapide mais peu blindé.',
    recruitAt: ['SHIPYARD'],
    requires: [],
    naval: true,
    minRecruitLevel: 2,
    population: 6,
  },
  FISHING_TRAWLER: {
    role: 'Pêche en mer : +90 vivres/min automatiquement et 360 vivres par pêche manuelle pour 1 PA. Eaux neutres ou à vous, pendant votre présence. Aucune arme.',
    recruitAt: ['NAVAL_FISHERY'],
    requires: [],
    naval: true,
    minRecruitLevel: 3,
    population: 8,
    fishing: 360,
    mechanical: true,
  },
  LANDING_SHIP: {
    role: 'Transport maritime de 12 places, vision 2. Embarquement et débarquement sur une terre voisine praticable.',
    recruitAt: ['PORT'],
    requires: ['MUNITIONS'],
    naval: true,
    minRecruitLevel: 3,
    population: 8,
    transport: true,
    mechanical: true,
  },
  SONAR_DESTROYER: {
    role: 'Artillerie navale de siège. Bombarde la côte et protège les convois.',
    recruitAt: ['SHIPYARD'],
    requires: ['MUNITIONS'],
    naval: true,
    minRecruitLevel: 3,
    population: 8,
    siege: true,
    sonar: 2,
    antiAir: 18,
    mechanical: true,
    armored: true,
  },
  BLACK_SUBMARINE: {
    role: 'Torpilles contre les navires uniquement. Invisible sans sonar proche ; révélé 60 secondes après un tir.',
    recruitAt: ['SUBMARINE_BASE'],
    requires: ['MUNITIONS'],
    naval: true,
    minRecruitLevel: 3,
    population: 8,
    submarine: true,
    sonar: 2,
    mechanical: true,
  },
  AUTO_FISHER: {
    role: 'Pêche en mer : +160 vivres/min automatiquement et 640 vivres par pêche manuelle pour 1 PA. Eaux neutres ou à vous, pendant votre présence. Aucune arme.',
    recruitAt: ['NAVAL_FISHERY'],
    requires: ['RADIO'],
    naval: true,
    minRecruitLevel: 4,
    population: 10,
    fishing: 640,
    mechanical: true,
  },
  AMPHIBIOUS_TRANSPORT: {
    role: 'Transport maritime de 16 places, vision 2. Embarquement et débarquement sur une terre voisine praticable.',
    recruitAt: ['PORT'],
    requires: ['RADIO'],
    naval: true,
    minRecruitLevel: 4,
    population: 10,
    transport: true,
    mechanical: true,
  },
  MISSILE_ESCORT: {
    role: 'Artillerie navale de siège. Bombarde la côte et protège les convois.',
    recruitAt: ['SHIPYARD'],
    requires: ['RADIO'],
    naval: true,
    minRecruitLevel: 4,
    population: 10,
    siege: true,
    sonar: 3,
    antiAir: 24,
    mechanical: true,
    armored: true,
  },
  HUNTER_SUBMARINE: {
    role: 'Torpilles contre les navires uniquement. Invisible sans sonar proche ; révélé 60 secondes après un tir.',
    recruitAt: ['SUBMARINE_BASE'],
    requires: ['RADIO'],
    naval: true,
    minRecruitLevel: 4,
    population: 10,
    submarine: true,
    sonar: 2,
    mechanical: true,
  },
  ATOMIC_HARVESTER: {
    role: 'Pêche en mer : +250 vivres/min automatiquement et 1000 vivres par pêche manuelle pour 1 PA. Eaux neutres ou à vous, pendant votre présence. Aucune arme.',
    recruitAt: ['NAVAL_FISHERY'],
    requires: ['NUCLEAR_REACTOR'],
    naval: true,
    minRecruitLevel: 5,
    population: 12,
    fishing: 1000,
    mechanical: true,
  },
  OCCULT_ARK: {
    role: 'Transport maritime de 24 places, vision 2. Embarquement et débarquement sur une terre voisine praticable.',
    recruitAt: ['PORT'],
    requires: ['NUCLEAR_REACTOR'],
    naval: true,
    minRecruitLevel: 5,
    population: 12,
    transport: true,
    mechanical: true,
  },
  NUCLEAR_DREADNOUGHT: {
    role: 'Artillerie navale de siège. Bombarde la côte et protège les convois.',
    recruitAt: ['SHIPYARD'],
    requires: ['NUCLEAR_REACTOR'],
    naval: true,
    minRecruitLevel: 5,
    population: 12,
    siege: true,
    sonar: 4,
    antiAir: 30,
    mechanical: true,
    armored: true,
  },
  ABYSSAL_SUBMARINE: {
    role: 'Torpilles contre les navires uniquement. Invisible sans sonar proche ; révélé 60 secondes après un tir.',
    recruitAt: ['SUBMARINE_BASE'],
    requires: ['NUCLEAR_REACTOR'],
    naval: true,
    minRecruitLevel: 5,
    population: 12,
    submarine: true,
    sonar: 2,
    mechanical: true,
  },
};
export const NAVAL_TIERS = {
  FISHING_CUTTER: 1,
  TROOP_FERRY: 1,
  WAR_GALLEY: 1,
  SCOUT_LONGSHIP: 1,
  FISHING_SCHOONER: 2,
  TROOP_BRIG: 2,
  CANNON_FRIGATE: 2,
  ESCORT_CORVETTE: 2,
  FISHING_TRAWLER: 3,
  LANDING_SHIP: 3,
  SONAR_DESTROYER: 3,
  BLACK_SUBMARINE: 3,
  AUTO_FISHER: 5,
  AMPHIBIOUS_TRANSPORT: 5,
  MISSILE_ESCORT: 5,
  HUNTER_SUBMARINE: 5,
  ATOMIC_HARVESTER: 6,
  OCCULT_ARK: 6,
  NUCLEAR_DREADNOUGHT: 6,
  ABYSSAL_SUBMARINE: 6,
} as const;
export const NAVAL_ERAS = {
  FISHING_CUTTER: 1,
  TROOP_FERRY: 1,
  WAR_GALLEY: 1,
  SCOUT_LONGSHIP: 1,
  FISHING_SCHOONER: 2,
  TROOP_BRIG: 2,
  CANNON_FRIGATE: 2,
  ESCORT_CORVETTE: 2,
  FISHING_TRAWLER: 3,
  LANDING_SHIP: 3,
  SONAR_DESTROYER: 3,
  BLACK_SUBMARINE: 3,
  AUTO_FISHER: 4,
  AMPHIBIOUS_TRANSPORT: 4,
  MISSILE_ESCORT: 4,
  HUNTER_SUBMARINE: 4,
  ATOMIC_HARVESTER: 5,
  OCCULT_ARK: 5,
  NUCLEAR_DREADNOUGHT: 5,
  ABYSSAL_SUBMARINE: 5,
} as const;
export const NAVAL_CATEGORIES = Object.fromEntries(
  Object.keys(NAVAL_UNITS).map((k) => [k, 'Marine']),
) as Record<NavalKind, UnitTab>;
export const NAVAL_TRANSPORTS = {
  TROOP_FERRY: { capacity: 4, vehicles: false, landing: 'SEA' },
  TROOP_BRIG: { capacity: 8, vehicles: true, heavy: true, landing: 'SEA' },
  LANDING_SHIP: { capacity: 12, vehicles: true, heavy: true, landing: 'SEA' },
  AMPHIBIOUS_TRANSPORT: { capacity: 16, vehicles: true, heavy: true, landing: 'SEA' },
  OCCULT_ARK: { capacity: 24, vehicles: true, heavy: true, landing: 'SEA' },
} satisfies Partial<Record<NavalKind, TransportSpec>>;
export const NAVAL_SHEETS = [
  'naval-medieval',
  'naval-empire',
  'naval-industrial',
  'naval-modern',
  'naval-atomic',
];
export const NAVAL_FRAMES = {
  FISHING_CUTTER: 4032,
  TROOP_FERRY: 4033,
  WAR_GALLEY: 4034,
  SCOUT_LONGSHIP: 4035,
  FISHING_SCHOONER: 4056,
  TROOP_BRIG: 4057,
  CANNON_FRIGATE: 4058,
  ESCORT_CORVETTE: 4059,
  FISHING_TRAWLER: 4080,
  LANDING_SHIP: 4081,
  SONAR_DESTROYER: 4082,
  BLACK_SUBMARINE: 4083,
  AUTO_FISHER: 4104,
  AMPHIBIOUS_TRANSPORT: 4105,
  MISSILE_ESCORT: 4106,
  HUNTER_SUBMARINE: 4107,
  ATOMIC_HARVESTER: 4128,
  OCCULT_ARK: 4129,
  NUCLEAR_DREADNOUGHT: 4130,
  ABYSSAL_SUBMARINE: 4131,
};
export const NAVAL_BUILDINGS = {
  PORT: {
    name: 'Port des marches',
    hp: 180,
    capture: 4,
    cost: { GOLD: 100, WOOD: 150, STONE: 60, IRON: 20, FOOD: 0 },
    production: {},
    terrains: ['COAST', 'SEA'],
  },
  SHIPYARD: {
    name: 'Chantier naval',
    hp: 260,
    capture: 4,
    cost: { GOLD: 250, WOOD: 200, STONE: 100, IRON: 90, FOOD: 0 },
    production: {},
    terrains: ['COAST', 'SEA'],
  },
  NAVAL_FISHERY: {
    name: 'Pêcherie maritime',
    hp: 120,
    capture: 4,
    cost: { GOLD: 100, WOOD: 120, STONE: 30, IRON: 10, FOOD: 0 },
    production: { FOOD: 8 },
    terrains: ['COAST', 'SEA'],
  },
  SUBMARINE_BASE: {
    name: 'Base des profondeurs',
    hp: 350,
    capture: 4,
    cost: { GOLD: 700, WOOD: 100, STONE: 300, IRON: 500, FOOD: 0 },
    production: {},
    terrains: ['COAST', 'SEA'],
  },
  COASTAL_BATTERY: {
    name: 'Batterie côtière',
    hp: 380,
    capture: 4,
    cost: { GOLD: 400, WOOD: 100, STONE: 250, IRON: 220, FOOD: 0 },
    production: {},
    terrains: ['BEACH', 'PLAIN', 'HILL', 'RUINS'],
  },
};
export type NavalBuildingKind = keyof typeof NAVAL_BUILDINGS;
export const NAVAL_BUILDING_TIERS = {
  PORT: 1,
  SHIPYARD: 2,
  NAVAL_FISHERY: 1,
  SUBMARINE_BASE: 3,
  COASTAL_BATTERY: 2,
} as const;
export const NAVAL_BUILDING_CATEGORIES: Record<NavalBuildingKind, BuildingTab> = {
  PORT: 'Recrutement',
  SHIPYARD: 'Recrutement',
  NAVAL_FISHERY: 'Ressources',
  SUBMARINE_BASE: 'Recrutement',
  COASTAL_BATTERY: 'Défenses',
};
export const NAVAL_BUILDING_FRAMES = {
  PORT: 4036,
  SHIPYARD: 4037,
  NAVAL_FISHERY: 4038,
  SUBMARINE_BASE: 4039,
  COASTAL_BATTERY: 4040,
};
export const isSea = (terrain?: string) => terrain === 'SEA' || terrain === 'COAST';
export const isNavalBuilding = (kind: string): kind is NavalBuildingKind =>
  Object.hasOwn(NAVAL_BUILDINGS, kind);

export const isOffshoreBuilding = (kind: string) =>
  isNavalBuilding(kind) && kind !== 'COASTAL_BATTERY';
