import type { UnitProfile, UnitTab } from './index';

export const RADIOACTIVE_UNITS = {
  RADIUM_GRENADIER: {
    name: 'Grenadier au radium',
    hp: 24,
    attack: 12,
    defense: 4,
    move: 3,
    vision: 5,
    range: 3,
    capture: 1,
    buildingAttack: 12,
    cost: { GOLD: 300, IRON: 140, FOOD: 45, WOOD: 30, STONE: 0 },
  },
  COBALT_SENTINEL: {
    name: 'Sentinelle de cobalt',
    hp: 38,
    attack: 10,
    defense: 8,
    move: 2,
    vision: 4,
    range: 2,
    capture: 1,
    buildingAttack: 10,
    cost: { GOLD: 370, IRON: 200, FOOD: 50, WOOD: 35, STONE: 0 },
  },
  ISOTOPE_SNIPER: {
    name: 'Tireur isotopique',
    hp: 19,
    attack: 17,
    defense: 2,
    move: 3,
    vision: 9,
    range: 6,
    capture: 1,
    buildingAttack: 17,
    cost: { GOLD: 410, IRON: 145, FOOD: 40, WOOD: 30, STONE: 0 },
  },
  ATOMIC_SAPPER: {
    name: 'Sapeur atomique',
    hp: 25,
    attack: 10,
    defense: 4,
    move: 2,
    vision: 5,
    range: 3,
    capture: 0,
    buildingAttack: 28,
    cost: { GOLD: 430, IRON: 210, FOOD: 50, WOOD: 50, STONE: 0 },
  },
  PALE_EXECUTIONER: {
    name: 'Exécuteur blafard',
    hp: 45,
    attack: 23,
    defense: 6,
    move: 2,
    vision: 4,
    range: 1,
    capture: 1,
    buildingAttack: 23,
    cost: { GOLD: 510, IRON: 240, FOOD: 75, WOOD: 30, STONE: 0 },
  },
  GAMMA_TEMPLAR: {
    name: 'Templier gamma',
    hp: 34,
    attack: 16,
    defense: 6,
    move: 3,
    vision: 6,
    range: 4,
    capture: 1,
    buildingAttack: 16,
    cost: { GOLD: 530, IRON: 250, FOOD: 65, WOOD: 35, STONE: 0 },
  },
  RADIUM_HUSSAR: {
    name: 'Hussard au radium',
    hp: 28,
    attack: 14,
    defense: 4,
    move: 6,
    vision: 6,
    range: 1,
    capture: 1,
    buildingAttack: 14,
    cost: { GOLD: 340, IRON: 120, FOOD: 90, WOOD: 35, STONE: 0 },
  },
  ISOTOPE_LANCER: {
    name: 'Lancier isotopique',
    hp: 32,
    attack: 18,
    defense: 4,
    move: 5,
    vision: 5,
    range: 1,
    capture: 1,
    buildingAttack: 18,
    cost: { GOLD: 390, IRON: 170, FOOD: 100, WOOD: 40, STONE: 0 },
  },
  COBALT_CUIRASSIER: {
    name: 'Cuirassier de cobalt',
    hp: 46,
    attack: 14,
    defense: 8,
    move: 4,
    vision: 5,
    range: 1,
    capture: 1,
    buildingAttack: 14,
    cost: { GOLD: 470, IRON: 220, FOOD: 120, WOOD: 45, STONE: 0 },
  },
  ASH_DRAGOON: {
    name: 'Dragon des cendres',
    hp: 27,
    attack: 13,
    defense: 4,
    move: 5,
    vision: 7,
    range: 4,
    capture: 1,
    buildingAttack: 13,
    cost: { GOLD: 410, IRON: 155, FOOD: 95, WOOD: 40, STONE: 0 },
  },
  PALE_OUTRIDER: {
    name: 'Éclaireur blafard',
    hp: 24,
    attack: 12,
    defense: 3,
    move: 7,
    vision: 10,
    range: 3,
    capture: 1,
    buildingAttack: 12,
    cost: { GOLD: 420, IRON: 125, FOOD: 100, WOOD: 35, STONE: 0 },
  },
  GAMMA_PALADIN: {
    name: 'Paladin gamma',
    hp: 44,
    attack: 19,
    defense: 7,
    move: 4,
    vision: 6,
    range: 1,
    capture: 1,
    buildingAttack: 19,
    cost: { GOLD: 560, IRON: 250, FOOD: 140, WOOD: 50, STONE: 0 },
  },
  RADIUM_COURIER: {
    name: 'Estafette au radium',
    hp: 23,
    attack: 10,
    defense: 3,
    move: 9,
    vision: 11,
    range: 3,
    capture: 1,
    buildingAttack: 10,
    cost: { GOLD: 360, IRON: 160, FOOD: 35, WOOD: 25, STONE: 0 },
  },
  ISOTOPE_BIKE: {
    name: 'Moto d’assaut isotopique',
    hp: 29,
    attack: 15,
    defense: 4,
    move: 7,
    vision: 6,
    range: 3,
    capture: 1,
    buildingAttack: 15,
    cost: { GOLD: 420, IRON: 200, FOOD: 40, WOOD: 30, STONE: 0 },
  },
  COBALT_SIDECAR: {
    name: 'Side-car de cobalt',
    hp: 38,
    attack: 13,
    defense: 7,
    move: 5,
    vision: 6,
    range: 3,
    capture: 1,
    buildingAttack: 13,
    cost: { GOLD: 450, IRON: 230, FOOD: 45, WOOD: 40, STONE: 0 },
  },
  PALE_HUNTER_BIKE: {
    name: 'Chasseur blafard motorisé',
    hp: 25,
    attack: 18,
    defense: 3,
    move: 7,
    vision: 8,
    range: 5,
    capture: 1,
    buildingAttack: 18,
    cost: { GOLD: 500, IRON: 210, FOOD: 40, WOOD: 30, STONE: 0 },
  },
  GAMMA_TRIKE: {
    name: 'Tricycle gamma',
    hp: 30,
    attack: 10,
    defense: 4,
    move: 6,
    vision: 8,
    range: 5,
    capture: 0,
    buildingAttack: 10,
    cost: { GOLD: 480, IRON: 230, FOOD: 40, WOOD: 35, STONE: 0 },
  },
  APOCALYPSE_BIKE: {
    name: 'Moto de l’Apocalypse',
    hp: 36,
    attack: 14,
    defense: 5,
    move: 5,
    vision: 6,
    range: 4,
    capture: 0,
    buildingAttack: 30,
    cost: { GOLD: 600, IRON: 280, FOOD: 50, WOOD: 45, STONE: 0 },
  },
  RADIUM_SCOUT_CAR: {
    name: 'Automitrailleuse au radium',
    hp: 35,
    attack: 13,
    defense: 5,
    move: 7,
    vision: 10,
    range: 4,
    capture: 1,
    buildingAttack: 13,
    cost: { GOLD: 490, IRON: 250, FOOD: 40, WOOD: 50, STONE: 0 },
  },
  COBALT_HALFTRACK: {
    name: 'Semi-chenillé de cobalt',
    hp: 48,
    attack: 17,
    defense: 7,
    move: 4,
    vision: 6,
    range: 3,
    capture: 1,
    buildingAttack: 17,
    cost: { GOLD: 580, IRON: 320, FOOD: 50, WOOD: 55, STONE: 0 },
  },
  ISOTOPE_TANK_HUNTER: {
    name: 'Chasseur de chars isotopique',
    hp: 43,
    attack: 23,
    defense: 5,
    move: 3,
    vision: 7,
    range: 5,
    capture: 0,
    buildingAttack: 23,
    cost: { GOLD: 690, IRON: 370, FOOD: 55, WOOD: 50, STONE: 0 },
  },
  MAUSOLEUM_TANK: {
    name: 'Char Mausolée',
    hp: 76,
    attack: 20,
    defense: 9,
    move: 2,
    vision: 5,
    range: 3,
    capture: 0,
    buildingAttack: 20,
    cost: { GOLD: 900, IRON: 520, FOOD: 75, WOOD: 70, STONE: 0 },
  },
  GAMMA_FLAK_CRAWLER: {
    name: 'Chenillé Flak gamma',
    hp: 44,
    attack: 10,
    defense: 6,
    move: 3,
    vision: 9,
    range: 6,
    capture: 0,
    buildingAttack: 10,
    cost: { GOLD: 660, IRON: 350, FOOD: 50, WOOD: 45, STONE: 0 },
  },
  APOCALYPSE_CRAWLER: {
    name: 'Chenillé de l’Apocalypse',
    hp: 52,
    attack: 17,
    defense: 6,
    move: 2,
    vision: 7,
    range: 6,
    capture: 0,
    buildingAttack: 40,
    cost: { GOLD: 980, IRON: 550, FOOD: 70, WOOD: 80, STONE: 0 },
  },
  RADIUM_RECON: {
    name: 'Épervier au radium',
    hp: 23,
    attack: 8,
    defense: 3,
    move: 12,
    vision: 14,
    range: 3,
    capture: 0,
    buildingAttack: 8,
    cost: { GOLD: 520, IRON: 240, FOOD: 35, WOOD: 50, STONE: 0 },
  },
  ISOTOPE_INTERCEPTOR: {
    name: 'Intercepteur isotopique',
    hp: 31,
    attack: 14,
    defense: 4,
    move: 10,
    vision: 9,
    range: 4,
    capture: 0,
    buildingAttack: 14,
    cost: { GOLD: 650, IRON: 340, FOOD: 45, WOOD: 55, STONE: 0 },
  },
  COBALT_ATTACK_PLANE: {
    name: 'Avion d’assaut cobalt',
    hp: 45,
    attack: 22,
    defense: 7,
    move: 6,
    vision: 7,
    range: 3,
    capture: 0,
    buildingAttack: 22,
    cost: { GOLD: 760, IRON: 410, FOOD: 55, WOOD: 70, STONE: 0 },
  },
  PALE_NIGHT_FIGHTER: {
    name: 'Chasseur nocturne blafard',
    hp: 29,
    attack: 18,
    defense: 4,
    move: 8,
    vision: 12,
    range: 5,
    capture: 0,
    buildingAttack: 18,
    cost: { GOLD: 780, IRON: 370, FOOD: 45, WOOD: 60, STONE: 0 },
  },
  GAMMA_BOMBER: {
    name: 'Bombardier gamma',
    hp: 48,
    attack: 14,
    defense: 5,
    move: 5,
    vision: 8,
    range: 4,
    capture: 0,
    buildingAttack: 36,
    cost: { GOLD: 950, IRON: 500, FOOD: 65, WOOD: 90, STONE: 0 },
  },
  APOCALYPSE_WING: {
    name: 'Aile de l’Apocalypse',
    hp: 62,
    attack: 19,
    defense: 7,
    move: 4,
    vision: 9,
    range: 5,
    capture: 0,
    buildingAttack: 44,
    cost: { GOLD: 1250, IRON: 680, FOOD: 90, WOOD: 120, STONE: 0 },
  },
  RADIUM_GYRO: {
    name: 'Autogire au radium',
    hp: 26,
    attack: 10,
    defense: 3,
    move: 9,
    vision: 12,
    range: 3,
    capture: 0,
    buildingAttack: 10,
    cost: { GOLD: 510, IRON: 240, FOOD: 35, WOOD: 40, STONE: 0 },
  },
  ISOTOPE_HELICOPTER: {
    name: 'Hélicoptère isotopique',
    hp: 32,
    attack: 16,
    defense: 4,
    move: 7,
    vision: 8,
    range: 4,
    capture: 0,
    buildingAttack: 16,
    cost: { GOLD: 640, IRON: 330, FOOD: 45, WOOD: 50, STONE: 0 },
  },
  COBALT_GUNSHIP: {
    name: 'Canonnière cobalt',
    hp: 49,
    attack: 21,
    defense: 8,
    move: 4,
    vision: 7,
    range: 3,
    capture: 0,
    buildingAttack: 21,
    cost: { GOLD: 810, IRON: 430, FOOD: 60, WOOD: 65, STONE: 0 },
  },
  PALE_HUNTER_HELI: {
    name: 'Hélicoptère Chasseur blafard',
    hp: 30,
    attack: 23,
    defense: 3,
    move: 6,
    vision: 10,
    range: 5,
    capture: 0,
    buildingAttack: 23,
    cost: { GOLD: 820, IRON: 390, FOOD: 50, WOOD: 50, STONE: 0 },
  },
  GAMMA_HELICOPTER: {
    name: 'Hélicoptère Flak gamma',
    hp: 36,
    attack: 11,
    defense: 5,
    move: 6,
    vision: 10,
    range: 5,
    capture: 0,
    buildingAttack: 11,
    cost: { GOLD: 740, IRON: 370, FOOD: 50, WOOD: 55, STONE: 0 },
  },
  APOCALYPSE_HELICOPTER: {
    name: 'Hélicoptère de l’Apocalypse',
    hp: 57,
    attack: 17,
    defense: 6,
    move: 4,
    vision: 8,
    range: 4,
    capture: 0,
    buildingAttack: 39,
    cost: { GOLD: 1100, IRON: 580, FOOD: 80, WOOD: 95, STONE: 0 },
  },
};

export const RADIOACTIVE_PROFILES = {
  RADIUM_GRENADIER: {
    radioactive: true,
    population: 7,
    recruitAt: ['ARSENAL'],
    requires: ['NUCLEAR_REACTOR'],
    role: 'Infanterie polyvalente à tir rapide ; capture les terres, portée 3.',
  },
  COBALT_SENTINEL: {
    radioactive: true,
    population: 7,
    recruitAt: ['FORT'],
    requires: ['NUCLEAR_REACTOR'],
    role: 'Infanterie de ligne très résistante ; lente, portée courte.',
  },
  ISOTOPE_SNIPER: {
    radioactive: true,
    population: 7,
    recruitAt: ['ARSENAL'],
    requires: ['NUCLEAR_REACTOR'],
    role: 'Tireur de précision à 6 cases et vision 9 ; fragile s’il est rejoint.',
  },
  ATOMIC_SAPPER: {
    radioactive: true,
    population: 7,
    recruitAt: ['WORKSHOP'],
    requires: ['NUCLEAR_REACTOR'],
    siege: true,
    role: 'Démolit les fortifications avec une attaque de bâtiment de 28 ; tir à 3 cases, 2 PA. Ne construit pas.',
  },
  PALE_EXECUTIONER: {
    radioactive: true,
    population: 7,
    recruitAt: ['CRYPT_BARRACKS'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    role: 'Assaut brutal au corps à corps ; incapable de toucher les cibles aériennes.',
  },
  GAMMA_TEMPLAR: {
    radioactive: true,
    population: 11,
    recruitAt: ['TESLA_COIL'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    antiAir: 6,
    role: 'Infanterie électrique d’élite ; +6 dégâts contre les aéronefs, portée 4.',
  },
  RADIUM_HUSSAR: {
    radioactive: true,
    population: 8,
    recruitAt: ['STABLE'],
    requires: ['NUCLEAR_REACTOR'],
    mounted: true,
    role: 'Charge rapide au sabre et capture ; vulnérable aux tirs et incapable d’attaquer en l’air.',
  },
  ISOTOPE_LANCER: {
    radioactive: true,
    population: 8,
    recruitAt: ['STABLE'],
    requires: ['NUCLEAR_REACTOR'],
    mounted: true,
    role: 'Lance de choc, forte attaque de mêlée ; doit atteindre le contact.',
  },
  COBALT_CUIRASSIER: {
    radioactive: true,
    population: 8,
    recruitAt: ['STABLE'],
    requires: ['NUCLEAR_REACTOR'],
    mounted: true,
    role: 'Cavalerie blindée pour tenir une brèche ; moins rapide que les hussards.',
  },
  ASH_DRAGOON: {
    radioactive: true,
    population: 8,
    recruitAt: ['STABLE'],
    requires: ['NUCLEAR_REACTOR'],
    mounted: true,
    role: 'Cavalier au fusil, attaque à 4 cases ; capture et harcèlement.',
  },
  PALE_OUTRIDER: {
    radioactive: true,
    population: 8,
    recruitAt: ['CRYPT_BARRACKS'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY', 'STABLE'],
    mounted: true,
    role: 'Éclaireur spectral à cheval : vision 10, reconnaissance des environs, tir à 3 cases.',
  },
  GAMMA_PALADIN: {
    radioactive: true,
    population: 12,
    recruitAt: ['MONASTERY'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY', 'STABLE'],
    mounted: true,
    healer: true,
    role: 'Chevalier monté de choc ; soigne les alliés non mécaniques proches de 3 PV pour 1 PA.',
  },
  RADIUM_COURIER: {
    radioactive: true,
    population: 9,
    recruitAt: ['GARAGE'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    role: 'Reconnaissance motorisée : vision 11, déplacement 9 ; armement léger pour ce palier.',
  },
  ISOTOPE_BIKE: {
    radioactive: true,
    population: 9,
    recruitAt: ['GARAGE'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    role: 'Moto d’assaut rapide à mitrailleuses ; capture les terres.',
  },
  COBALT_SIDECAR: {
    radioactive: true,
    population: 9,
    recruitAt: ['GARAGE'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    role: 'Side-car blindé résistant, plus lent que les motos d’assaut.',
  },
  PALE_HUNTER_BIKE: {
    radioactive: true,
    population: 9,
    recruitAt: ['GARAGE'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    role: 'Tir de précision mobile à 5 cases ; blindage léger.',
  },
  GAMMA_TRIKE: {
    radioactive: true,
    population: 9,
    recruitAt: ['GARAGE'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    antiAir: 17,
    role: 'Escorte antiaérienne : +17 dégâts contre les aéronefs ; faible contre les blindés au sol.',
  },
  APOCALYPSE_BIKE: {
    radioactive: true,
    population: 13,
    recruitAt: ['GARAGE'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    siege: true,
    role: 'Side-car lance-fusées : attaque 30 contre les bâtiments, portée 4 ; attaque à 2 PA.',
  },
  RADIUM_SCOUT_CAR: {
    radioactive: true,
    population: 14,
    recruitAt: ['GARAGE'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    armored: true,
    role: 'Reconnaissance blindée ; vision 10, tir à 4 cases, capture et cartographie.',
  },
  COBALT_HALFTRACK: {
    radioactive: true,
    population: 14,
    recruitAt: ['TANK_FACTORY'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    armored: true,
    role: 'Blindé d’assaut qui peut revendiquer les terres ; portée limitée.',
  },
  ISOTOPE_TANK_HUNTER: {
    radioactive: true,
    population: 14,
    recruitAt: ['TANK_FACTORY'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    armored: true,
    role: 'Canon lourd à 5 cases, forte attaque contre les unités ; flancs moins protégés.',
  },
  MAUSOLEUM_TANK: {
    radioactive: true,
    population: 14,
    recruitAt: ['ATOMIC_FOUNDRY'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    armored: true,
    role: 'Forteresse terrestre très résistante ; déplacement 2, portée 3 et entretien élevé.',
  },
  GAMMA_FLAK_CRAWLER: {
    radioactive: true,
    population: 14,
    recruitAt: ['FLAK_BATTERY'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    mechanical: true,
    armored: true,
    antiAir: 22,
    role: 'Défense antiaérienne lourde : +22 dégâts en l’air, portée 6 ; puissance réduite au sol.',
  },
  APOCALYPSE_CRAWLER: {
    radioactive: true,
    population: 18,
    recruitAt: ['ATOMIC_FOUNDRY'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    mechanical: true,
    armored: true,
    siege: true,
    role: 'Batterie de siège : attaque 40 contre les bâtiments à 6 cases, 2 PA ; mobilité réduite.',
  },
  RADIUM_RECON: {
    radioactive: true,
    population: 14,
    recruitAt: ['AERODROME'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    flying: true,
    role: 'Reconnaissance aérienne : vision 14, déplacement 12, cartographie ; peu armé. Survole les terrains et remparts, sans capture.',
  },
  ISOTOPE_INTERCEPTOR: {
    radioactive: true,
    population: 14,
    recruitAt: ['AERODROME'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    flying: true,
    antiAir: 15,
    role: 'Chasseur rapide : +15 dégâts contre les aéronefs ; portée 4. Survole les terrains et remparts, sans capture.',
  },
  COBALT_ATTACK_PLANE: {
    radioactive: true,
    population: 14,
    recruitAt: ['AERODROME'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    flying: true,
    armored: true,
    role: 'Avion cuirassé d’appui rapproché ; puissant au sol mais plus lent que les chasseurs. Survole les terrains et remparts, sans capture.',
  },
  PALE_NIGHT_FIGHTER: {
    radioactive: true,
    population: 14,
    recruitAt: ['AERODROME'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    flying: true,
    antiAir: 9,
    role: 'Chasseur à longue vision : portée 5, +9 dégâts contre les aéronefs. Survole les terrains et remparts, sans capture.',
  },
  GAMMA_BOMBER: {
    radioactive: true,
    population: 14,
    recruitAt: ['AERODROME'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    mechanical: true,
    flying: true,
    siege: true,
    role: 'Bombardement lourd : attaque 36 contre les bâtiments, portée 4, 2 PA. Survole les terrains et remparts, sans capture.',
  },
  APOCALYPSE_WING: {
    radioactive: true,
    population: 18,
    recruitAt: ['AIRSHIP_YARD'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    mechanical: true,
    flying: true,
    siege: true,
    role: 'Aile volante de siège : attaque 44 contre les bâtiments à 5 cases, 2 PA ; coût et entretien extrêmes. Survole les terrains et remparts, sans capture.',
  },
  RADIUM_GYRO: {
    radioactive: true,
    population: 12,
    recruitAt: ['HELIPAD'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    flying: true,
    role: 'Autogire de reconnaissance : vision 12 et cartographie ; blindage léger. Survole les terrains et remparts, sans capture.',
  },
  ISOTOPE_HELICOPTER: {
    radioactive: true,
    population: 12,
    recruitAt: ['HELIPAD'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    flying: true,
    role: 'Hélicoptère d’attaque polyvalent, portée 4 et bonne mobilité. Survole les terrains et remparts, sans capture.',
  },
  COBALT_GUNSHIP: {
    radioactive: true,
    population: 12,
    recruitAt: ['HELIPAD'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    flying: true,
    armored: true,
    role: 'Hélicoptère blindé d’assaut ; excellente résistance, portée courte. Survole les terrains et remparts, sans capture.',
  },
  PALE_HUNTER_HELI: {
    radioactive: true,
    population: 12,
    recruitAt: ['HELIPAD'],
    requires: ['NUCLEAR_REACTOR'],
    mechanical: true,
    flying: true,
    role: 'Canon de précision à 5 cases et vision 10 ; fuselage fragile. Survole les terrains et remparts, sans capture.',
  },
  GAMMA_HELICOPTER: {
    radioactive: true,
    population: 12,
    recruitAt: ['HELIPAD'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    mechanical: true,
    flying: true,
    antiAir: 21,
    role: 'Interception en vol : +21 dégâts contre les aéronefs ; peu efficace contre les chars. Survole les terrains et remparts, sans capture.',
  },
  APOCALYPSE_HELICOPTER: {
    radioactive: true,
    population: 16,
    recruitAt: ['HELIPAD'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY'],
    mechanical: true,
    flying: true,
    siege: true,
    role: 'Double rotor de siège : attaque 39 contre les bâtiments, portée 4, 2 PA. Survole les terrains et remparts, sans capture.',
  },
} satisfies Record<keyof typeof RADIOACTIVE_UNITS, UnitProfile>;

export const RADIOACTIVE_CATEGORIES = {
  RADIUM_GRENADIER: 'Armes à feu',
  COBALT_SENTINEL: 'Armes à feu',
  ISOTOPE_SNIPER: 'Armes à feu',
  ATOMIC_SAPPER: 'Armes à feu',
  PALE_EXECUTIONER: 'Occulte',
  GAMMA_TEMPLAR: 'Occulte',
  RADIUM_HUSSAR: 'Cavalerie',
  ISOTOPE_LANCER: 'Cavalerie',
  COBALT_CUIRASSIER: 'Cavalerie',
  ASH_DRAGOON: 'Cavalerie',
  PALE_OUTRIDER: 'Cavalerie',
  GAMMA_PALADIN: 'Cavalerie',
  RADIUM_COURIER: 'Motos',
  ISOTOPE_BIKE: 'Motos',
  COBALT_SIDECAR: 'Motos',
  PALE_HUNTER_BIKE: 'Motos',
  GAMMA_TRIKE: 'Motos',
  APOCALYPSE_BIKE: 'Motos',
  RADIUM_SCOUT_CAR: 'Véhicules',
  COBALT_HALFTRACK: 'Véhicules',
  ISOTOPE_TANK_HUNTER: 'Véhicules',
  MAUSOLEUM_TANK: 'Véhicules',
  GAMMA_FLAK_CRAWLER: 'Véhicules',
  APOCALYPSE_CRAWLER: 'Véhicules',
  RADIUM_RECON: 'Aviation',
  ISOTOPE_INTERCEPTOR: 'Aviation',
  COBALT_ATTACK_PLANE: 'Aviation',
  PALE_NIGHT_FIGHTER: 'Aviation',
  GAMMA_BOMBER: 'Aviation',
  APOCALYPSE_WING: 'Aviation',
  RADIUM_GYRO: 'Hélicoptères',
  ISOTOPE_HELICOPTER: 'Hélicoptères',
  COBALT_GUNSHIP: 'Hélicoptères',
  PALE_HUNTER_HELI: 'Hélicoptères',
  GAMMA_HELICOPTER: 'Hélicoptères',
  APOCALYPSE_HELICOPTER: 'Hélicoptères',
} satisfies Record<keyof typeof RADIOACTIVE_UNITS, UnitTab>;

export const RADIOACTIVE_RECON = [
  'PALE_OUTRIDER',
  'RADIUM_COURIER',
  'RADIUM_SCOUT_CAR',
  'RADIUM_RECON',
  'RADIUM_GYRO',
] as const;
