import type { UnitProfile, UnitTab } from './index';

// Variants share the existing family miniature; their armament and role are distinct.
export const SPECIALIST_UNITS = {
  NEUTRON_FLAK: {
    name: 'Bastion antiaérien à neutrons',
    hp: 230,
    attack: 14,
    buildingAttack: 14,
    defense: 17,
    move: 2,
    vision: 8,
    range: 6,
    capture: 0,
    cost: { GOLD: 1500, IRON: 900, WOOD: 100, STONE: 0, FOOD: 80 },
  },
  GLOCKE_WACHT: {
    name: 'Die Glocke — Wacht',
    hp: 220,
    attack: 54,
    buildingAttack: 75,
    defense: 12,
    move: 5,
    vision: 9,
    range: 4,
    capture: 0,
    cost: { GOLD: 2200, IRON: 1300, WOOD: 240, STONE: 0, FOOD: 180 },
  },
  GLOCKE_STURM: {
    name: 'Die Glocke — Sturm',
    hp: 290,
    attack: 62,
    buildingAttack: 125,
    defense: 15,
    move: 4,
    vision: 8,
    range: 5,
    capture: 0,
    cost: { GOLD: 3200, IRON: 2000, WOOD: 320, STONE: 0, FOOD: 230 },
  },
  TESLA_AIRSHIP: {
    name: 'Dirigeable des orages',
    hp: 155,
    attack: 36,
    buildingAttack: 70,
    defense: 9,
    move: 5,
    vision: 10,
    range: 4,
    capture: 0,
    cost: { GOLD: 500, IRON: 350, WOOD: 100, STONE: 0, FOOD: 60 },
  },
  ISOTOPE_AIRSHIP: {
    name: 'Dirigeable isotopique',
    hp: 190,
    attack: 46,
    buildingAttack: 150,
    defense: 12,
    move: 4,
    vision: 10,
    range: 5,
    capture: 0,
    cost: { GOLD: 900, IRON: 650, WOOD: 150, STONE: 0, FOOD: 80 },
  },
  ASH_DRAKE: {
    name: 'Drake des cendres',
    hp: 85,
    attack: 27,
    buildingAttack: 65,
    defense: 6,
    move: 6,
    vision: 7,
    range: 2,
    capture: 0,
    cost: { GOLD: 250, IRON: 70, WOOD: 40, STONE: 0, FOOD: 100 },
  },
  STORM_WYVERN: {
    name: 'Wyverne des tempêtes',
    hp: 130,
    attack: 37,
    buildingAttack: 100,
    defense: 9,
    move: 8,
    vision: 9,
    range: 3,
    capture: 0,
    cost: { GOLD: 650, IRON: 180, WOOD: 60, STONE: 0, FOOD: 160 },
  },
  RADIUM_DRAGON: {
    name: 'Dragon au radium',
    hp: 190,
    attack: 47,
    buildingAttack: 180,
    defense: 14,
    move: 6,
    vision: 8,
    range: 3,
    capture: 0,
    cost: { GOLD: 1000, IRON: 450, WOOD: 100, STONE: 0, FOOD: 220 },
  },
} as const;
type Kind = keyof typeof SPECIALIST_UNITS;
const bell = {
  recruitAt: ['GLOCKE_COMPLEX'],
  requires: ['GLOCKE_COMPLEX', 'NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY', 'BLACK_OBSERVATORY'],
  flying: true,
  mechanical: true,
  siege: true,
} satisfies Partial<UnitProfile>;
export const SPECIALIST_PROFILES = {
  NEUTRON_FLAK: {
    recruitAt: ['FLAK_BATTERY'],
    requires: ['NUCLEAR_REACTOR', 'ATOMIC_FOUNDRY', 'MUNITIONS'],
    minRecruitLevel: 5,
    mechanical: true,
    armored: true,
    radioactive: true,
    antiAir: 56,
    role: 'DCA lourde à neutrons : +56 dégâts contre les aéronefs, portée 6. Très lente et faible au sol ; 1 PA par tir.',
  },
  GLOCKE_WACHT: {
    ...bell,
    population: 20,
    minRecruitLevel: 2,
    antiAir: 18,
    role: 'Cloche d’escorte : décharge électrique et défense antiaérienne. Grande vision, sans capture ; 2 PA par tir.',
  },
  GLOCKE_STURM: {
    ...bell,
    population: 24,
    minRecruitLevel: 4,
    antiArmor: 22,
    role: 'Cloche de rupture : rayon antiblindage, plus mobile que le modèle ultime. Sans capture ; 2 PA par tir.',
  },
  TESLA_AIRSHIP: {
    recruitAt: ['AIRSHIP_YARD'],
    requires: ['TESLA_COIL', 'RADIO'],
    minRecruitLevel: 3,
    flying: true,
    mechanical: true,
    antiAir: 18,
    role: 'Dirigeable d’escorte électrique : protège les bombardiers contre les avions. Tir direct depuis les airs ; 1 PA.',
  },
  ISOTOPE_AIRSHIP: {
    recruitAt: ['AIRSHIP_YARD'],
    requires: ['NUCLEAR_REACTOR', 'MUNITIONS'],
    minRecruitLevel: 4,
    flying: true,
    mechanical: true,
    radioactive: true,
    siege: true,
    role: 'Bombardier isotopique : grande portée contre les fortifications, lent et vulnérable à la DCA ; 2 PA.',
  },
  ASH_DRAKE: {
    recruitAt: ['DRAGON_ROOST'],
    requires: ['OCCULT_LAB'],
    minRecruitLevel: 1,
    flying: true,
    siege: true,
    role: 'Jeune dragon de siège : souffle court, mobile mais fragile face à la DCA ; 2 PA.',
  },
  STORM_WYVERN: {
    recruitAt: ['DRAGON_ROOST'],
    requires: ['TESLA_COIL', 'ALCHEMY_FOUNDRY'],
    minRecruitLevel: 3,
    flying: true,
    antiAir: 18,
    role: 'Chasseuse des airs : vol rapide, éclairs et interception des aéronefs ; 1 PA par tir.',
  },
  RADIUM_DRAGON: {
    recruitAt: ['DRAGON_ROOST'],
    requires: ['NUCLEAR_REACTOR', 'ALCHEMY_FOUNDRY'],
    minRecruitLevel: 4,
    flying: true,
    radioactive: true,
    siege: true,
    role: 'Dragon irradié : souffle de siège puissant à courte portée ; 2 PA. Vulnérable à la DCA.',
  },
} satisfies Record<Kind, UnitProfile>;
export const SPECIALIST_TIERS = {
  NEUTRON_FLAK: 6,
  GLOCKE_WACHT: 7,
  GLOCKE_STURM: 7,
  TESLA_AIRSHIP: 4,
  ISOTOPE_AIRSHIP: 5,
  ASH_DRAKE: 3,
  STORM_WYVERN: 4,
  RADIUM_DRAGON: 5,
} as const;
export const SPECIALIST_ERAS = {
  NEUTRON_FLAK: 5,
  GLOCKE_WACHT: 5,
  GLOCKE_STURM: 5,
  TESLA_AIRSHIP: 4,
  ISOTOPE_AIRSHIP: 5,
  ASH_DRAKE: 3,
  STORM_WYVERN: 4,
  RADIUM_DRAGON: 5,
} as const;
export const SPECIALIST_CATEGORIES = {
  NEUTRON_FLAK: 'Artillerie',
  GLOCKE_WACHT: 'Cloches occultes',
  GLOCKE_STURM: 'Cloches occultes',
  TESLA_AIRSHIP: 'Aviation',
  ISOTOPE_AIRSHIP: 'Aviation',
  ASH_DRAKE: 'Aviation',
  STORM_WYVERN: 'Aviation',
  RADIUM_DRAGON: 'Aviation',
} satisfies Record<Kind, UnitTab>;
export const SPECIALIST_FRAMES = {
  NEUTRON_FLAK: 220,
  GLOCKE_WACHT: 432,
  GLOCKE_STURM: 456,
  TESLA_AIRSHIP: 99,
  ISOTOPE_AIRSHIP: 99,
  ASH_DRAKE: 100,
  STORM_WYVERN: 100,
  RADIUM_DRAGON: 100,
} as const;
export const SPECIALIST_WEAPONS = {
  NEUTRON_FLAK: 'lightning',
  GLOCKE_WACHT: 'lightning',
  GLOCKE_STURM: 'lightning',
  TESLA_AIRSHIP: 'lightning',
  ISOTOPE_AIRSHIP: 'bomb',
  ASH_DRAKE: 'flame',
  STORM_WYVERN: 'lightning',
  RADIUM_DRAGON: 'flame',
} as const;
